bat.d: specify relevant parameter(s) in warnings
Fix some threshold boundary conditions too.

diff --git a/bat.d/05-thinkpad b/bat.d/05-thinkpad
--- a/bat.d/05-thinkpad
+++ b/bat.d/05-thinkpad
@@ -500,6 +500,7 @@ batdrv_write_thresholds () {
     # $1: new start threshold 0(disabled)..99/DEF(default)
     # $2: new stop threshold 1..100/DEF(default)
     # $3: 0=quiet/1=output parameter errors/2=output progress and errors
+    # $4: battery - non-empty string indicates thresholds stem from configuration
     # global param: $_bm_thresh, $_bat_str, $_bat_idx, $_bf_start, $_bf_stop
     # rc: 0=ok/
     #     2=threshold(s) out of range or non-numeric/
@@ -510,6 +511,7 @@ batdrv_write_thresholds () {
     local new_start=$1
     local new_stop=$2
     local verb=${3:-0}
+    local cfg_bat="$4"
     local old_start old_stop
 
     # insert defaults
@@ -523,10 +525,21 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_start" 3 || \
        ! is_within_bounds $new_start 0 99; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3).invalid_start: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_start: bat=$_bat_str"
         case $verb in
-            1) echo_message "Warning: charge start threshold ($new_start) for $_bat_str not specified, invalid or out of range (0..99). Battery skipped." ;;
-            2) printf "Error: charge start threshold (%s) for %s not specified, invalid or out of range (0..99). Aborted.\n" "$new_start" $_bat_str 1>&2 ;;
+            1)
+                if [ -n "$cfg_bat" ]; then
+                    echo_message "Error in configuration at START_CHARGE_THRESH_${cfg_bat}=\"${new_start}\": not specified, invalid or out of range (0..99). Battery skipped."
+                fi
+                ;;
+
+            2)
+                if [ -n "$cfg_bat" ]; then
+                    printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..99). Aborted.\n" "$cfg_bat" "$new_start" 1>&2
+                else
+                    printf "Error: charge start threshold (%s) for %s is not specified, invalid or out of range (0..99). Aborted.\n" "$new_start" "$_bat_str" 1>&2
+                fi
+                ;;
         esac
         return 2
     fi
@@ -535,20 +548,42 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_stop" 3 || \
        ! is_within_bounds $new_stop 1 100; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3).invalid_stop: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str"
         case $verb in
-            1) echo_message "Warning: charge stop threshold ($new_stop) for $_bat_str not specified, invalid or out of range (1..100). Battery skipped." ;;
-            2) printf "Error: charge stop threshold (%s) for %s not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" $_bat_str 1>&2 ;;
+            1)
+                if [ -n "$cfg_bat" ]; then
+                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (1..100). Battery skipped."
+                fi
+                ;;
+
+            2)
+                if [ -n "$cfg_bat" ]; then
+                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
+                else
+                    printf "Error: charge stop threshold (%s) for %s is not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
+                fi
+                ;;
         esac
         return 2
     fi
 
-    # check minimum start - stop difference
-    if [ $((new_start + 4)) -gt $new_stop ]; then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3).invalid_diff: bat=$_bat_str"
+    # check if start < stop
+    if [ $new_start -ge $new_stop ]; then
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_diff: bat=$_bat_str"
         case $verb in
-            1) echo_message "Warning: charge start threshold > stop threshold - 4 for $_bat_str. Battery skipped." ;;
-            2) printf "Error: start threshold > stop threshold - 4 for %s. Aborted.\n" $_bat_str 1>&2 ;;
+            1)
+                if [ -n "$cfg_bat" ]; then
+                    echo_message "Error in configuration: START_CHARGE_THRESH_${cfg_bat} >= STOP_CHARGE_THRESH_${cfg_bat}. Battery skipped."
+                fi
+                ;;
+
+            2)
+                if [ -n "$cfg_bat" ]; then
+                    printf "Error in configuration: START_CHARGE_THRESH_%s >= STOP_CHARGE_THRESH_%s. Aborted.\n" "$cfg_bat" "$cfg_bat" 1>&2
+                else
+                    printf "Error: start threshold >= stop threshold for %s. Aborted.\n" "$_bat_str" 1>&2
+                fi
+                ;;
         esac
         return 3
     fi
@@ -556,10 +591,10 @@ batdrv_write_thresholds () {
     # read active threshold values
     if ! old_start=$(batdrv_read_threshold start) || \
        ! old_stop=$(batdrv_read_threshold stop); then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3).read_error: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str"
         case $verb in
             1) echo_message "Warning: could not read current charge threshold(s) for $_bat_str. Battery skipped." ;;
-            2) printf "Error: could not read current charge threshold(s) for %s. Aborted.\n" $_bat_str 1>&2 ;;
+            2) printf "Error: could not read current charge threshold(s) for %s. Aborted.\n" "$_bat_str" 1>&2 ;;
         esac
         return 4
     fi
@@ -572,8 +607,8 @@ batdrv_write_thresholds () {
 
     # determine write sequence because driver's intrinsic boundary conditions
     # must be met in all write stages:
-    #   - natacpi: start <= stop (write fails if not met)
-    #   - tpacpi:  nothing (maybe BIOS enforces something)
+    #   - natacpi: start < stop (write fails if not met)
+    #   - tpacpi:  nothing (maybe BIOS/ECP enforces something)
     local rc=0 steprc tseq
 
     if [ "$old_stop" != "none" ] && [ $new_start -gt $old_stop ]; then
@@ -633,7 +668,7 @@ batdrv_write_thresholds () {
                     rc=5
                     ;;
             esac
-            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3).$step.write: bat=$_bat_str; old=$old_thresh; new=$new_thresh; steprc=$steprc"
+            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.write: bat=$_bat_str; old=$old_thresh; new=$new_thresh; steprc=$steprc"
 
             case $verb in
                 2)
@@ -654,7 +689,7 @@ batdrv_write_thresholds () {
                     ;;
             esac
         else
-            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3).$step.no_change: bat=$_bat_str; old=$old_thresh; new=$new_thresh"
+            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.no_change: bat=$_bat_str; old=$old_thresh; new=$new_thresh"
 
             if [ "$verb" = "2" ]; then
                 printf "  %-5s = %3d (no change)\n" $step $new_thresh
@@ -662,7 +697,7 @@ batdrv_write_thresholds () {
         fi
     done # for step
 
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3).complete: bat=$_bat_str; rc=$rc"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).complete: bat=$_bat_str; rc=$rc"
     return $rc
 }
 
@@ -747,11 +782,11 @@ batdrv_apply_configured_thresholds () {
     # output parameter errors only
 
     if batdrv_select_battery BAT0; then
-        batdrv_write_thresholds "$START_CHARGE_THRESH_BAT0" "$STOP_CHARGE_THRESH_BAT0" 1; rc=$?
+        batdrv_write_thresholds "$START_CHARGE_THRESH_BAT0" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
     fi
     if batdrv_select_battery BAT1; then
         # write configured thresholds, output parameter errors
-        batdrv_write_thresholds "$START_CHARGE_THRESH_BAT1" "$STOP_CHARGE_THRESH_BAT1" 1; rc=$?
+        batdrv_write_thresholds "$START_CHARGE_THRESH_BAT1" "$STOP_CHARGE_THRESH_BAT1" 1 "BAT1"; rc=$?
     fi
 
     return 0
diff --git a/bat.d/15-asus b/bat.d/15-asus
--- a/bat.d/15-asus
+++ b/bat.d/15-asus
@@ -209,6 +209,7 @@ batdrv_write_thresholds () {
     # $1: new start threshold -- unused dummy for plugin api compatibility
     # $2: new stop threshold 1..100/DEF(default)
     # $3: 0=quiet/1=output parameter errors/2=output progress and errors
+    # $4: battery - non-empty string indicates thresholds stem from configuration
     # global param: $_bat_str, $_bf_stop
     # rc: 0=ok/
     #     2=threshold out of range or non-numeric/
@@ -216,8 +217,9 @@ batdrv_write_thresholds () {
     #     5=threshold write error
     # prerequisite: batdrv_init(), batdrv_select_battery()
     local new_stop=$2
-    local old_stop
     local verb=${3:-0}
+    local cfg_bat="$4"
+    local old_stop
 
     # insert defaults
     [ "$new_stop" = "DEF" ] && new_stop=$_bt_def_stop
@@ -229,17 +231,28 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_stop" 3 || \
        ! is_within_bounds $new_stop 1 100; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3).invalid_stop: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).invalid_stop: bat=$_bat_str"
         case $verb in
-            1) echo_message "Warning: charge stop threshold ($new_stop) for $_bat_str not specified, invalid or out of range (1..100). Battery skipped." ;;
-            2) printf "Error: charge stop threshold (%s) for %s not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" $_bat_str 1>&2 ;;
+            1)
+                if [ -n "$cfg_bat" ]; then
+                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (1..100). Battery skipped."
+                fi
+                ;;
+
+            2)
+                if [ -n "$cfg_bat" ]; then
+                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
+                else
+                    printf "Error: charge stop threshold (%s) for %s is not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
+                fi
+                ;;
         esac
         return 2
     fi
 
     # read active stop threshold value
     if ! old_stop=$(batdrv_read_threshold); then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3).read_error: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).read_error: bat=$_bat_str"
         case $verb in
             1) echo_message "Warning: could not read current charge stop threshold for $_bat_str. Battery skipped." ;;
             2) printf "Error: could not read current charge stop threshold for %s. Aborted.\n" $_bat_str 1>&2 ;;
@@ -256,7 +269,7 @@ batdrv_write_thresholds () {
     if [ "$old_stop" != "$new_stop" ]; then
         # new threshold differs from effective one --> write it
         write_sysf "$new_stop" $_bf_stop || rc=5
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3).write: bat=$_bat_str; old=$old_stop; new=$new_stop; rc=$rc"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).write: bat=$_bat_str; old=$old_stop; new=$new_stop; rc=$rc"
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
@@ -272,7 +285,7 @@ batdrv_write_thresholds () {
                 ;;
         esac
     else
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3).no_change: bat=$_bat_str; old=$old_stop; new=$new_stop"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).no_change: bat=$_bat_str; old=$old_stop; new=$new_stop"
         if [ "$verb" = "2" ]; then
                 printf "  stop = %3d (no change)\n" $new_stop
         fi
@@ -292,17 +305,17 @@ batdrv_apply_configured_thresholds () {
     # output parameter errors only
 
     if batdrv_select_battery BAT0; then
-        batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1; rc=$?
+        batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
     fi
     # BATC, BATT use BAT0 settings
     if batdrv_select_battery BATC; then
-        batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1; rc=$?
+        batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
     fi
     if batdrv_select_battery BATT; then
-        batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1; rc=$?
+        batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
     fi
     if batdrv_select_battery BAT1; then
-        batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT1" 1; rc=$?
+        batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT1" 1 "BAT1"; rc=$?
     fi
 
     return 0
diff --git a/bat.d/30-samsung b/bat.d/30-samsung
--- a/bat.d/30-samsung
+++ b/bat.d/30-samsung
@@ -197,6 +197,7 @@ batdrv_write_thresholds () {
     # $1: new start threshold -- unused dummy for plugin api compatibility
     # $2: new stop threshold 1..100/DEF(default)
     # $3: 0=quiet/1=output parameter errors/2=output progress and errors
+    # $4: battery - non-empty string indicates thresholds stem from configuration
     # global param: $_bat_str, $_bf_stop
     # rc: 0=ok/
     #     2=threshold out of range or non-numeric/
@@ -204,8 +205,9 @@ batdrv_write_thresholds () {
     #     5=threshold write error
     # prerequisite: batdrv_init(), batdrv_select_battery()
     local new_stop=$2
-    local old_stop
     local verb=${3:-0}
+    local cfg_bat="$4"
+    local old_stop
 
     # insert defaults
     [ "$new_stop" = "DEF" ] && new_stop=$_bt_def_stop
@@ -217,17 +219,28 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_stop" 3 || \
        ! is_within_bounds $new_stop 0 1; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3).invalid_stop"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).invalid_stop"
         case $verb in
-            1) echo_message "Warning: life extender ($new_stop) not specified or invalid (must be 0 or 1). Skipped." ;;
-            2) printf "Error: life extender (%s) not specified or invalid (must be 0 or 1). Aborted.\n" "$new_stop" 1>&2 ;;
+            1)
+                if [ -n "$cfg_bat" ]; then
+                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\": life extender not specified or invalid (must be 0 or 1). Skipped."
+                fi
+                ;;
+
+            2)
+                if [ -n "$cfg_bat" ]; then
+                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": life extender not specified or invalid (must be 0 or 1). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
+                else
+                    printf "Error: life extender (%s) not specified or invalid (must be 0 or 1). Aborted.\n" "$new_stop" 1>&2
+                fi
+                ;;
         esac
         return 2
     fi
 
     # read active stop threshold value
     if ! old_stop=$(batdrv_read_threshold); then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3).read_error"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).read_error"
         case $verb in
             1) echo_message "Warning: could not read current life extender. Skipped." ;;
             2) printf "Error: could not read current life extender. Aborted.\n" 1>&2 ;;
@@ -244,7 +257,7 @@ batdrv_write_thresholds () {
     if [ "$old_stop" != "$new_stop" ]; then
         # new threshold differs from effective one --> write it
         write_sysf "$new_stop" $_bf_stop || rc=5
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3).write: old=$old_stop; new=$new_stop; rc=$rc"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).write: old=$old_stop; new=$new_stop; rc=$rc"
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
@@ -260,7 +273,7 @@ batdrv_write_thresholds () {
                 ;;
         esac
     else
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3).no_change: old=$old_stop; new=$new_stop"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).no_change: old=$old_stop; new=$new_stop"
         if [ "$verb" = "2" ]; then
                 printf "  life extender = %d (no change)\n" $new_stop
         fi
@@ -279,7 +292,7 @@ batdrv_apply_configured_thresholds () {
     # apply configured battery life extender from configuration (concerns all batteries)
     # output parameter errors only
 
-    batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1; rc=$?
+    batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
 
     return 0
 }
