Unify wording: "start/stop charge threshold"

diff --git a/bat.d/05-thinkpad b/bat.d/05-thinkpad
--- a/bat.d/05-thinkpad
+++ b/bat.d/05-thinkpad
@@ -573,7 +573,7 @@ batdrv_write_thresholds () {
                 if [ -n "$cfg_bat" ]; then
                     printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..99). Aborted.\n" "$cfg_bat" "$new_start" 1>&2
                 else
-                    printf "Error: charge start threshold (%s) for %s is not specified, invalid or out of range (0..99). Aborted.\n" "$new_start" "$_bat_str" 1>&2
+                    printf "Error: start charge threshold (%s) for %s is not specified, invalid or out of range (0..99). Aborted.\n" "$new_start" "$_bat_str" 1>&2
                 fi
                 ;;
         esac
@@ -596,7 +596,7 @@ batdrv_write_thresholds () {
                 if [ -n "$cfg_bat" ]; then
                     printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
                 else
-                    printf "Error: charge stop threshold (%s) for %s is not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
+                    printf "Error: stop charge threshold (%s) for %s is not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
                 fi
                 ;;
         esac
@@ -751,7 +751,7 @@ batdrv_chargeonce () {
     local rc=0
 
     if ! cur_stop=$(batdrv_read_threshold stop 0); then
-        printf "Error: reading charge stop threshold for %s failed. Aborted.\n" "$_bat_str" 1>&2
+        printf "Error: reading stop charge threshold for %s failed. Aborted.\n" "$_bat_str" 1>&2
         echo_debug "bat" "batdrv.${_batdrv_plugin}.chargeonce($_bat_str).thresh_unknown: stop=$cur_stop; rc=4"
         return 4
     fi
diff --git a/bat.d/10-thinkpad-legacy b/bat.d/10-thinkpad-legacy
--- a/bat.d/10-thinkpad-legacy
+++ b/bat.d/10-thinkpad-legacy
@@ -315,7 +315,7 @@ batdrv_write_thresholds () {
                 if [ -n "$cfg_bat" ]; then
                     printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (2..96). Aborted.\n" "$cfg_bat" "$new_start" 1>&2
                 else
-                    printf "Error: charge start threshold (%s) for %s is not specified, invalid or out of range (2..96). Aborted.\n" "$new_start" "$_bat_str" 1>&2
+                    printf "Error: start charge threshold (%s) for %s is not specified, invalid or out of range (2..96). Aborted.\n" "$new_start" "$_bat_str" 1>&2
                 fi
                 ;;
         esac
@@ -338,7 +338,7 @@ batdrv_write_thresholds () {
                 if [ -n "$cfg_bat" ]; then
                     printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (6..100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
                 else
-                    printf "Error: charge stop threshold (%s) for %s is not specified, invalid or out of range (6..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
+                    printf "Error: stop charge threshold (%s) for %s is not specified, invalid or out of range (6..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
                 fi
                 ;;
         esac
@@ -459,11 +459,11 @@ batdrv_chargeonce () {
     local rc=0
 
     if ! cur_stop=$(batdrv_read_threshold stop 0); then
-        printf "Error: reading charge stop threshold for %s failed. Aborted.\n" "$_bat_str" 1>&2
+        printf "Error: reading stop charge threshold for %s failed. Aborted.\n" "$_bat_str" 1>&2
         echo_debug "bat" "batdrv.${_batdrv_plugin}.chargeonce($_bat_str).thresh_unknown: stop=$cur_stop; rc=4"
         return 4
     elif [ "$cur_stop" -lt 6 ]; then
-        printf "Error: the %s charge stop threshold is %s. " "$_bat_str" "$ccharge"  1>&2
+        printf "Error: the %s stop charge threshold is %s. " "$_bat_str" "$ccharge"  1>&2
         printf "For this command to work, it must be 6 at least.\n"  1>&2
         echo_debug "bat" "batdrv.${_batdrv_plugin}.chargeonce($_bat_str).stop_thresh_too_low: stop=$cur_stop; rc=6"
         return 6
diff --git a/bat.d/35-lg b/bat.d/35-lg
--- a/bat.d/35-lg
+++ b/bat.d/35-lg
@@ -261,7 +261,7 @@ batdrv_write_thresholds () {
                 if [ -n "$cfg_bat" ]; then
                     printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified or invalid (must be 80 or 100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
                 else
-                    printf "Error: charge stop threshold (%s) not specified or invalid (must be 80 or 100). Aborted.\n" "$new_stop" 1>&2
+                    printf "Error: stop charge threshold (%s) not specified or invalid (must be 80 or 100). Aborted.\n" "$new_stop" 1>&2
                 fi
                 ;;
         esac
@@ -272,8 +272,8 @@ batdrv_write_thresholds () {
     if ! old_stop=$(batdrv_read_threshold); then
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).read_error"
         case $verb in
-            1) echo_message "Error: could not read current charge stop threshold. Skipped." ;;
-            2) printf "Error: could not read current charge stop threshold. Aborted.\n" 1>&2 ;;
+            1) echo_message "Error: could not read current stop charge threshold. Skipped." ;;
+            2) printf "Error: could not read current stop charge threshold. Aborted.\n" 1>&2 ;;
         esac
         return 4
     fi
@@ -306,7 +306,7 @@ batdrv_write_thresholds () {
                 ;;
             1)
                 if [ $rc -gt 0 ]; then
-                    echo_message "Error: writing charge stop threshold failed."
+                    echo_message "Error: writing stop charge threshold failed."
                 fi
                 ;;
         esac
diff --git a/bat.d/50-toshiba b/bat.d/50-toshiba
--- a/bat.d/50-toshiba
+++ b/bat.d/50-toshiba
@@ -265,7 +265,7 @@ batdrv_write_thresholds () {
                 if [ -n "$cfg_bat" ]; then
                     printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified or invalid (must be 80 or 100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
                 else
-                    printf "Error: charge stop threshold (%s) for %s is not specified or invalid (must be 80 or 100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
+                    printf "Error: stop charge threshold (%s) for %s is not specified or invalid (must be 80 or 100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
                 fi
                 ;;
         esac
@@ -302,7 +302,7 @@ batdrv_write_thresholds () {
                 ;;
             1)
                 if [ $rc -gt 0 ]; then
-                    echo_message "Error: writing charge stop threshold for $_bat_str failed."
+                    echo_message "Error: writing stop charge threshold for $_bat_str failed."
                 fi
                 ;;
         esac
diff --git a/bat.d/TEMPLATE b/bat.d/TEMPLATE
--- a/bat.d/TEMPLATE
+++ b/bat.d/TEMPLATE
@@ -300,7 +300,7 @@ batdrv_write_thresholds () {
                 if [ -n "$cfg_bat" ]; then
                     printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..100). Aborted.\n" "$cfg_bat" "$new_start" 1>&2
                 else
-                    printf "Error: charge start threshold (%s) for %s is not specified, invalid or out of range (0..100). Aborted.\n" "$new_start" "$_bat_str" 1>&2
+                    printf "Error: start charge threshold (%s) for %s is not specified, invalid or out of range (0..100). Aborted.\n" "$new_start" "$_bat_str" 1>&2
                 fi
                 ;;
         esac
@@ -324,7 +324,7 @@ batdrv_write_thresholds () {
                 if [ -n "$cfg_bat" ]; then
                     printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
                 else
-                    printf "Error: charge stop threshold (%s) for %s is not specified, invalid or out of range (0..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
+                    printf "Error: stop charge threshold (%s) for %s is not specified, invalid or out of range (0..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
                 fi
                 ;;
         esac
