CQM: make shellcheck happy once again (SC2086)

diff --git a/bat.d/05-thinkpad b/bat.d/05-thinkpad
--- a/bat.d/05-thinkpad
+++ b/bat.d/05-thinkpad
@@ -384,7 +384,7 @@ batdrv_select_battery () {
 
         BAT1)
             _bat_str="$bs"
-            if [ $_tpacpi -le 1 ]; then
+            if [ "$_tpacpi" -le 1 ]; then
                 # tpacpi: try to read start threshold for index 2
                 if $TPACPIBAT -g ST 2 2> /dev/null 1>&2 ; then
                     _bat_idx=2 # BAT1 is aux
@@ -473,15 +473,15 @@ batdrv_read_threshold () {
         tpacpi)
             case $1 in
                 start)
-                    out=$($TPACPIBAT -g ST $_bat_idx 2> /dev/null | cut -f1 -d' ')
+                    out=$($TPACPIBAT -g ST "$_bat_idx" 2> /dev/null | cut -f1 -d' ')
                     # workaround: read threshold a second time (see above)
-                    out=$($TPACPIBAT -g ST $_bat_idx 2> /dev/null | cut -f1 -d' ')
+                    out=$($TPACPIBAT -g ST "$_bat_idx" 2> /dev/null | cut -f1 -d' ')
                     ;;
 
                 stop)
-                    out=$($TPACPIBAT -g SP $_bat_idx 2> /dev/null | cut -f1 -d' ')
+                    out=$($TPACPIBAT -g SP "$_bat_idx" 2> /dev/null | cut -f1 -d' ')
                     # workaround: read threshold a second time (see above)
-                    out=$($TPACPIBAT -g SP $_bat_idx 2> /dev/null | cut -f1 -d' ')
+                    out=$($TPACPIBAT -g SP "$_bat_idx" 2> /dev/null | cut -f1 -d' ')
                     ;;
             esac
             # shellcheck disable=SC2181
@@ -490,7 +490,7 @@ batdrv_read_threshold () {
                     # remove offset of 128 for Edge S430 et al.
                     out=$((out - 128))
                 fi
-                if [ "$1" = "stop" ] && [ $out -eq 0 ]; then
+                if [ "$1" = "stop" ] && [ "$out" -eq 0 ]; then
                     # stop: 0 (hardware default) means 100
                     out=100
                 fi
@@ -647,7 +647,7 @@ batdrv_write_thresholds () {
     #   - tpacpi:  nothing (maybe BIOS/ECP enforces something)
     local rc=0 steprc tseq
 
-    if [ "$old_stop" != "none" ] && [ $new_start -ge $old_stop ]; then
+    if [ "$old_stop" != "none" ] && [ "$new_start" -ge "$old_stop" ]; then
         tseq="stop start"
     else
         tseq="start stop"
@@ -686,13 +686,13 @@ batdrv_write_thresholds () {
 
                 tpacpi)
                     case $step in
-                        start) $TPACPIBAT -s ST $_bat_idx $new_thresh > /dev/null 2>&1 ;;
+                        start) $TPACPIBAT -s ST "$_bat_idx" "$new_thresh" > /dev/null 2>&1 ;;
                         stop)
-                            if [ $new_thresh -eq 100 ]; then
+                            if [ "$new_thresh" -eq 100 ]; then
                                 # tpacpi-bat won't accept 100
-                                $TPACPIBAT -s SP $_bat_idx 0 > /dev/null 2>&1
+                                $TPACPIBAT -s SP "$_bat_idx" 0 > /dev/null 2>&1
                             else
-                                $TPACPIBAT -s SP $_bat_idx $new_thresh > /dev/null 2>&1
+                                $TPACPIBAT -s SP "$_bat_idx" "$new_thresh" > /dev/null 2>&1
                             fi
                             ;;
                     esac
@@ -708,13 +708,13 @@ batdrv_write_thresholds () {
             case $verb in
                 2)
                     if [ $steprc -eq 0 ]; then
-                        if [ "$step" = "start" ] && [ $new_thresh -eq 0 ]; then
-                            printf "  %-5s = %3d (disabled)\n" "$step" $new_thresh
+                        if [ "$step" = "start" ] && [ "$new_thresh" -eq 0 ]; then
+                            printf "  %-5s = %3d (disabled)\n" "$step" "$new_thresh"
                         else
-                            printf "  %-5s = %3d\n" "$step" $new_thresh
+                            printf "  %-5s = %3d\n" "$step" "$new_thresh"
                         fi
                     else
-                        printf "  %-5s = %3d (Error: write failed)\n" "$step" $new_thresh 1>&2
+                        printf "  %-5s = %3d (Error: write failed)\n" "$step" "$new_thresh" 1>&2
                     fi
                     ;;
                 1)
@@ -727,7 +727,7 @@ batdrv_write_thresholds () {
             echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.no_change: bat=$_bat_str; old=$old_thresh; new=$new_thresh"
 
             if [ "$verb" = "2" ]; then
-                printf "  %-5s = %3d (no change)\n" "$step" $new_thresh
+                printf "  %-5s = %3d (no change)\n" "$step" "$new_thresh"
             fi
         fi
     done # for step
@@ -777,14 +777,14 @@ batdrv_chargeonce () {
             ;;
     esac
 
-    if [ $ccharge -eq -1 ]; then
+    if [ "$ccharge" -eq -1 ]; then
         printf "Error: cannot determine charge level for %s.\n" "$_bat_str" 1>&2
         echo_debug "bat" "batdrv.${_batdrv_plugin}.chargeonce($_bat_str).charge_level_unknown: enow=$enow; efull=$efull; rc=2"
         return 2
     fi
 
     temp_start=$(( cur_stop - 1 ))
-    if [ $ccharge -gt $temp_start ]; then
+    if [ "$ccharge" -gt "$temp_start" ]; then
         printf "Error: the %s charge level is %s%%. " "$_bat_str" "$ccharge"  1>&2
         printf "For this command to work, it must not exceed %s%% (stop threshold - 1).\n" "$temp_start" 1>&2
         echo_debug "bat" "batdrv.${_batdrv_plugin}.chargeonce($_bat_str).charge_level_too_high: soc=$ccharge; stop=$cur_stop; rc=3"
@@ -798,14 +798,14 @@ batdrv_chargeonce () {
             ;;
 
         tpacpi)
-            $TPACPIBAT -s ST $_bat_idx $temp_start > /dev/null 2>&1 || rc=5
+            $TPACPIBAT -s ST "$_bat_idx" "$temp_start" > /dev/null 2>&1 || rc=5
             ;;
     esac
 
     if [ $rc -eq 0 ]; then
-        printf "  start = %3d\n" $temp_start
+        printf "  start = %3d\n" "$temp_start"
     else
-        printf "  start = %3d (Error: write failed)\n" $temp_start 1>&2
+        printf "  start = %3d (Error: write failed)\n" "$temp_start" 1>&2
     fi
     echo_debug "bat" "batdrv.${_batdrv_plugin}.chargeonce($_bat_str): soc=$ccharge; start=$temp_start; stop=$cur_stop; rc=$rc"
 
@@ -862,7 +862,7 @@ batdrv_read_force_discharge () {
             ;;
 
         tpacpi) # read via tpacpi-bat
-            case $($TPACPIBAT -g FD $_bat_idx 2> /dev/null) in
+            case "$($TPACPIBAT -g FD "$_bat_idx" 2> /dev/null)" in
                 yes) out=1 ;;
                 no)  out=0 ;;
                 *)
@@ -911,7 +911,7 @@ batdrv_write_force_discharge () {
             ;; # natacpi
 
         tpacpi) # use tpacpi-bat
-            $TPACPIBAT -s FD $_bat_idx "$1" > /dev/null 2>&1 || rc=5
+            $TPACPIBAT -s FD "$_bat_idx" "$1" > /dev/null 2>&1 || rc=5
             ;; # tpcpaci
 
         *) # no discharge api
@@ -1312,7 +1312,7 @@ batdrv_show_battery_data () {
             perl -e 'printf ("%-59s = %6.1f [%%]\n", "Capacity", 100.0 * '"$ef"' / '"$ed"');'
             lf=1
         fi
-        [ $lf -gt 0 ] && printf "\n"
+        [ "$lf" -gt 0 ] && printf "\n"
 
         bcnt=$((bcnt+1))
 
diff --git a/bat.d/20-huawei b/bat.d/20-huawei
--- a/bat.d/20-huawei
+++ b/bat.d/20-huawei
@@ -174,7 +174,7 @@ batdrv_read_threshold () {
     fi
 
     if [ "$_bm_thresh" = "natacpi" ]; then
-        out=$(read_sysf $_bf_start_stop) || rc=4
+        out=$(read_sysf "$_bf_start_stop") || rc=4
     else
         rc=255
     fi
@@ -299,9 +299,9 @@ batdrv_write_thresholds () {
     case $verb in
         2)
             if [ $rc -eq 0 ]; then
-                printf "  %s = %d, %s = %d\n" start $new_start stop $new_stop
+                printf "  %s = %d, %s = %d\n" start "$new_start" stop "$new_stop"
             else
-                printf "  %s = %d, %s = %d (Error: write failed)\n" start $new_start stop $new_stop 1>&2
+                printf "  %s = %d, %s = %d (Error: write failed)\n" start "$new_start" stop "$new_stop" 1>&2
             fi
             ;;
         1)
@@ -469,15 +469,15 @@ batdrv_show_battery_data () {
 
         # --- show charge level (SOC) and capacity
         lf=0
-        if [ $ef -ne 0 ]; then
+        if [ "$ef" -ne 0 ]; then
             perl -e 'printf ("%-59s = %6.1f [%%]\n", "Charge",   100.0 * '"$en"' / '"$ef"');'
             lf=1
         fi
-        if [ $ed -ne 0 ]; then
+        if [ "$ed" -ne 0 ]; then
             perl -e 'printf ("%-59s = %6.1f [%%]\n", "Capacity", 100.0 * '"$ef"' / '"$ed"');'
             lf=1
         fi
-        [ $lf -gt 0 ] && printf "\n"
+        [ "$lf" -gt 0 ] && printf "\n"
 
         bcnt=$((bcnt+1))
 
diff --git a/bat.d/25-lenovo b/bat.d/25-lenovo
--- a/bat.d/25-lenovo
+++ b/bat.d/25-lenovo
@@ -174,7 +174,7 @@ batdrv_read_threshold () {
     fi
 
     if [ "$_bm_thresh" = "natacpi" ]; then
-        out=$(read_sysf $_bf_stop) || rc=4
+        out=$(read_sysf "$_bf_stop") || rc=4
     else
         # no threshold api
         rc=255
@@ -268,9 +268,9 @@ batdrv_write_thresholds () {
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
-                    printf "  conservation mode = %d\n" $new_stop
+                    printf "  conservation mode = %d\n" "$new_stop"
                 else
-                    printf "  conservation mode = %d (Error: write failed)\n" $new_stop 1>&2
+                    printf "  conservation mode = %d (Error: write failed)\n" "$new_stop" 1>&2
                 fi
                 ;;
             1)
@@ -282,7 +282,7 @@ batdrv_write_thresholds () {
     else
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).no_change: old=$old_stop; new=$new_stop"
         if [ "$verb" = "2" ]; then
-                printf "  conservation mode = %d (no change)\n" $new_stop
+                printf "  conservation mode = %d (no change)\n" "$new_stop"
         fi
     fi
 
@@ -442,15 +442,15 @@ batdrv_show_battery_data () {
         # --- show battery features: thresholds
 
         # --- show charge level (SOC) and capacity
-        if [ $ef -ne 0 ]; then
+        if [ "$ef" -ne 0 ]; then
             perl -e 'printf ("%-59s = %6.1f [%%]\n", "Charge",   100.0 * '"$en"' / '"$ef"');'
             lf=1
         fi
-        if [ $ed -ne 0 ]; then
+        if [ "$ed" -ne 0 ]; then
             perl -e 'printf ("%-59s = %6.1f [%%]\n", "Capacity", 100.0 * '"$ef"' / '"$ed"');'
             lf=1
         fi
-        [ $lf -gt 0 ] && printf "\n"
+        [ "$lf" -gt 0 ] && printf "\n"
 
         bcnt=$((bcnt+1))
 
diff --git a/bat.d/35-lg b/bat.d/35-lg
--- a/bat.d/35-lg
+++ b/bat.d/35-lg
@@ -286,8 +286,8 @@ batdrv_write_thresholds () {
     local rc=0
     if [ "$old_stop" != "$new_stop" ]; then
         # new threshold differs from effective one --> write it
-        if write_sysf "$new_stop" $_bf_stop; then
-            if [ "$(read_sysf $_bf_stop)" != "$new_stop" ]; then
+        if write_sysf "$new_stop" "$_bf_stop"; then
+            if [ "$(read_sysf "$_bf_stop")" != "$new_stop" ]; then
                 #  write discarded by kernel or firmware
                 rc=6
             fi
@@ -299,9 +299,9 @@ batdrv_write_thresholds () {
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
-                    printf "  stop = %d\n" $new_stop
+                    printf "  stop = %d\n" "$new_stop"
                 else
-                    printf "  stop = %d (Error: write failed)\n" $new_stop 1>&2
+                    printf "  stop = %d (Error: write failed)\n" "$new_stop" 1>&2
                 fi
                 ;;
             1)
@@ -313,7 +313,7 @@ batdrv_write_thresholds () {
     else
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).no_change: old=$old_stop; new=$new_stop"
         if [ "$verb" = "2" ]; then
-                printf "  stop = %d (no change)\n" $new_stop
+                printf "  stop = %d (no change)\n" "$new_stop"
         fi
     fi
 
@@ -479,15 +479,15 @@ batdrv_show_battery_data () {
         fi
 
         # --- show charge level (SOC) and capacity
-        if [ $ef -ne 0 ]; then
+        if [ "$ef" -ne 0 ]; then
             perl -e 'printf ("%-59s = %6.1f [%%]\n", "Charge",   100.0 * '"$en"' / '"$ef"');'
             lf=1
         fi
-        if [ $ed -ne 0 ]; then
+        if [ "$ed" -ne 0 ]; then
             perl -e 'printf ("%-59s = %6.1f [%%]\n", "Capacity", 100.0 * '"$ef"' / '"$ed"');'
             lf=1
         fi
-        [ $lf -gt 0 ] && printf "\n"
+        [ "$lf" -gt 0 ] && printf "\n"
 
         bcnt=$((bcnt+1))
 
diff --git a/bat.d/36-lg-legacy b/bat.d/36-lg-legacy
--- a/bat.d/36-lg-legacy
+++ b/bat.d/36-lg-legacy
@@ -92,7 +92,7 @@ batdrv_init () {
     if [ "$NATACPI_ENABLE" = "0" ]; then
         # natacpi disabled in configuration --> skip actual detection
         _natacpi=32
-    elif sp="${X_THRESH_SIMULATE_STOP:-$(read_sysf $BATDRV_LG_BCL)}"; then
+    elif sp="${X_THRESH_SIMULATE_STOP:-$(read_sysf "$BATDRV_LG_BCL")}"; then
         # sysfile exists and is actually readable --> check threshold value
         if [ "$sp" != "0" ]; then
             # threshold is non-zero
@@ -173,7 +173,7 @@ batdrv_read_threshold () {
     fi
 
     if [ "$_bm_thresh" = "natacpi" ]; then
-        out=$(read_sysf $_bf_stop) || rc=4
+        out=$(read_sysf "$_bf_stop") || rc=4
     else
         # no threshold api
         rc=255
@@ -262,8 +262,8 @@ batdrv_write_thresholds () {
     local rc=0
     if [ "$old_stop" != "$new_stop" ]; then
         # new threshold differs from effective one --> write it
-        if write_sysf "$new_stop" $_bf_stop; then
-            if [ "$(read_sysf $_bf_stop)" != "$new_stop" ]; then
+        if write_sysf "$new_stop" "$_bf_stop"; then
+            if [ "$(read_sysf "$_bf_stop")" != "$new_stop" ]; then
                 #  write discarded by kernel or firmware
                 rc=6
             fi
@@ -275,9 +275,9 @@ batdrv_write_thresholds () {
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
-                    printf "  care limit = %d\n" $new_stop
+                    printf "  care limit = %d\n" "$new_stop"
                 else
-                    printf "  care limit = %d (Error: write failed)\n" $new_stop 1>&2
+                    printf "  care limit = %d (Error: write failed)\n" "$new_stop" 1>&2
                 fi
                 ;;
             1)
@@ -289,7 +289,7 @@ batdrv_write_thresholds () {
     else
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).no_change: old=$old_stop; new=$new_stop"
         if [ "$verb" = "2" ]; then
-                printf "  care limit = %d (no change)\n" $new_stop
+                printf "  care limit = %d (no change)\n" "$new_stop"
         fi
     fi
 
@@ -444,15 +444,15 @@ batdrv_show_battery_data () {
         # --- show battery features: thresholds
 
         # --- show charge level (SOC) and capacity
-        if [ $ef -ne 0 ]; then
+        if [ "$ef" -ne 0 ]; then
             perl -e 'printf ("%-59s = %6.1f [%%]\n", "Charge",   100.0 * '"$en"' / '"$ef"');'
             lf=1
         fi
-        if [ $ed -ne 0 ]; then
+        if [ "$ed" -ne 0 ]; then
             perl -e 'printf ("%-59s = %6.1f [%%]\n", "Capacity", 100.0 * '"$ef"' / '"$ed"');'
             lf=1
         fi
-        [ $lf -gt 0 ] && printf "\n"
+        [ "$lf" -gt 0 ] && printf "\n"
 
         bcnt=$((bcnt+1))
 
diff --git a/bat.d/50-toshiba b/bat.d/50-toshiba
--- a/bat.d/50-toshiba
+++ b/bat.d/50-toshiba
@@ -294,9 +294,9 @@ batdrv_write_thresholds () {
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
-                    printf "  stop = %3d\n" $new_stop
+                    printf "  stop = %3d\n" "$new_stop"
                 else
-                    printf "  stop = %3d (Error: write failed)\n" $new_stop 1>&2
+                    printf "  stop = %3d (Error: write failed)\n" "$new_stop" 1>&2
                 fi
                 ;;
             1)
@@ -309,7 +309,7 @@ batdrv_write_thresholds () {
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).no_change: bat=$_bat_str; old=$old_stop; new=$new_stop"
 
         if [ "$verb" = "2" ]; then
-            printf "  stop = %3d (no change)\n" $new_stop 1>&2
+            printf "  stop = %3d (no change)\n" "$new_stop" 1>&2
         fi
     fi
 
@@ -468,15 +468,15 @@ batdrv_show_battery_data () {
 
         # --- show charge level (SOC) and capacity
         lf=0
-        if [ $ef -ne 0 ]; then
+        if [ "$ef" -ne 0 ]; then
             perl -e 'printf ("%-59s = %6.1f [%%]\n", "Charge",   100.0 * '"$en"' / '"$ef"');'
             lf=1
         fi
-        if [ $ed -ne 0 ]; then
+        if [ "$ed" -ne 0 ]; then
             perl -e 'printf ("%-59s = %6.1f [%%]\n", "Capacity", 100.0 * '"$ef"' / '"$ed"');'
             lf=1
         fi
-        [ $lf -gt 0 ] && printf "\n"
+        [ "$lf" -gt 0 ] && printf "\n"
 
         bcnt=$((bcnt+1))
 
