CQM: activate shellcheck SC2086 (bat.d/*)

diff --git a/bat.d/10-thinkpad-legacy b/bat.d/10-thinkpad-legacy
--- a/bat.d/10-thinkpad-legacy
+++ b/bat.d/10-thinkpad-legacy
@@ -8,8 +8,6 @@
 
 # Needs: tlp-func-base, 35-tlp-func-batt, tlp-func-stat, 05-thinkpad
 
-# shellcheck disable=SC2086
-
 # --- Plugin API functions
 
 batdrv_init () {
@@ -86,7 +84,7 @@ batdrv_init () {
 
     # iterate batteries
     for bd in "$ACPIBATDIR"/BAT[01]; do
-        if [ "$(read_sysf $bd/present)" = "1" ]; then
+        if [ "$(read_sysf "$bd/present")" = "1" ]; then
             # record detected batteries and directories
             bs=${bd##/*/}
             if [ -n "$_batteries" ]; then
@@ -104,9 +102,9 @@ batdrv_init () {
     fi
 
     # --- probe tp-smapi external kernel module
-    load_modules $MOD_TPSMAPI
+    load_modules "$MOD_TPSMAPI"
 
-    if [ -d $SMAPIBATDIR ]; then
+    if [ -d "$SMAPIBATDIR" ]; then
         # module loaded --> tp-smapi available
         if [ "$TPSMAPI_ENABLE" = "0" ]; then
             # tpsmapi disabled by configuration
@@ -127,7 +125,7 @@ batdrv_init () {
                 fi
             done
         fi
-    elif $MODINFO $MOD_TPSMAPI > /dev/null 2>&1; then
+    elif $MODINFO "$MOD_TPSMAPI" > /dev/null 2>&1; then
         # module installed but not loaded
         _tpsmapi=64
     else
@@ -237,7 +235,7 @@ batdrv_read_threshold () {
                 start) bf=$_bf_start ;;
                 stop)  bf=$_bf_stop  ;;
             esac
-            if ! out=$(read_sysf $bf); then
+            if ! out=$(read_sysf "$bf"); then
                 # not readable/non-existent
                 if [ "$2" != "1" ]; then
                     out=""
@@ -303,7 +301,7 @@ batdrv_write_thresholds () {
 
     # start: check for 3 digits max, ensure min 2 / max 96
     if ! is_uint "$new_start" 3 || \
-       ! is_within_bounds $new_start 2 96; then
+       ! is_within_bounds "$new_start" 2 96; then
         # threshold out of range
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_start: bat=$_bat_str"
         case $verb in
@@ -326,7 +324,7 @@ batdrv_write_thresholds () {
 
     # stop: check for 3 digits max, ensure min 6 / max 100
     if ! is_uint "$new_stop" 3 || \
-       ! is_within_bounds $new_stop 6 100; then
+       ! is_within_bounds "$new_stop" 6 100; then
         # threshold out of range
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str"
         case $verb in
@@ -348,7 +346,7 @@ batdrv_write_thresholds () {
     fi
 
     # check minimum start - stop difference
-    if [ $((new_start + 4)) -gt $new_stop ]; then
+    if [ $((new_start + 4)) -gt "$new_stop" ]; then
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_diff: bat=$_bat_str"
         case $verb in
             1)
@@ -374,7 +372,7 @@ batdrv_write_thresholds () {
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str"
         case $verb in
             1) echo_message "Error: could not read current charge threshold(s) for $_bat_str. Battery skipped." ;;
-            2) printf "Error: could not read current charge threshold(s) for %s. Aborted.\n" $_bat_str 1>&2 ;;
+            2) printf "Error: could not read current charge threshold(s) for %s. Aborted.\n" "$_bat_str" 1>&2 ;;
         esac
         return 4
     fi
@@ -384,7 +382,7 @@ batdrv_write_thresholds () {
     #   - tpsmapi: start <= stop - 4 (changes value for compliance)
     local rc=0 steprc tseq
 
-    if [ $new_start -gt $old_stop ]; then
+    if [ "$new_start" -gt "$old_stop" ]; then
         tseq="stop start"
     else
         tseq="start stop"
@@ -415,8 +413,8 @@ batdrv_write_thresholds () {
             case $_bm_thresh in
                 tpsmapi)
                     case $step in
-                        start) write_sysf "$new_thresh" $_bf_start ;;
-                        stop)  write_sysf "$new_thresh" $_bf_stop  ;;
+                        start) write_sysf "$new_thresh" "$_bf_start" ;;
+                        stop)  write_sysf "$new_thresh" "$_bf_stop"  ;;
                     esac
                     steprc=$?; [ $steprc -ne 0 ] && [ $rc -eq 0 ] && rc=5
                     ;;
@@ -431,9 +429,9 @@ batdrv_write_thresholds () {
             case $verb in
                 2)
                     if [ $steprc -eq 0 ]; then
-                        printf "  %-5s = %3d\n" $step $new_thresh
+                        printf "  %-5s = %3d\n" "$step" "$new_thresh"
                     else
-                        printf "  %-5s = %3d (Error: write failed)\n" $step $new_thresh 1>&2
+                        printf "  %-5s = %3d (Error: write failed)\n" "$step" "$new_thresh" 1>&2
                     fi
                     ;;
                 1)
@@ -446,7 +444,7 @@ batdrv_write_thresholds () {
             echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.no_change: bat=$_bat_str; old=$old_thresh; new=$new_thresh"
 
             if [ "$verb" = "2" ]; then
-                printf "  %-5s = %3d (no change)\n" $step $new_thresh
+                printf "  %-5s = %3d (no change)\n" "$step" "$new_thresh"
             fi
         fi
     done # for step
@@ -471,10 +469,10 @@ batdrv_chargeonce () {
     local rc=0
 
     if ! cur_stop=$(batdrv_read_threshold stop 0); then
-        printf "Error: reading charge stop threshold for %s failed. Aborted.\n" $_bat_str 1>&2
+        printf "Error: reading charge stop threshold for %s failed. Aborted.\n" "$_bat_str" 1>&2
         echo_debug "bat" "batdrv.${_batdrv_plugin}.chargeonce($_bat_str).thresh_unknown: stop=$cur_stop; rc=4"
         return 4
-    elif [ $cur_stop -lt 6 ]; then
+    elif [ "$cur_stop" -lt 6 ]; then
         printf "Error: the %s charge stop threshold is %s. " "$_bat_str" "$ccharge"  1>&2
         printf "For this command to work, it must be 6 at least.\n"  1>&2
         echo_debug "bat" "batdrv.${_batdrv_plugin}.chargeonce($_bat_str).stop_thresh_too_low: stop=$cur_stop; rc=6"
@@ -484,7 +482,7 @@ batdrv_chargeonce () {
     # get current charge level (in %)
     case $_bm_read in
         tpsmapi) # use tp-smapi sysfile
-            ccharge=$(read_sysval $_bd_read/remaining_percent) || ccharge=-1
+            ccharge=$(read_sysval "$_bd_read/remaining_percent") || ccharge=-1
             ;;
     esac
 
@@ -505,14 +503,14 @@ batdrv_chargeonce () {
     printf "Setting temporary charge threshold for %s:" "$_bat_str"
     case $_bm_thresh in
         tpsmapi)
-            write_sysf "$temp_start" $_bf_start || rc=5
+            write_sysf "$temp_start" "$_bf_start" || rc=5
             ;;
     esac
 
     if [ $rc -eq 0 ]; then
-        printf "  start = %3d\n" $temp_start
+        printf "  start = %3d\n" "$temp_start"
     else
-        printf "  start = %3d (Error: write failed)\n" $temp_start 1>&2
+        printf "  start = %3d (Error: write failed)\n" "$temp_start" 1>&2
     fi
     echo_debug "bat" "batdrv.${_batdrv_plugin}.chargeonce($_bat_str): soc=$ccharge; start=$temp_start; stop=$cur_stop; rc=$rc"
 
@@ -548,8 +546,8 @@ batdrv_read_force_discharge () {
     case $_bm_dischg in
         tpsmapi)
             # read force discharge from sysfile
-            out=$(read_sysf $_bf_dischg);
-            if ! out=$(read_sysf $_bf_dischg); then
+            out=$(read_sysf "$_bf_dischg");
+            if ! out=$(read_sysf "$_bf_dischg"); then
                 # not readable/non-existent
                 if [ "$1" = "1" ]; then
                     out="(not available)"
@@ -583,7 +581,7 @@ batdrv_write_force_discharge () {
     case $_bm_dischg in
         tpsmapi)
             # write force_discharge
-            write_sysf "$1" $_bf_dischg || rc=5
+            write_sysf "$1" "$_bf_dischg" || rc=5
             ;;
 
         *) # no discharge api
@@ -667,13 +665,13 @@ batdrv_discharge () {
             # show current battery state
             case $_bm_read in
                 tpsmapi) # use tp-smapi sysfiles
-                    printf "voltage            = %6s [mV]\n"  "$(read_sysf $_bd_read/voltage)"
-                    printf "remaining capacity = %6s [mWh]\n" "$(read_sysf $_bd_read/remaining_capacity)"
-                    rp=$(read_sysf $_bd_read/remaining_percent)
+                    printf "voltage            = %6s [mV]\n"  "$(read_sysf "$_bd_read/voltage")"
+                    printf "remaining capacity = %6s [mWh]\n" "$(read_sysf "$_bd_read/remaining_capacity")"
+                    rp=$(read_sysf "$_bd_read/remaining_percent")
                     printf "remaining percent  = %6s [%%]\n"  "$rp"
-                    printf "remaining time     = %6s [min]\n" "$(read_sysf $_bd_read/remaining_running_time_now)"
-                    printf "power              = %6s [mW]\n"  "$(read_sysf $_bd_read/power_avg)"
-                    printf "state              = %s\n"  "$(read_sysf $_bd_read/state)"
+                    printf "remaining time     = %6s [min]\n" "$(read_sysf "$_bd_read/remaining_running_time_now")"
+                    printf "power              = %6s [mW]\n"  "$(read_sysf "$_bd_read/power_avg")"
+                    printf "state              = %s\n"  "$(read_sysf "$_bd_read/state")"
                     ;; # tpsmapi
 
             esac
@@ -687,16 +685,16 @@ batdrv_discharge () {
         # read charge level one last time
         case $_bm_read in
             tpsmapi) # use tp-smapi sysfiles
-                rp=$(read_sysf $_bd_read/remaining_percent)
+                rp=$(read_sysf "$_bd_read/remaining_percent")
                 ;;
 
         esac
 
-        if [ $rp -gt 0 ]; then
+        if [ "$rp" -gt 0 ]; then
             # battery not emptied --> determine cause
             get_sys_power_supply
             # shellcheck disable=SC2154
-            if [ $_syspwr -eq 1 ]; then
+            if [ "$_syspwr" -eq 1 ]; then
                 # system on battery --> AC power removed
                 echo_debug "bat" "batdrv.${_batdrv_plugin}.discharge.ac_removed($_bat_str)"
                 printf "Warning: battery %s was not discharged completely -- AC/charger removed.\n" "$_bat_str" 1>&2
@@ -770,7 +768,7 @@ batdrv_show_battery_data () {
     local ensum=0
 
     for bat in $_batteries; do # iterate detected batteries
-        batdrv_select_battery $bat
+        batdrv_select_battery "$bat"
 
         case $_bat_idx in
             1) printf "+++ ThinkPad Battery Status: %s (Main / Internal)\n" "$bat" ;;
@@ -781,21 +779,21 @@ batdrv_show_battery_data () {
         # --- show basic data
         case $_bm_read in
             natacpi) # use ACPI data
-                printparm "%-59s = ##%s##" $_bd_read/manufacturer
-                printparm "%-59s = ##%s##" $_bd_read/model_name
+                printparm "%-59s = ##%s##" "$_bd_read/manufacturer"
+                printparm "%-59s = ##%s##" "$_bd_read/model_name"
 
-                print_battery_cycle_count "$_bd_read/cycle_count" "$(read_sysf $_bd_read/cycle_count)"
+                print_battery_cycle_count "$_bd_read/cycle_count" "$(read_sysf "$_bd_read/cycle_count")"
 
-                if [ -f $_bd_read/energy_full ]; then
-                    printparm "%-59s = ##%6d## [mWh]" $_bd_read/energy_full_design "" 000
-                    printparm "%-59s = ##%6d## [mWh]" $_bd_read/energy_full "" 000
-                    printparm "%-59s = ##%6d## [mWh]" $_bd_read/energy_now "" 000
-                    printparm "%-59s = ##%6d## [mW]"  $_bd_read/power_now "" 000
+                if [ -f "$_bd_read/energy_full" ]; then
+                    printparm "%-59s = ##%6d## [mWh]" "$_bd_read/energy_full_design" "" 000
+                    printparm "%-59s = ##%6d## [mWh]" "$_bd_read/energy_full" "" 000
+                    printparm "%-59s = ##%6d## [mWh]" "$_bd_read/energy_now" "" 000
+                    printparm "%-59s = ##%6d## [mW]"  "$_bd_read/power_now" "" 000
 
                     # store values for charge / capacity calculation below
-                    ed=$(read_sysval $_bd_read/energy_full_design)
-                    ef=$(read_sysval $_bd_read/energy_full)
-                    en=$(read_sysval $_bd_read/energy_now)
+                    ed=$(read_sysval "$_bd_read/energy_full_design")
+                    ef=$(read_sysval "$_bd_read/energy_full")
+                    en=$(read_sysval "$_bd_read/energy_now")
                     efsum=$((efsum + ef))
                     ensum=$((ensum + en))
                 else
@@ -804,52 +802,52 @@ batdrv_show_battery_data () {
                     en=0
                 fi
 
-                print_batstate $_bd_read/status
+                print_batstate "$_bd_read/status"
                 printf "\n"
 
-                if [ $verbose -eq 1 ]; then
-                    printparm "%-59s = ##%6s## [mV]" $_bd_read/voltage_min_design "" 000
-                    printparm "%-59s = ##%6s## [mV]" $_bd_read/voltage_now "" 000
+                if [ "$verbose" -eq 1 ]; then
+                    printparm "%-59s = ##%6s## [mV]" "$_bd_read/voltage_min_design" "" 000
+                    printparm "%-59s = ##%6s## [mV]" "$_bd_read/voltage_now" "" 000
                     printf "\n"
                 fi
                 ;; # natacpi
 
             tpsmapi) # ThinkPad with active tp-smapi
-                printparm "%-59s = ##%s##" $_bd_read/manufacturer
-                printparm "%-59s = ##%s##" $_bd_read/model
-                printparm "%-59s = ##%s##" $_bd_read/manufacture_date
-                printparm "%-59s = ##%s##" $_bd_read/first_use_date
-                printparm "%-59s = ##%6d##" $_bd_read/cycle_count
+                printparm "%-59s = ##%s##" "$_bd_read/manufacturer"
+                printparm "%-59s = ##%s##" "$_bd_read/model"
+                printparm "%-59s = ##%s##" "$_bd_read/manufacture_date"
+                printparm "%-59s = ##%s##" "$_bd_read/first_use_date"
+                printparm "%-59s = ##%6d##" "$_bd_read/cycle_count"
 
-                if [ -f $_bd_read/temperature ]; then
+                if [ -f "$_bd_read/temperature" ]; then
                     # shellcheck disable=SC2046
-                    perl -e 'printf ("%-59s = %6d [°C]\n", "'$_bd_read/temperature'", '$(read_sysval $_bd_read/temperature)' / 1000.0);'
+                    perl -e 'printf ("%-59s = %6d [°C]\n", "'"$_bd_read/temperature"'", '$(read_sysval "$_bd_read/temperature")' / 1000.0);'
                 fi
 
-                printparm "%-59s = ##%6d## [mWh]" $_bd_read/design_capacity
-                printparm "%-59s = ##%6d## [mWh]" $_bd_read/last_full_capacity
-                printparm "%-59s = ##%6d## [mWh]" $_bd_read/remaining_capacity
-                printparm "%-59s = ##%6d## [%%]" $_bd_read/remaining_percent
-                printparm "%-59s = ##%6s## [min]" $_bd_read/remaining_running_time_now
-                printparm "%-59s = ##%6s## [min]" $_bd_read/remaining_charging_time
-                printparm "%-59s = ##%6d## [mW]" $_bd_read/power_now
-                printparm "%-59s = ##%6d## [mW]" $_bd_read/power_avg
-                print_batstate $_bd_read/state
+                printparm "%-59s = ##%6d## [mWh]" "$_bd_read/design_capacity"
+                printparm "%-59s = ##%6d## [mWh]" "$_bd_read/last_full_capacity"
+                printparm "%-59s = ##%6d## [mWh]" "$_bd_read/remaining_capacity"
+                printparm "%-59s = ##%6d## [%%]" "$_bd_read/remaining_percent"
+                printparm "%-59s = ##%6s## [min]" "$_bd_read/remaining_running_time_now"
+                printparm "%-59s = ##%6s## [min]" "$_bd_read/remaining_charging_time"
+                printparm "%-59s = ##%6d## [mW]" "$_bd_read/power_now"
+                printparm "%-59s = ##%6d## [mW]" "$_bd_read/power_avg"
+                print_batstate "$_bd_read/state"
                 printf "\n"
-                if [ $verbose -eq 1 ]; then
-                    printparm "%-59s = ##%6s## [mV]" $_bd_read/design_voltage
-                    printparm "%-59s = ##%6s## [mV]" $_bd_read/voltage
-                    printparm "%-59s = ##%6s## [mV]" $_bd_read/group0_voltage
-                    printparm "%-59s = ##%6s## [mV]" $_bd_read/group1_voltage
-                    printparm "%-59s = ##%6s## [mV]" $_bd_read/group2_voltage
-                    printparm "%-59s = ##%6s## [mV]" $_bd_read/group3_voltage
+                if [ "$verbose" -eq 1 ]; then
+                    printparm "%-59s = ##%6s## [mV]" "$_bd_read/design_voltage"
+                    printparm "%-59s = ##%6s## [mV]" "$_bd_read/voltage"
+                    printparm "%-59s = ##%6s## [mV]" "$_bd_read/group0_voltage"
+                    printparm "%-59s = ##%6s## [mV]" "$_bd_read/group1_voltage"
+                    printparm "%-59s = ##%6s## [mV]" "$_bd_read/group2_voltage"
+                    printparm "%-59s = ##%6s## [mV]" "$_bd_read/group3_voltage"
                     printf "\n"
                 fi
 
                 # store values for charge / capacity calculation below
-                ed=$(read_sysval $_bd_read/design_capacity)
-                ef=$(read_sysval $_bd_read/last_full_capacity)
-                en=$(read_sysval $_bd_read/remaining_capacity)
+                ed=$(read_sysval "$_bd_read/design_capacity")
+                ef=$(read_sysval "$_bd_read/last_full_capacity")
+                en=$(read_sysval "$_bd_read/remaining_capacity")
                 efsum=$((efsum + ef))
                 ensum=$((ensum + en))
                 ;; # tp-smapi
@@ -871,12 +869,12 @@ batdrv_show_battery_data () {
 
         # --- show charge level (SOC) and capacity
         lf=0
-        if [ $ef -ne 0 ]; then
-            perl -e 'printf ("%-59s = %6.1f [%%]\n", "Charge",   100.0 * '$en' / '$ef');'
+        if [ "$ef" -ne 0 ]; then
+            perl -e 'printf ("%-59s = %6.1f [%%]\n", "Charge",   100.0 * '"$en"' / '"$ef"');'
             lf=1
         fi
-        if [ $ed -ne 0 ]; then
-            perl -e 'printf ("%-59s = %6.1f [%%]\n", "Capacity", 100.0 * '$ef' / '$ed');'
+        if [ "$ed" -ne 0 ]; then
+            perl -e 'printf ("%-59s = %6.1f [%%]\n", "Capacity", 100.0 * '"$ef"' / '"$ed"');'
             lf=1
         fi
         [ $lf -gt 0 ] && printf "\n"
