THE BIG bat.d rework
* Move determination of battery config suffix to batdrv_select_battery()
* Rename set_charge_thresholds() to init_batteries_thresholds() for
  comprehensibility
* Improve function header docs
* Unify debug output
* Minor code fixes

diff --git a/bat.d/10-thinkpad-legacy b/bat.d/10-thinkpad-legacy
--- a/bat.d/10-thinkpad-legacy
+++ b/bat.d/10-thinkpad-legacy
@@ -75,9 +75,7 @@ batdrv_init () {
     _bn_stop="stop_charge_thresh"
     _bn_dischg="force_discharge"
     _batteries=""
-    # shellcheck disable=SC2034
     _bt_def_start=96
-    # shellcheck disable=SC2034
     _bt_def_stop=100
 
     local bs bd done=0
@@ -171,7 +169,7 @@ batdrv_init () {
 batdrv_select_battery () {
     # determine battery sysfiles and bat index
     # $1: BAT0/BAT1/DEF
-    # global param: $_bm_read
+    # global params: $_batdrv_plugin, $_batteries, $_bm_thresh, $_bm_dischg
     # rc: 0=bat exists/1=bat non-existent
     # retval: $_bat_str:   BAT0/BAT1;
     #         $_bat_idx:   1/2;
@@ -189,16 +187,21 @@ batdrv_select_battery () {
     _bf_stop=""
     _bf_dischg=""
 
+    local bat="$1"
+
+    # convert battery param to uppercase
+    bat="$(printf '%s' "$bat" | tr "[:lower:]" "[:upper:]")"
+
     # validate battery param
     local bs
-    case $1 in
+    case "$bat" in
         DEF) # 1st battery is default
             bs="${_batteries%% *}"
             ;;
 
         *)
-            if wordinlist "$1" "$_batteries"; then
-                bs=$1
+            if wordinlist "$bat" "$_batteries"; then
+                bs="$bat"
             else
                 # battery not present --> quit
                 echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1).not_present"
@@ -213,6 +216,9 @@ batdrv_select_battery () {
         BAT0) _bat_idx=1 ;;
         BAT1) _bat_idx=2 ;;
     esac
+
+    # config suffix equals battery name
+    _bt_cfg_bat="$_bat_str"
 
     # determine tp-smapi sysfiles
     if [ "$_bm_thresh" = "tpsmapi" ]; then
@@ -229,7 +235,7 @@ batdrv_select_battery () {
         tpsmapi) _bd_read="$SMAPIBATDIR/$bs" ;;
     esac
 
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; bat_idx=$_bat_idx; bd_read=$_bd_read; bf_start=$_bf_start; bf_stop=$_bf_stop; bf_dischg=$_bf_dischg"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; cfg=$_bt_cfg_bat; bat_idx=$_bat_idx; bd_read=$_bd_read; bf_start=$_bf_start; bf_stop=$_bf_stop; bf_dischg=$_bf_dischg"
     return 0
 }
 
@@ -237,7 +243,7 @@ batdrv_read_threshold () {
     # read and print charge threshold
     # $1: start/stop
     # $2: 0=api/1=tlp-stat output
-    # global param: $_bm_thresh, $_bf_start, $_bf_stop
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bf_start, $_bf_stop
     # out:
     # - api: 0..100/"" on error
     # - tlp-stat: 0..100/"(not available)" on error
@@ -299,8 +305,8 @@ batdrv_write_thresholds () {
     # $1: new start threshold 0(disabled)..99/DEF(default)
     # $2: new stop threshold 1..100/DEF(default)
     # $3: 0=quiet/1=output parameter errors/2=output progress and errors
-    # $4: battery - non-empty string indicates thresholds stem from configuration
-    # global param: $_bm_thresh, $_bat_str, $_bf_start, $_bf_stop
+    # $4: non-empty string indicates thresholds stem from configuration
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bat_str, $_bt_cfg_bat, $_bf_start, $_bf_stop
     # rc: 0=ok/
     #     1=not configured/
     #     2=threshold(s) out of range or non-numeric/
@@ -311,7 +317,6 @@ batdrv_write_thresholds () {
     local new_start=${1:-}
     local new_stop=${2:-}
     local verb=${3:-0}
-    local cfg_bat="$4"
     local old_start old_stop
 
     # insert defaults
@@ -321,9 +326,9 @@ batdrv_write_thresholds () {
     # --- validate thresholds
     local rc
 
-    if [ -n "$cfg_bat" ] && [ -z "$new_start" ] && [ -z "$new_stop" ]; then
+    if [ -n "$4" ] && [ -z "$new_start" ] && [ -z "$new_stop" ]; then
         # do nothing if unconfigured
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).not_configured: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).not_configured: bat=$_bat_str; cfg=$_bt_cfg_bat"
         return 1
     fi
 
@@ -331,17 +336,17 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_start" 3 || \
        ! is_within_bounds "$new_start" 2 96; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_start: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_start: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration at START_CHARGE_THRESH_${cfg_bat}=\"${new_start}\": not specified, invalid or out of range (2..96). Battery skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration at START_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_start}\": not specified, invalid or out of range (2..96). Battery skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (2..96). Aborted.\n" "$cfg_bat" "$new_start" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (2..96). Aborted.\n" "$_bt_cfg_bat" "$new_start" 1>&2
                 else
                     printf "Error: start charge threshold (%s) for %s is not specified, invalid or out of range (2..96). Aborted.\n" "$new_start" "$_bat_str" 1>&2
                 fi
@@ -354,17 +359,17 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_stop" 3 || \
        ! is_within_bounds "$new_stop" 6 100; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (6..100). Battery skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (6..100). Battery skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (6..100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (6..100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
                     printf "Error: stop charge threshold (%s) for %s is not specified, invalid or out of range (6..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
                 fi
@@ -375,17 +380,17 @@ batdrv_write_thresholds () {
 
     # check minimum start - stop difference
     if [ $((new_start + 4)) -gt "$new_stop" ]; then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_diff: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_diff: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration: START_CHARGE_THRESH_${cfg_bat} > STOP_CHARGE_THRESH_${cfg_bat} - 4. Battery skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration: START_CHARGE_THRESH_${_bt_cfg_bat} > STOP_CHARGE_THRESH_${_bt_cfg_bat} - 4. Battery skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration: START_CHARGE_THRESH_%s > STOP_CHARGE_THRESH_%s - 4. Aborted.\n" "$cfg_bat" "$cfg_bat" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration: START_CHARGE_THRESH_%s > STOP_CHARGE_THRESH_%s - 4. Aborted.\n" "$_bt_cfg_bat" "$_bt_cfg_bat" 1>&2
                 else
                     printf "Error: start threshold > stop threshold - 4 for %s. Aborted.\n" "$_bat_str" 1>&2
                 fi
@@ -397,7 +402,7 @@ batdrv_write_thresholds () {
     # read active threshold values
     if ! old_start=$(batdrv_read_threshold start 0) || \
        ! old_stop=$(batdrv_read_threshold stop 0); then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1) echo_message "Error: could not read current charge threshold(s) for $_bat_str. Battery skipped." ;;
             2) printf "Error: could not read current charge threshold(s) for %s. Aborted.\n" "$_bat_str" 1>&2 ;;
@@ -443,7 +448,7 @@ batdrv_write_thresholds () {
                 stop)  write_sysf "$new_thresh" "$_bf_stop"  ;;
             esac
             steprc=$?; [ $steprc -ne 0 ] && [ $rc -eq 0 ] && rc=5
-            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.write: bat=$_bat_str; old=$old_thresh; new=$new_thresh; steprc=$steprc"
+            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.write: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_thresh; new=$new_thresh; steprc=$steprc"
             case $verb in
                 2)
                     if [ $steprc -eq 0 ]; then
@@ -459,7 +464,7 @@ batdrv_write_thresholds () {
                     ;;
             esac
         else
-            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.no_change: bat=$_bat_str; old=$old_thresh; new=$new_thresh"
+            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.no_change: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_thresh; new=$new_thresh"
 
             if [ "$verb" = "2" ]; then
                 printf "  %-5s = %3d (no change)\n" "$step" "$new_thresh"
@@ -467,14 +472,14 @@ batdrv_write_thresholds () {
         fi
     done # for step
 
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).complete: bat=$_bat_str; rc=$rc"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).complete: bat=$_bat_str; cfg=$_bt_cfg_bat; rc=$rc"
     return $rc
 }
 
 batdrv_chargeonce () {
     # charge battery to stop threshold once
     # use pre-determined method and sysfiles from global parms
-    # global param: $_bm_thresh, $_bat_str, $_bf_start, $_bf_stop
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bat_str, $_bf_start, $_bf_stop
     # rc: 0=ok/
     #     2=charge level read error
     #     3=charge level too high/
@@ -536,24 +541,28 @@ batdrv_chargeonce () {
 }
 
 batdrv_apply_configured_thresholds () {
-    # apply configured thresholds from configuration to all batteries
-    # output parameter errors only
+     # apply configured stop thresholds from configuration to all batteries
+     # - called for bg tasks tlp init [re]start/auto and tlp start
+     # output parameter errors only
+     # prerequisite: batdrv_init()
 
-    if batdrv_select_battery BAT0; then
-        batdrv_write_thresholds "$START_CHARGE_THRESH_BAT0" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
-    fi
-    if batdrv_select_battery BAT1; then
-        # write configured thresholds, output parameter errors
-        batdrv_write_thresholds "$START_CHARGE_THRESH_BAT1" "$STOP_CHARGE_THRESH_BAT1" 1 "BAT1"; rc=$?
-    fi
+     local bat start_thresh stop_thresh
 
-    return 0
+     for bat in BAT0 BAT1; do
+         if batdrv_select_battery "$bat"; then
+             eval start_thresh="\$START_CHARGE_THRESH_${_bt_cfg_bat}"
+             eval stop_thresh="\$STOP_CHARGE_THRESH_${_bt_cfg_bat}"
+             batdrv_write_thresholds "$start_thresh" "$stop_thresh" 1 1
+         fi
+     done
+
+     return 0
 }
 
 batdrv_read_force_discharge () {
     # read and print force discharge state
     # $1: 0=api/1=tlp-stat output
-    # global param: $_bm_dischg, $_bf_dischg
+    # global params: $_batdrv_plugin, $_bm_dischg, $_bat_str, $_bf_dischg, $_bat_idx
     # - api: 0=off/1=on/"" on error
     # - tlp-stat: 0=off/1=on/"(not available)" on error
     # rc: 0=ok/4=read error/255=no api
@@ -593,7 +602,7 @@ batdrv_read_force_discharge () {
 batdrv_write_force_discharge () {
     # write force discharge state
     # $1: 0=off/1=on/255=no api
-    # global param: $_bat_str, $_bat_idx, $_bm_dischg, $_bf_dischg
+    # global params: $_batdrv_plugin, $_bat_str, $_bat_idx, $_bm_dischg, $_bf_dischg
     # rc: 0=done/5=write error
     # prerequisite: batdrv_init(), batdrv_select_battery()
 
@@ -616,7 +625,7 @@ batdrv_write_force_discharge () {
 
 batdrv_cancel_force_discharge () {
     # trap: called from batdrv_discharge
-    # global param: $_bat_str
+    # global params: $_batdrv_plugin, $_bat_str
     # prerequisite: batdrv_discharge()
 
     batdrv_write_force_discharge 0
@@ -628,7 +637,7 @@ batdrv_cancel_force_discharge () {
 }
 
 batdrv_force_discharge_active () { # check if battery is in 'force_discharge' state
-    # global param: $_bat_str, $_bm_read, $_bd_read
+    # global params: $_batdrv_plugin, $_bat_str, $_bm_read, $_bd_read
     # rc: 0=discharging/1=not discharging or read error
     # prerequisite: batdrv_init(), batdrv_select_battery()
 
@@ -650,7 +659,7 @@ batdrv_force_discharge_active () { # check if battery is in 'force_discharge' st
 
 batdrv_discharge () {
     # discharge battery
-    # global param: $_bm_dischg, $_bat_idx, $_bf_dischg
+    # global params: $_batdrv_plugin, $_bm_dischg, $_bat_str, $_bd_read, $_bf_dischg
     # rc: 0=done/1=malfunction/2=not emptied/3=ac removed/255=no api
     # prerequisite: batdrv_init(), batdrv_select_battery()
 
@@ -749,7 +758,7 @@ batdrv_discharge () {
 batdrv_show_battery_data () {
     # output battery data
     # $1: 1=verbose
-    # global param: $_batteries
+    # global params: $_batdrv_plugin, $_batteries, $_batdrv_kmod, $_tpsmapi, $_bm_thresh, $_bd_read, $_bf_start, $_bf_stop, $_bf_dischg
     # prerequisite: batdrv_init()
     local verbose=${1:-0}
 
@@ -907,7 +916,7 @@ batdrv_show_battery_data () {
 
     if [ $bcnt -gt 1 ] && [ $efsum -ne 0 ]; then
         # more than one battery detected --> show charge total
-        perl -e 'printf ("%-59s = %6.1f [%%]\n", "+++ Charge total",   100.0 * '$ensum' / '$efsum');'
+        perl -e 'printf ("%-59s = %6.1f [%%]\n", "+++ Charge total",   100.0 * '"$ensum"' / '"$efsum"');'
         printf "\n"
     fi
 
diff --git a/bat.d/15-asus b/bat.d/15-asus
--- a/bat.d/15-asus
+++ b/bat.d/15-asus
@@ -21,7 +21,7 @@ batdrv_is_asus () {
 batdrv_init () {
     # detect hardware and initialize driver
     # rc: 0=matching hardware detected/1=not detected/2=no batteries detected
-    # retval: $_batdrv_plugin, $batdrv_kmod
+    # retval: $_batdrv_plugin, $_batdrv_kmod
     #
     # 1. check for native kernel acpi (Linux 5.4 or higher required)
     #    --> retval $_natacpi:
@@ -69,10 +69,8 @@ batdrv_init () {
 
     # presume no features at all
     _natacpi=128
-    # shellcheck disable=SC2034
     _bm_read="natacpi"
     _bm_thresh="none"
-    # shellcheck disable=SC2034
     _bm_dischg="none"
     _bn_stop=""
     _batteries=""
@@ -129,27 +127,34 @@ batdrv_init () {
 batdrv_select_battery () {
     # determine battery acpidir and sysfile
     # $1: BAT0/BATC/BATT/BAT1/DEF
+    # global params: $_batdrv_plugin, $_batteries, $_bn_stop
     # rc: 0=bat exists/1=bat non-existent
-    # retval: $_bat_str:   BAT0/BAT1/BATT;
-    #         $_bd_read:   directory with battery data sysfiles;
-    #         $_bf_stop:   sysfile for stop threshold;
+    # retval: $_bat_str:    BAT0/BATC/BATT/BAT1;
+    #         $_bt_cfg_bat: config suffix (BAT0/BAT1);
+    #         $_bd_read:    directory with battery data sysfiles;
+    #         $_bf_stop:    sysfile for stop threshold;
     # prerequisite: batdrv_init()
 
     # defaults
-    _bat_str=""   # no bat
-    _bd_read=""   # no directory
+    _bat_str=""    # no bat
+    _bt_cfg_bat=""
+    _bd_read=""    # no directory
     _bf_stop=""
 
+    local bat="$1"
+
+    # convert battery param to uppercase
+    bat="$(printf '%s' "$bat" | tr "[:lower:]" "[:upper:]")"
+
     # validate battery param
-    local bs
-    case $1 in
+    case "$bat" in
         DEF) # 1st battery is default
             _bat_str="${_batteries%% *}"
             ;;
 
         *)
-            if wordinlist "$1" "$_batteries"; then
-                _bat_str=$1
+            if wordinlist "$bat" "$_batteries"; then
+                _bat_str="$bat"
             else
                 # battery not present --> quit
                 echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1).not_present"
@@ -158,20 +163,26 @@ batdrv_select_battery () {
             ;;
     esac
 
+    case "$_bat_str" in
+        BAT0|BATC|BATT) _bt_cfg_bat="BAT0" ;;
+        BAT1)           _bt_cfg_bat="BAT1" ;;
+        *)              _bt_cfg_bat="BAT0" ;;
+    esac
+
     # determine natacpi sysfile
     _bd_read="$ACPIBATDIR/$_bat_str"
     if [ "$_bm_thresh" = "natacpi" ]; then
         _bf_stop="$ACPIBATDIR/$_bat_str/$_bn_stop"
     fi
 
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; bd_read=$_bd_read; bf_stop=$_bf_stop"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; cfg=$_bt_cfg_bat; bd_read=$_bd_read; bf_stop=$_bf_stop"
     return 0
 }
 
 batdrv_read_threshold () {
     # read and print charge threshold (stop only)
     # $1: 0=api/1=tlp-stat output
-    # global param: $_bf_stop
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bf_stop
     # out:
     # - api: 0..100/"" on error
     # - tlp-stat: 0..100/"(not available)" on error
@@ -183,7 +194,7 @@ batdrv_read_threshold () {
     out="$X_THRESH_SIMULATE_STOP"
     if [ -n "$out" ]; then
         printf "%s" "$out"
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.read_threshold($1).simulate: bf_stop=$_bf_stop; out=$out; rc=$rc"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.read_threshold($1).simulate: bm_thresh=$_bm_thresh; bf_stop=$_bf_stop; out=$out; rc=$rc"
         return 0
     fi
 
@@ -215,7 +226,7 @@ batdrv_read_threshold () {
         rc=4
     fi
 
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.read_threshold($1): bf_stop=$_bf_stop; out=$out; rc=$rc"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.read_threshold($1): bm_thresh=$_bm_thresh; bf_stop=$_bf_stop; out=$out; rc=$rc"
     return $rc
 }
 
@@ -225,25 +236,25 @@ batdrv_write_thresholds () {
     # $1: new start threshold -- unused dummy for plugin api compatibility
     # $2: new stop threshold 1..100/DEF(default)
     # $3: 0=quiet/1=output parameter errors/2=output progress and errors
-    # $4: battery - non-empty string indicates thresholds stem from configuration
-    # global param: $_bat_str, $_bf_stop
+    # $4: non-empty string indicates thresholds stem from configuration
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bat_str, $_bt_cfg_bat, $_bf_stop
     # rc: 0=ok/
     #     1=not configured/
     #     2=threshold out of range or non-numeric/
     #     4=threshold read error/
     #     5=threshold write error
     # prerequisite: batdrv_init(), batdrv_select_battery()
+
     local new_stop=${2:-}
     local verb=${3:-0}
-    local cfg_bat="$4"
 
     # insert defaults
     [ "$new_stop" = "DEF" ] && new_stop=$_bt_def_stop
 
     # --- validate thresholds
-    if [ -n "$cfg_bat" ] && [ -z "$new_stop" ]; then
+    if [ -n "$4" ] && [ -z "$new_stop" ]; then
         # do nothing if unconfigured
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).not_configured: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).not_configured: bat=$_bat_str; cfg=$_bt_cfg_bat"
         return 1
     fi
 
@@ -251,17 +262,17 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_stop" 3 || \
        ! is_within_bounds "$new_stop" 1 100; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).invalid_stop: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (1..100). Battery skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (1..100). Battery skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
                     printf "Error: stop charge threshold (%s) for %s is not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
                 fi
@@ -274,14 +285,14 @@ batdrv_write_thresholds () {
     if ! wordinlist "$new_stop" "40 60 80 100"; then
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Notice: some ASUS laptops silently ignore charge thresholds other than 40, 60 or 80. Please check if STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\" works as expected."
+                if [ -n "$4" ]; then
+                    echo_message "Notice: some ASUS laptops silently ignore charge thresholds other than 40, 60 or 80. Please check if STOP_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_stop}\" works as expected."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Notice: some ASUS laptops silently ignore charge thresholds other than 40, 60 or 80. Please check if STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\" works as expected."
+                if [ -n "$4" ]; then
+                    echo_message "Notice: some ASUS laptops silently ignore charge thresholds other than 40, 60 or 80. Please check if STOP_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_stop}\" works as expected."
                 else
                     printf "Notice: some ASUS laptops silently ignore charge thresholds other than 40, 60 or 80. Please check if %s works as expected.\n" "$new_stop"
                 fi
@@ -296,7 +307,7 @@ batdrv_write_thresholds () {
 
     local rc=0
     write_sysf "$new_stop" "$_bf_stop" || rc=5
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).write: bat=$_bat_str; new=$new_stop; rc=$rc"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).write: bat=$_bat_str; cfg=$_bt_cfg_bat; new=$new_stop; rc=$rc"
     case $verb in
         2)
             if [ $rc -eq 0 ]; then
@@ -317,57 +328,69 @@ batdrv_write_thresholds () {
 
 batdrv_chargeonce () {
     # function not implemented for ASUS laptops
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.charge_once.not_implemented"
     return 255
 }
 
 batdrv_apply_configured_thresholds () {
     # apply configured stop thresholds from configuration to all batteries
+    # - called for bg tasks tlp init [re]start/auto and tlp start
     # output parameter errors only
+    # prerequisite: batdrv_init()
 
-    if batdrv_select_battery BAT0; then
-        batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
-    fi
-    # BATC, BATT use BAT0 settings
-    if batdrv_select_battery BATC; then
-        batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
-    fi
-    if batdrv_select_battery BATT; then
-        batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
-    fi
-    if batdrv_select_battery BAT1; then
-        batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT1" 1 "BAT1"; rc=$?
-    fi
+    local bat stop_thresh
+
+    for bat in BAT0 BATC BATT BAT1; do
+        if batdrv_select_battery "$bat"; then
+            eval stop_thresh="\$STOP_CHARGE_THRESH_${_bt_cfg_bat}"
+            batdrv_write_thresholds "DEF" "$stop_thresh" 1 1; rc=$?
+        fi
+    done
 
     return 0
 }
 
 batdrv_read_force_discharge () {
     # function not implemented for ASUS laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.read_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_write_force_discharge () {
     # function not implemented for ASUS laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.write_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_cancel_force_discharge () {
     # function not implemented for ASUS laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.cancel_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_force_discharge_active () {
     # function not implemented for ASUS laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.force_discharge_active.not_implemented"
     return 255
 }
 
 batdrv_discharge () {
     # function not implemented for ASUS laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
 
     # Important: release lock from caller
     unlock_tlp tlp_discharge
@@ -379,8 +402,9 @@ batdrv_discharge () {
 batdrv_show_battery_data () {
     # output battery status
     # $1: 1=verbose
-    # global param: $_batteries
+    # global params: $_batdrv_plugin, $_batteries, $_batdrv_kmod, $_bd_read, $_bf_stop
     # prerequisite: batdrv_init()
+
     local verbose=${1:-0}
 
     printf "+++ Battery Care\n"
@@ -439,7 +463,7 @@ batdrv_show_battery_data () {
             ensum=$((ensum + en))
 
         elif [ -f "$_bd_read/charge_full" ]; then
-            printparm "%-59s = ##%6d## [mAh]" "$_bd_read/charge_full"_design "" 000
+            printparm "%-59s = ##%6d## [mAh]" "$_bd_read/charge_full_design" "" 000
             printparm "%-59s = ##%6d## [mAh]" "$_bd_read/charge_full" "" 000
             printparm "%-59s = ##%6d## [mAh]" "$_bd_read/charge_now" "" 000
             printparm "%-59s = ##%6d## [mA]" "$_bd_read/current_now" "" 000
@@ -499,5 +523,6 @@ batdrv_show_battery_data () {
 
 batdrv_recommendations () {
      # no recommendations for ASUS laptops
+
     return 0
 }
diff --git a/bat.d/20-huawei b/bat.d/20-huawei
--- a/bat.d/20-huawei
+++ b/bat.d/20-huawei
@@ -43,7 +43,6 @@ batdrv_init () {
     #    list of batteries (space separated)    --> retval $_batteries;
     #
     # 4. determine charge threshold config, sysfile and defaults
-    #    START/STOP_CHARGE_THRESH_ suffix       --> retval $_bt_cfg_bat,
     #    sysfile (start and stop threshold)     --> retval $_bf_start_stop,
     #    start default                          --> retval $_bt_def_start,
     #    stop default                           --> retval $_bt_def_stop;
@@ -72,10 +71,8 @@ batdrv_init () {
 
     # presume no features at all
     _natacpi=128
-    # shellcheck disable=SC2034
     _bm_read="natacpi"
     _bm_thresh="none"
-    # shellcheck disable=SC2034
     _bm_dischg="none"
     _batteries=""
     _bt_def_start=0
@@ -123,25 +120,31 @@ batdrv_init () {
 batdrv_select_battery () {
     # determine battery acpidir
     # $1: BAT0/BAT1/DEF
-    # # rc: 0=bat exists/1=bat non-existent
-    # retval: $_bat_str:   BAT0/BAT1;
-    #         $_bd_read:   directory with battery data sysfiles;
+    # global params: $_batdrv_plugin, $_batteries
+    # rc: 0=bat exists/1=bat non-existent
+    # retval: $_bat_str:    BAT0/BAT1;
+    #         $_bt_cfg_bat: config suffix (BAT0/BAT1);
+    #         $_bd_read:    directory with battery data sysfiles;
     # prerequisite: batdrv_init()
 
     # defaults
     _bat_str=""   # no bat
     _bd_read=""   # no directory
 
+    local bat="$1"
+
+    # convert battery param to uppercase
+    bat="$(printf '%s' "$bat" | tr "[:lower:]" "[:upper:]")"
+
     # validate battery param
-    local bs
-    case $1 in
+    case "$bat" in
         DEF) # 1st battery is default
             _bat_str="${_batteries%% *}"
             ;;
 
         *)
-            if wordinlist "$1" "$_batteries"; then
-                _bat_str=$1
+            if wordinlist "$bat" "$_batteries"; then
+                _bat_str="$bat"
             else
                 # battery not present --> quit
                 echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1).not_present"
@@ -150,16 +153,19 @@ batdrv_select_battery () {
             ;;
     esac
 
+    # all batteries share the BAT0 config parameters
+    _bt_cfg_bat="BAT0"
+
     # determine natacpi sysfiles
     _bd_read="$ACPIBATDIR/$_bat_str"
 
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; bd_read=$_bd_read;"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; cfg=$_bt_cfg_bat; bd_read=$_bd_read;"
     return 0
 }
 
 batdrv_read_threshold () {
     # read and print both charge thresholds
-    # global param: $_bm_thresh, $_bf_start_stop
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bf_start_stop
     # out: both thresholds 0..100 separated with a blank/"" on error
     # rc: 0=ok/4=read error/255=no api
     # prerequisite: batdrv_init(), batdrv_select_battery()
@@ -196,8 +202,8 @@ batdrv_write_thresholds () {
     # $1: new start threshold 0(off)..100/DEF(default)
     # $2: new stop threshold 0(off)..100(off)/DEF(default)
     # $3: 0=quiet/1=output parameter errors/2=output progress and errors
-    # $4: battery - non-empty string indicates thresholds stem from configuration
-    # global param: $_bm_thresh, $_bf_start_stop
+    # $4: non-empty string indicates thresholds stem from configuration
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bt_cfg_bat, $_bf_start_stop
     # rc: 0=ok/
     #     1=not configured/
     #     2=threshold(s) out of range or non-numeric/
@@ -207,16 +213,15 @@ batdrv_write_thresholds () {
     local new_start=${1:-}
     local new_stop=${2:-}
     local verb=${3:-0}
-    local cfg_bat="$4"
 
     # insert defaults
     [ "$new_start" = "DEF" ] && new_start=$_bt_def_start
     [ "$new_stop" = "DEF" ] && new_stop=$_bt_def_stop
 
     # --- validate thresholds
-    if [ -n "$cfg_bat" ] && [ -z "$new_start" ] && [ -z "$new_stop" ]; then
+    if [ -n "$4" ] && [ -z "$new_start" ] && [ -z "$new_stop" ]; then
         # do nothing if unconfigured
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).not_configured"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).not_configured: cfg=$_bt_cfg_bat"
         return 1
     fi
 
@@ -224,17 +229,17 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_start" 3 || \
        ! is_within_bounds "$new_start" 0 99; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_start"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_start: cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration at START_CHARGE_THRESH_${cfg_bat}=\"${new_start}\": not specified, invalid or out of range (0..99). Skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration at START_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_start}\": not specified, invalid or out of range (0..99). Skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..99). Aborted.\n" "$cfg_bat" "$new_start" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..99). Aborted.\n" "$_bt_cfg_bat" "$new_start" 1>&2
                 else
                     printf "Error: start charge threshold (%s) is not specified, invalid or out of range (0..99). Aborted.\n" "$new_start" 1>&2
                 fi
@@ -247,17 +252,17 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_stop" 3 || \
        ! is_within_bounds "$new_stop" 1 100; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (1..100). Skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (1..100). Skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
                     printf "Error: stop charge threshold (%s) is not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" 1>&2
                 fi
@@ -268,17 +273,17 @@ batdrv_write_thresholds () {
 
     # check start <= stop
     if [ "$new_start" -gt "$new_stop" ]; then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_diff"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_diff: cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration: START_CHARGE_THRESH_${cfg_bat} > STOP_CHARGE_THRESH_${cfg_bat}. Skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration: START_CHARGE_THRESH_${_bt_cfg_bat} > STOP_CHARGE_THRESH_${_bt_cfg_bat}. Skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration: START_CHARGE_THRESH_%s > STOP_CHARGE_THRESH_%s. Aborted.\n" "$cfg_bat" "$cfg_bat" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration: START_CHARGE_THRESH_%s > STOP_CHARGE_THRESH_%s. Aborted.\n" "$_bt_cfg_bat" "$_bt_cfg_bat" 1>&2
                 else
                     printf "Error: start threshold > stop threshold. Aborted.\n" 1>&2
                 fi
@@ -295,7 +300,7 @@ batdrv_write_thresholds () {
     local rc=0
     local new_threshs="$new_start $new_stop"
     write_sysf "$new_threshs" "$_bf_start_stop" || rc=5
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4): new=$new_threshs; rc=$rc"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4): cfg=$_bt_cfg_bat; new=$new_threshs; rc=$rc"
     case $verb in
         2)
             if [ $rc -eq 0 ]; then
@@ -316,45 +321,70 @@ batdrv_write_thresholds () {
 
 batdrv_chargeonce () {
     # function not implemented for Huawei MateBooks
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.charge_once.not_implemented"
     return 255
 }
 
 batdrv_apply_configured_thresholds () {
     # apply configured stop thresholds from configuration to all batteries
+    # - called for bg tasks tlp init [re]start/auto and tlp start
     # output parameter errors only
+    # prerequisite: batdrv_init()
 
-    batdrv_write_thresholds "$START_CHARGE_THRESH_BAT0" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"
+    local start_thresh stop_thresh
+
+    if batdrv_select_battery "DEF"; then
+        eval start_thresh="\$START_CHARGE_THRESH_${_bt_cfg_bat}"
+        eval stop_thresh="\$STOP_CHARGE_THRESH_${_bt_cfg_bat}"
+        batdrv_write_thresholds "$start_thresh" "$stop_thresh" 1 1
+    fi
 
     return 0
 }
 
 batdrv_read_force_discharge () {
     # function not implemented for Huawei MateBooks
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.read_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_write_force_discharge () {
     # function not implemented for Huawei MateBooks
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.write_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_cancel_force_discharge () {
     # function not implemented for Huawei MateBooks
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.cancel_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_force_discharge_active () {
     # function not implemented for Huawei MateBooks
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.force_discharge_active.not_implemented"
     return 255
 }
 
 batdrv_discharge () {
     # function not implemented for Huawei MateBooks
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
 
     # Important: release lock from caller
     unlock_tlp tlp_discharge
@@ -366,7 +396,7 @@ batdrv_discharge () {
 batdrv_show_battery_data () {
     # output battery status
     # $1: 1=verbose
-    # global param: $_batteries
+    # global params: $_batdrv_plugin, $_batteries, $_batdrv_kmod, $_natacpi, $_bd_read, $_bf_start_stop
     # prerequisite: batdrv_init()
     local verbose=${1:-0}
     local threshs
@@ -485,7 +515,7 @@ batdrv_show_battery_data () {
 
     if [ $bcnt -gt 1 ] && [ $efsum -ne 0 ]; then
         # more than one battery detected --> show charge total
-        perl -e 'printf ("%-59s = %6.1f [%%]\n", "+++ Charge total",   100.0 * '$ensum' / '$efsum');'
+        perl -e 'printf ("%-59s = %6.1f [%%]\n", "+++ Charge total",   100.0 * '"$ensum"' / '"$efsum"');'
         printf "\n"
     fi
 
@@ -494,5 +524,6 @@ batdrv_show_battery_data () {
 
 batdrv_recommendations () {
      # no recommendations for Huawei MateBooks
+
     return 0
 }
diff --git a/bat.d/36-lg-legacy b/bat.d/36-lg-legacy
--- a/bat.d/36-lg-legacy
+++ b/bat.d/36-lg-legacy
@@ -35,7 +35,7 @@ batdrv_init () {
     #    list of batteries (space separated)    --> retval $_batteries;
     #
     # 4. define battery care limit config, sysfile and default
-    #    START/STOP_CHARGE_THRESH_ suffix       --> retval $_bt_cfg_bat,
+    #    config suffix                          --> retval $_bt_cfg_bat,
     #    sysfile                                --> retval $_bf_stop,
     #    default                                --> retval $_bt_def_stop;
 
@@ -63,14 +63,11 @@ batdrv_init () {
 
     # presume no features at all
     _natacpi=128
-    # shellcheck disable=SC2034
     _bm_read="natacpi"
     _bm_thresh="none"
-    # shellcheck disable=SC2034
     _bm_dischg="none"
     _batteries=""
-    # shellcheck disable=SC2034
-    _bt_cfg_bat="BAT0"
+    _bt_cfg_bat="BAT0" # all batteries share the BAT0 config parameter
     _bf_stop=""
     _bt_def_stop=100
 
@@ -122,6 +119,7 @@ batdrv_init () {
 batdrv_select_battery () {
     # determine battery acpidir
     # $1: BAT0/BAT1/CMB0/CMB1/DEF
+    # global params: $_batdrv_plugin, $_batteries
     # # rc: 0=bat exists/1=bat non-existent
     # retval: $_bat_str:   BAT0/BAT1/CMB0/CMB1;
     #         $_bd_read:   directory with battery data sysfiles;
@@ -131,16 +129,20 @@ batdrv_select_battery () {
     _bat_str=""   # no bat
     _bd_read=""   # no directory
 
+    local bat="$1"
+
+    # convert battery param to uppercase
+    bat="$(printf '%s' "$bat" | tr "[:lower:]" "[:upper:]")"
+
     # validate battery param
-    local bs
-    case $1 in
+    case "$bat" in
         DEF) # 1st battery is default
             _bat_str="${_batteries%% *}"
             ;;
 
         *)
-            if wordinlist "$1" "$_batteries"; then
-                _bat_str=$1
+            if wordinlist "$bat" "$_batteries"; then
+                _bat_str="$bat"
             else
                 # battery not present --> quit
                 echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1).not_present"
@@ -149,7 +151,7 @@ batdrv_select_battery () {
             ;;
     esac
 
-    # determine natacpi sysfiles
+    # determine battery directory
     _bd_read="$ACPIBATDIR/$_bat_str"
 
     echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; bd_read=$_bd_read;"
@@ -158,7 +160,7 @@ batdrv_select_battery () {
 
 batdrv_read_threshold () {
     # read and print charge threshold (stop only)
-    # global param: $_bf_stop
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bf_stop
     # out: threshold 80,100/"" on error
     # rc: 0=ok/4=read error/255=no api
     # prerequisite: batdrv_init(), batdrv_select_battery()
@@ -196,8 +198,8 @@ batdrv_write_thresholds () {
     # $1: new start threshold -- unused dummy for plugin api compatibility
     # $2: new stop threshold 80/100/DEF(default)
     # $3: 0=quiet/1=output parameter errors/2=output progress and errors
-    # $4: battery - non-empty string indicates thresholds stem from configuration
-    # global param: $_bat_str, $_bf_stop
+    # $4: non-empty string indicates thresholds stem from configuration
+    # global params: $_batdrv_plugin, $_bat_str, $_bt_cfg_bat, $_bf_stop
     # rc: 0=ok/
     #     1=not configured/
     #     2=threshold out of range or non-numeric/
@@ -207,7 +209,6 @@ batdrv_write_thresholds () {
     # prerequisite: batdrv_init(), batdrv_select_battery()
     local new_stop=${2:-}
     local verb=${3:-0}
-    local cfg_bat="$4"
     local old_stop
 
     # insert defaults
@@ -216,26 +217,26 @@ batdrv_write_thresholds () {
     # --- validate thresholds
     local rc
 
-    if [ -n "$cfg_bat" ] && [ -z "$new_stop" ]; then
+    if [ -n "$4" ] && [ -z "$new_stop" ]; then
         # do nothing if unconfigured
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).not_configured: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).not_configured: bat=$_bat_str; cfg=$_bt_cfg_bat"
         return 1
     fi
 
     # stop: check for 3 digits max, ensure 80 or 100
     if ! is_uint "$new_stop" 3 || ! wordinlist "$new_stop" "80 100"; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).invalid_stop"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\": care limit not specified or invalid (must be 80 or 100). Skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_stop}\": care limit not specified or invalid (must be 80 or 100). Skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": care limit not specified or invalid (must be 80 or 100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": care limit not specified or invalid (must be 80 or 100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
                     printf "Error: care limit (%s) not specified or invalid (must be 80 or 100). Aborted.\n" "$new_stop" 1>&2
                 fi
@@ -246,7 +247,7 @@ batdrv_write_thresholds () {
 
     # read active stop threshold value
     if ! old_stop=$(batdrv_read_threshold); then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).read_error"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1) echo_message "Error: could not read current care limit. Skipped." ;;
             2) printf "Error: could not read current care limit. Aborted.\n" 1>&2 ;;
@@ -271,7 +272,7 @@ batdrv_write_thresholds () {
             # write error
             rc=5
         fi
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).write: old=$old_stop; new=$new_stop; rc=$rc"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).write: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_stop; new=$new_stop; rc=$rc"
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
@@ -287,7 +288,7 @@ batdrv_write_thresholds () {
                 ;;
         esac
     else
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).no_change: old=$old_stop; new=$new_stop"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).no_change: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_stop; new=$new_stop"
         if [ "$verb" = "2" ]; then
                 printf "  care limit = %d (no change)\n" "$new_stop"
         fi
@@ -298,27 +299,43 @@ batdrv_write_thresholds () {
 
 batdrv_chargeonce () {
     # function not implemented for LG laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.charge_once.not_implemented"
     return 255
 }
 
 batdrv_apply_configured_thresholds () {
-    # apply configured battery care limit from configuration (concerns all batteries)
+    # apply configured battery life extender from configuration to all batteries
+    # - called for bg tasks tlp init [re]start/auto and tlp start
     # output parameter errors only
+    # prerequisite: batdrv_init()
 
-    batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
+    local stop_thresh
+
+    if batdrv_select_battery "DEF"; then
+        eval stop_thresh="\$STOP_CHARGE_THRESH_${_bt_cfg_bat}"
+        batdrv_write_thresholds "DEF" "$stop_thresh" 1 1
+    fi
 
     return 0
 }
 
 batdrv_read_force_discharge () {
     # function not implemented for LG laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.read_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_write_force_discharge () {
     # function not implemented for LG laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.write_force_discharge.not_implemented"
     return 255
 }
@@ -331,12 +348,17 @@ batdrv_cancel_force_discharge () {
 
 batdrv_force_discharge_active () {
     # function not implemented for LG laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.force_discharge_active.not_implemented"
     return 255
 }
 
 batdrv_discharge () {
     # function not implemented for LG laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
 
     # Important: release lock from caller
     unlock_tlp tlp_discharge
@@ -348,8 +370,9 @@ batdrv_discharge () {
 batdrv_show_battery_data () {
     # output battery status
     # $1: 1=verbose
-    # global param: $_batteries
+    # global params: $_batdrv_plugin, $_batteries, $_batdrv_kmod, $_bm_thresh, $_natacpi, $_bd_read, $_bf_stop
     # prerequisite: batdrv_init()
+
     local verbose=${1:-0}
 
     printf "+++ Battery Care\n"
@@ -469,5 +492,6 @@ batdrv_show_battery_data () {
 
 batdrv_recommendations () {
      # no recommendations for LG laptops
+
     return 0
 }
diff --git a/bat.d/40-sony b/bat.d/40-sony
--- a/bat.d/40-sony
+++ b/bat.d/40-sony
@@ -23,7 +23,7 @@ readonly BATDRV_SONY_BLE="${BATDRV_SONY_MD}/battery_care_limiter"
 batdrv_init () {
     # detect hardware and initialize driver
     # rc: 0=matching hardware detected/1=not detected/2=no batteries detected
-    # retval: $_batdrv_plugin, $batdrv_kmod
+    # retval: $_batdrv_plugin, $_batdrv_kmod
     #
     # 1. check for vendor specific kernel api
     #    --> retval $_natacpi:
@@ -42,7 +42,7 @@ batdrv_init () {
     #    list of batteries (space separated)    --> retval $_batteries;
     #
     # 4. define battery care limiter config, sysfile and default
-    #    START/STOP_CHARGE_THRESH_ suffix       --> retval $_bt_cfg_bat,
+    #    conig suffix (BAT0                     --> retval $_bt_cfg_bat,
     #    sysfile                                --> retval $_bf_stop,
     #    default                                --> retval $_bt_def_stop;
 
@@ -70,14 +70,11 @@ batdrv_init () {
 
     # presume no features at all
     _natacpi=128
-    # shellcheck disable=SC2034
     _bm_read="natacpi"
     _bm_thresh="none"
-    # shellcheck disable=SC2034
     _bm_dischg="none"
     _batteries=""
-    # shellcheck disable=SC2034
-    _bt_cfg_bat="BAT0"
+    _bt_cfg_bat="BAT0" # all batteries share the BAT0 config parameter
     _bf_stop=""
     _bt_def_stop=100
 
@@ -123,6 +120,7 @@ batdrv_init () {
 batdrv_select_battery () {
     # determine battery acpidir
     # $1: BAT0/BAT1/DEF
+    # global params: $_batdrv_plugin, $_batteries
     # # rc: 0=bat exists/1=bat non-existent
     # retval: $_bat_str:   BAT0/BAT1;
     #         $_bd_read:   directory with battery data sysfiles;
@@ -132,16 +130,20 @@ batdrv_select_battery () {
     _bat_str=""   # no bat
     _bd_read=""   # no directory
 
+    local bat="$1"
+
+    # convert battery param to uppercase
+    bat="$(printf '%s' "$bat" | tr "[:lower:]" "[:upper:]")"
+
     # validate battery param
-    local bs
-    case $1 in
+    case "$bat" in
         DEF) # 1st battery is default
             _bat_str="${_batteries%% *}"
             ;;
 
         *)
-            if wordinlist "$1" "$_batteries"; then
-                _bat_str=$1
+            if wordinlist "$bat" "$_batteries"; then
+                _bat_str="$bat"
             else
                 # battery not present --> quit
                 echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1).not_present"
@@ -150,7 +152,7 @@ batdrv_select_battery () {
             ;;
     esac
 
-    # determine natacpi sysfiles
+    # determine battery directory
     _bd_read="$ACPIBATDIR/$_bat_str"
 
     echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; bd_read=$_bd_read;"
@@ -159,7 +161,7 @@ batdrv_select_battery () {
 
 batdrv_read_threshold () {
     # read and print charge threshold (stop only)
-    # global param: $_bf_stop
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bf_stop
     # out: threshold 50/80/100/"" on error
     # rc: 0=ok/4=read error/255=no api
     # prerequisite: batdrv_init(), batdrv_select_battery()
@@ -197,8 +199,8 @@ batdrv_write_thresholds () {
     # $1: new start threshold -- unused dummy for plugin api compatibility
     # $2: new stop threshold  50/80/100/DEF(default)
     # $3: 0=quiet/1=output parameter errors/2=output progress and errors
-    # $4: battery - non-empty string indicates thresholds stem from configuration
-    # global param: $_bat_str, $_bf_stop
+    # $4: non-empty string indicates thresholds stem from configuration
+    # global params: $_batdrv_plugin, $_bat_str, $_bt_cfg_bat, $_bf_stop
     # rc: 0=ok/
     #     1=not configured/
     #     2=threshold out of range or non-numeric/
@@ -207,7 +209,6 @@ batdrv_write_thresholds () {
     # prerequisite: batdrv_init(), batdrv_select_battery()
     local new_stop=${2:-}
     local verb=${3:-0}
-    local cfg_bat="$4"
     local old_stop
     local sony_stop
 
@@ -217,9 +218,9 @@ batdrv_write_thresholds () {
     # --- validate thresholds
     local rc
 
-    if [ -n "$cfg_bat" ] && [ -z "$new_stop" ]; then
+    if [ -n "$4" ] && [ -z "$new_stop" ]; then
         # do nothing if unconfigured
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).not_configured: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).not_configured: bat=$_bat_str; cfg=$_bt_cfg_bat"
         return 1
     fi
 
@@ -227,17 +228,17 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_stop" 3 || \
        ! wordinlist "$new_stop" "50 80 100"; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).invalid_stop"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\": care limiter not specified or invalid (must be 50, 80 or 100). Skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_stop}\": care limiter not specified or invalid (must be 50, 80 or 100). Skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": care limiter not specified or invalid (must be 50, 80 or 100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": care limiter not specified or invalid (must be 50, 80 or 100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
                     printf "Error: care limiter (%s) not specified or invalid (must be 50, 80 or 100). Aborted.\n" "$new_stop" 1>&2
                 fi
@@ -254,7 +255,7 @@ batdrv_write_thresholds () {
 
     # read active stop threshold value
     if ! old_stop=$(batdrv_read_threshold); then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).read_error"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1) echo_message "Error: could not read current care limiter. Skipped." ;;
             2) printf "Error: could not read current care limiter. Aborted.\n" 1>&2 ;;
@@ -271,7 +272,7 @@ batdrv_write_thresholds () {
     if [ "$old_stop" != "$sony_stop" ]; then
         # new threshold differs from effective one --> write it
         write_sysf "$sony_stop" "$_bf_stop" || rc=5
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).write: old=$old_stop; new=$sony_stop; rc=$rc"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).write: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_stop; new=$sony_stop; rc=$rc"
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
@@ -287,7 +288,7 @@ batdrv_write_thresholds () {
                 ;;
         esac
     else
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($2, $3, $4).no_change: old=$old_stop; new=$sony_stop"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).no_change: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_stop; new=$sony_stop"
         if [ "$verb" = "2" ]; then
                 printf "  care limiter = %d (no change)\n" "$new_stop"
         fi
@@ -298,15 +299,25 @@ batdrv_write_thresholds () {
 
 batdrv_chargeonce () {
     # function not implemented for Sony laptops
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.charge_once.not_implemented"
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
+     echo_debug "bat" "batdrv.${_batdrv_plugin}.charge_once.not_implemented"
     return 255
 }
 
 batdrv_apply_configured_thresholds () {
-    # apply configured battery life extender from configuration (concerns all batteries)
+    # apply configured battery life extender from configuration to all batteries
+    # - called for bg tasks tlp init [re]start/auto and tlp start
     # output parameter errors only
+    # prerequisite: batdrv_init()
 
-    batdrv_write_thresholds "DEF" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
+    local stop_thresh
+
+    if batdrv_select_battery "DEF"; then
+        eval stop_thresh="\$STOP_CHARGE_THRESH_${_bt_cfg_bat}"
+        batdrv_write_thresholds "DEF" "$stop_thresh" 1 1
+    fi
 
     return 0
 }
@@ -319,24 +330,35 @@ batdrv_read_force_discharge () {
 
 batdrv_write_force_discharge () {
     # function not implemented for Sony laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.write_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_cancel_force_discharge () {
     # function not implemented for Sony laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.cancel_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_force_discharge_active () {
     # function not implemented for Sony laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.force_discharge_active.not_implemented"
     return 255
 }
 
 batdrv_discharge () {
     # function not implemented for Sony laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
 
     # Important: release lock from caller
     unlock_tlp tlp_discharge
@@ -348,7 +370,7 @@ batdrv_discharge () {
 batdrv_show_battery_data () {
     # output battery status
     # $1: 1=verbose
-    # global param: $_batteries
+    # global params: $_batdrv_plugin, $_batteries, $_batdrv_kmod, $_bm_thresh, $_natacpi, $_bd_read, $_bf_stop
     # prerequisite: batdrv_init()
     local verbose=${1:-0}
 
@@ -473,5 +495,6 @@ batdrv_show_battery_data () {
 
 batdrv_recommendations () {
      # no recommendations for Sony laptops
+
     return 0
 }
diff --git a/bat.d/45-system76 b/bat.d/45-system76
--- a/bat.d/45-system76
+++ b/bat.d/45-system76
@@ -72,10 +72,8 @@ batdrv_init () {
 
     # presume no features at all
     _natacpi=128
-    # shellcheck disable=SC2034
     _bm_read="natacpi"
     _bm_thresh="none"
-    # shellcheck disable=SC2034
     _bm_dischg="none"
     _bn_start=""
     _bn_stop=""
@@ -137,7 +135,7 @@ batdrv_init () {
 
     # shellcheck disable=SC2034
     _batdrv_selected=$_batdrv_plugin
-    echo_debug "bat" "batdrv_init.${_batdrv_plugin}: batteries=$_batteries; natacpi=$_natacpi; thresh=$_bm_thresh; bn_start=$_bn_start; bn_stop=$_bn_stop;"
+    echo_debug "bat" "batdrv_init.${_batdrv_plugin}: batteries=$_batteries; natacpi=$_natacpi; thresh=$_bm_thresh; bn_start=$_bn_start; bn_stop=$_bn_stop; dischg=$_bm_dischg"
     return 0
 }
 
@@ -145,10 +143,11 @@ batdrv_select_battery () {
     # determine battery acpidir and sysfiles
     # $1: BAT0/DEF
     # # rc: 0=bat exists/1=bat non-existent
-    # retval: $_bat_str:   BAT0;
-    #         $_bd_read:   directory with battery data sysfiles;
-    #         $_bf_start:  sysfile for stop threshold;
-    #         $_bf_stop:   sysfile for stop threshold;
+    # retval: $_bat_str:    BAT0
+    #         $_bt_cfg_bat: config suffix (BAT0);
+    #         $_bd_read:    directory with battery data sysfiles;
+    #         $_bf_start:   sysfile for stop threshold;
+    #         $_bf_stop:    sysfile for stop threshold;
     # prerequisite: batdrv_init()
 
     # defaults
@@ -157,16 +156,20 @@ batdrv_select_battery () {
     _bf_start=""
     _bf_stop=""
 
+    local bat="$1"
+
+    # convert battery param to uppercase
+    bat="$(printf '%s' "$1" | tr "[:lower:]" "[:upper:]")"
+
     # validate battery param
-    local bs
-    case $1 in
+    case "$bat" in
         DEF) # 1st battery is default
             _bat_str="${_batteries%% *}"
             ;;
 
         *)
-            if wordinlist "$1" "$_batteries"; then
-                _bat_str=$1
+            if wordinlist "$bat" "$_batteries"; then
+                _bat_str="$bat"
             else
                 # battery not present --> quit
                 echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1).not_present"
@@ -175,6 +178,9 @@ batdrv_select_battery () {
             ;;
     esac
 
+    # System76 EC only supports one battery
+    _bt_cfg_bat="BAT0"
+
     # determine natacpi sysfiles
     _bd_read="$ACPIBATDIR/$_bat_str"
     if [ "$_bm_thresh" = "natacpi" ]; then
@@ -182,7 +188,7 @@ batdrv_select_battery () {
         _bf_stop="$ACPIBATDIR/$_bat_str/$_bn_stop"
     fi
 
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; bd_read=$_bd_read; bf_start=$_bf_start; bf_stop=$_bf_stop"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; cfg=$_bt_cfg_bat; bd_read=$_bd_read; bf_start=$_bf_start; bf_stop=$_bf_stop"
     return 0
 }
 
@@ -190,7 +196,7 @@ batdrv_read_threshold () {
     # read and print charge threshold
     # $1: start/stop
     # $2: 0=api/1=tlp-stat output
-    # global param: $_bm_thresh, $_bf_start, $_bf_stop
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bf_start, $_bf_stop
     # out:
     # - api: 0..100/"" on error
     # - tlp-stat: 0..100/"(not available)" on error
@@ -252,8 +258,8 @@ batdrv_write_thresholds () {
     # $1: new start threshold 0(disabled)..99/DEF(default)
     # $2: new stop threshold 1..100/DEF(default)
     # $3: 0=quiet/1=output parameter errors/2=output progress and errors
-    # $4: battery - non-empty string indicates thresholds stem from configuration
-    # global param: $_bm_thresh, $_bat_str, $_bf_start, $_bf_stop
+    # $4: non-empty string indicates thresholds stem from configuration
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bat_str, $_bt_cfg_bat, $_bf_start, $_bf_stop
     # rc: 0=ok/
     #     1=not configured/
     #     2=threshold(s) out of range or non-numeric/
@@ -264,7 +270,6 @@ batdrv_write_thresholds () {
     local new_start=${1:-}
     local new_stop=${2:-}
     local verb=${3:-0}
-    local cfg_bat="$4"
     local old_start old_stop
 
     # insert defaults
@@ -274,9 +279,9 @@ batdrv_write_thresholds () {
     # --- validate thresholds
     local rc
 
-    if [ -n "$cfg_bat" ] && [ -z "$new_start" ] && [ -z "$new_stop" ]; then
+    if [ -n "$4" ] && [ -z "$new_start" ] && [ -z "$new_stop" ]; then
         # do nothing if unconfigured
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).not_configured: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).not_configured: bat=$_bat_str; cfg=$_bt_cfg_bat"
         return 1
     fi
 
@@ -284,17 +289,17 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_start" 3 || \
        ! is_within_bounds "$new_start" 0 99; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_start: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_start: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration at START_CHARGE_THRESH_${cfg_bat}=\"${new_start}\": not specified, invalid or out of range (0..99). Battery skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration at START_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_start}\": not specified, invalid or out of range (0..99). Battery skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..99). Aborted.\n" "$cfg_bat" "$new_start" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..99). Aborted.\n" "$_bt_cfg_bat" "$new_start" 1>&2
                 else
                     printf "Error: start charge threshold (%s) for %s is not specified, invalid or out of range (0..99). Aborted.\n" "$new_start" "$_bat_str" 1>&2
                 fi
@@ -307,17 +312,17 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_stop" 3 || \
        ! is_within_bounds "$new_stop" 1 100; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (1..100). Battery skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (1..100). Battery skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
                     printf "Error: stop charge threshold (%s) for %s is not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
                 fi
@@ -328,17 +333,17 @@ batdrv_write_thresholds () {
 
     # check start < stop
     if [ "$new_start" -ge "$new_stop" ]; then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_diff: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_diff: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration: START_CHARGE_THRESH_${cfg_bat} >= STOP_CHARGE_THRESH_${cfg_bat}. Battery skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration: START_CHARGE_THRESH_${_bt_cfg_bat} >= STOP_CHARGE_THRESH_${_bt_cfg_bat}. Battery skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration: START_CHARGE_THRESH_%s >= STOP_CHARGE_THRESH_%s. Aborted.\n" "$cfg_bat" "$cfg_bat" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration: START_CHARGE_THRESH_%s >= STOP_CHARGE_THRESH_%s. Aborted.\n" "$_bt_cfg_bat" "$_bt_cfg_bat" 1>&2
                 else
                     printf "Error: start threshold >= stop threshold for %s. Aborted.\n" "$_bat_str" 1>&2
                 fi
@@ -350,7 +355,7 @@ batdrv_write_thresholds () {
     # read active threshold values
     if ! old_start=$(batdrv_read_threshold start 0) || \
        ! old_stop=$(batdrv_read_threshold stop 0); then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1) echo_message "Error: could not read current charge threshold(s) for $_bat_str. Battery skipped." ;;
             2) printf "Error: could not read current charge threshold(s) for %s. Aborted.\n" "$_bat_str" 1>&2 ;;
@@ -396,7 +401,8 @@ batdrv_write_thresholds () {
                 stop)  write_sysf "$new_thresh" "$_bf_stop"  ;;
             esac
             steprc=$?; [ $steprc -ne 0 ] && rc=5
-            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.write: bat=$_bat_str; old=$old_thresh; new=$new_thresh; steprc=$steprc"
+            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.write: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_thresh; new=$new_thresh; steprc=$steprc"
+
             case $verb in
                 2)
                     if [ $steprc -eq 0 ]; then
@@ -420,7 +426,7 @@ batdrv_write_thresholds () {
         fi
     done # for step
 
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).complete: bat=$_bat_str; rc=$rc"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).complete: bat=$_bat_str; cfg=$_bt_cfg_bat; rc=$rc"
     return $rc
 }
 
@@ -432,41 +438,61 @@ batdrv_chargeonce () {
 
 batdrv_apply_configured_thresholds () {
     # apply configured stop thresholds from configuration to all batteries
+    # - called for bg tasks tlp init [re]start/auto and tlp start
     # output parameter errors only
+    # prerequisite: batdrv_init()
 
-    if batdrv_select_battery BAT0; then
-        batdrv_write_thresholds "$START_CHARGE_THRESH_BAT0" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
+    local start_thresh stop_thresh
+
+    if batdrv_select_battery "DEF"; then
+        eval start_thresh="\$START_CHARGE_THRESH_${_bt_cfg_bat}"
+        eval stop_thresh="\$STOP_CHARGE_THRESH_${_bt_cfg_bat}"
+        batdrv_write_thresholds "$start_thresh" "$stop_thresh" 1 1
     fi
 
     return 0
 }
 
 batdrv_read_force_discharge () {
-    # function not implemented
+    # function not implemented for System76 laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.read_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_write_force_discharge () {
-    # function not implemented
+    # function not implemented for System76 laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.write_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_cancel_force_discharge () {
-    # function not implemented
+    # function not implemented for System76 laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.cancel_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_force_discharge_active () {
-    # function not implemented
+    # function not implemented for System76 laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.force_discharge_active.not_implemented"
     return 255
 }
 
 batdrv_discharge () {
-    # function not implemented
+    # function not implemented for System76 laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
 
     # Important: release lock from caller
     unlock_tlp tlp_discharge
@@ -478,8 +504,9 @@ batdrv_discharge () {
 batdrv_show_battery_data () {
     # output battery status
     # $1: 1=verbose
-    # global param: $_batteries
+    # global params: $_batdrv_plugin, $_batteries, $_batdrv_kmod, $_bd_read, $_bf_start, $_bf_stop, $_bf_dischg
     # prerequisite: batdrv_init()
+
     local verbose=${1:-0}
 
     printf "+++ Battery Care\n"
@@ -593,5 +620,6 @@ batdrv_show_battery_data () {
 
 batdrv_recommendations () {
      # no recommendations
+
     return 0
 }
diff --git a/bat.d/55-msi b/bat.d/55-msi
--- a/bat.d/55-msi
+++ b/bat.d/55-msi
@@ -71,10 +71,8 @@ batdrv_init () {
 
     # presume no features at all
     _natacpi=128
-    # shellcheck disable=SC2034
     _bm_read="natacpi"
     _bm_thresh="none"
-    # shellcheck disable=SC2034
     _bm_dischg="none"
     _bn_start=""
     _bn_stop=""
@@ -134,36 +132,42 @@ batdrv_init () {
 
     # shellcheck disable=SC2034
     _batdrv_selected=$_batdrv_plugin
-    echo_debug "bat" "batdrv_init.${_batdrv_plugin}: batteries=$_batteries; natacpi=$_natacpi; thresh=$_bm_thresh; bn_start=$_bn_start; bn_stop=$_bn_stop;"
+    echo_debug "bat" "batdrv_init.${_batdrv_plugin}: batteries=$_batteries; natacpi=$_natacpi; thresh=$_bm_thresh; bn_start=$_bn_start; bn_stop=$_bn_stop; dischg=$_bm_dischg"
     return 0
 }
 
 batdrv_select_battery () {
     # determine battery acpidir and sysfiles
     # $1: BAT0/BAT1/DEF
-    # # rc: 0=bat exists/1=bat non-existent
-    # retval: $_bat_str:   BAT0/BAT1/BATT;
+    # rc: 0=bat exists/1=bat non-existent
+    # retval: $_bat_str:   BAT0/BAT1;
     #         $_bd_read:   directory with battery data sysfiles;
+    #         $_bt_cfg_bat: config suffix (BAT0/BAT1);
     #         $_bf_start:  sysfile for stop threshold;
     #         $_bf_stop:   sysfile for stop threshold;
     # prerequisite: batdrv_init()
 
     # defaults
-    _bat_str=""   # no bat
-    _bd_read=""   # no directory
+    _bat_str=""    # no bat
+    _bt_cfg_bat=""
+    _bd_read=""    # no directory
     _bf_start=""
     _bf_stop=""
 
+    local bat="$1"
+
+    # convert battery param to uppercase
+    bat="$(printf '%s' "$bat" | tr "[:lower:]" "[:upper:]")"
+
     # validate battery param
-    local bs
-    case $1 in
+    case "$bat" in
         DEF) # 1st battery is default
             _bat_str="${_batteries%% *}"
             ;;
 
         *)
-            if wordinlist "$1" "$_batteries"; then
-                _bat_str=$1
+            if wordinlist "$bat" "$_batteries"; then
+                _bat_str="$bat"
             else
                 # battery not present --> quit
                 echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1).not_present"
@@ -172,6 +176,9 @@ batdrv_select_battery () {
             ;;
     esac
 
+    # config suffix equals battery name
+    _bt_cfg_bat="$_bat_str"
+
     # determine natacpi sysfiles
     _bd_read="$ACPIBATDIR/$_bat_str"
     if [ "$_bm_thresh" = "natacpi" ]; then
@@ -179,7 +186,7 @@ batdrv_select_battery () {
         _bf_stop="$ACPIBATDIR/$_bat_str/$_bn_stop"
     fi
 
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; bd_read=$_bd_read; bf_start=$_bf_start; bf_stop=$_bf_stop"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; cfg=$_bt_cfg_bat; bd_read=$_bd_read; bf_start=$_bf_start; bf_stop=$_bf_stop"
     return 0
 }
 
@@ -187,7 +194,7 @@ batdrv_read_threshold () {
     # read and print charge threshold
     # $1: start/stop
     # $2: 0=api/1=tlp-stat output
-    # global param: $_bm_thresh, $_bf_start, $_bf_stop
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bf_start, $_bf_stop
     # out:
     # - api: 0..100/"" on error
     # - tlp-stat: 0..100/"(not available)" on error
@@ -250,8 +257,8 @@ batdrv_write_thresholds () {
     # $1: new start threshold 0..90/DEF(default)
     # $2: new stop threshold 10..100/DEF(default)
     # $3: 0=quiet/1=output parameter errors/2=output progress and errors
-    # $4: config battery - non-empty string indicates thresholds stem from configuration
-    # global param: $_bm_thresh, $_bat_str, $_bf_start, $_bf_stop
+    # $4: non-empty string indicates thresholds stem from configuration
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bat_str, $_bt_cfg_bat, $_bf_start, $_bf_stop
     # rc: 0=ok/
     #     1=not configured/
     #     2=threshold(s) out of range or non-numeric/
@@ -262,7 +269,6 @@ batdrv_write_thresholds () {
     local new_start=${1:-}
     local new_stop=${2:-}
     local verb=${3:-0}
-    local cfg_bat="$4"
     local old_stop
     local nom_start
 
@@ -273,9 +279,9 @@ batdrv_write_thresholds () {
     # --- validate thresholds
     local rc
 
-    if [ -n "$cfg_bat" ] && [ -z "$new_start" ] && [ -z "$new_stop" ]; then
+    if [ -n "$4" ] && [ -z "$new_start" ] && [ -z "$new_stop" ]; then
         # do nothing if unconfigured
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).not_configured: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).not_configured: bat=$_bat_str; cfg=$_bt_cfg_bat"
         return 1
     fi
 
@@ -283,17 +289,17 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_stop" 3 || \
        ! is_within_bounds "$new_stop" 10 100; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (10..100). Battery skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (10..100). Battery skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (10..100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (10..100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
                     printf "Error: stop charge threshold (%s) for %s is not specified, invalid or out of range (10..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
                 fi
@@ -307,13 +313,13 @@ batdrv_write_thresholds () {
 
     # start: silently ignore non-numeric or invalid threshold, substitute it with stop - 10
     if ! is_uint "$new_start" 3 || [ "$new_start" -ne "$nom_start" ]; then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_start: bat=$_bat_str; nom=$nom_start"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_start: bat=$_bat_str; cfg=$_bt_cfg_bat; nom=$nom_start"
         new_start="$nom_start"
     fi
 
     # read active stop threshold value
     if ! old_stop=$(batdrv_read_threshold stop 0); then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1) echo_message "Error: could not read current stop charge threshold for $_bat_str. Battery skipped." ;;
             2) printf "Error: could not read current stop charge threshold for %s. Aborted.\n" "$_bat_str" 1>&2 ;;
@@ -333,7 +339,7 @@ batdrv_write_thresholds () {
         write_sysf "$new_stop" "$_bf_stop"
         steprc=$?; [ $steprc -ne 0 ] && rc=5
 
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).stop.write: bat=$_bat_str; old=$old_stop; new=$new_stop; steprc=$steprc"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).stop.write: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_stop; new=$new_stop; steprc=$steprc"
         case $verb in
             2)
                 if [ $steprc -eq 0 ]; then
@@ -358,7 +364,7 @@ batdrv_write_thresholds () {
         fi
 
     else
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).stop.no_change: bat=$_bat_str; old=$old_stop; new=$new_stop"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).stop.no_change: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_stop; new=$new_stop"
 
         if [ "$verb" = "2" ]; then
             printf "  %-5s = %3d (no change)\n" "stop" "$new_stop"
@@ -366,56 +372,78 @@ batdrv_write_thresholds () {
         fi
     fi
 
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).complete: bat=$_bat_str; rc=$rc"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).complete: bat=$_bat_str; cfg=$_bt_cfg_bat; rc=$rc"
     return $rc
 }
 
 batdrv_chargeonce () {
-    # function not implemented
+    # function not implemented for MSI laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.charge_once.not_implemented"
     return 255
 }
 
 batdrv_apply_configured_thresholds () {
     # apply configured stop thresholds from configuration to all batteries
+    # - called for bg tasks tlp init [re]start/auto and tlp start
     # output parameter errors only
+    # prerequisite: batdrv_init()
 
-    if batdrv_select_battery BAT0; then
-        batdrv_write_thresholds "$START_CHARGE_THRESH_BAT0" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
-    fi
-    if batdrv_select_battery BAT1; then
-        batdrv_write_thresholds "$START_CHARGE_THRESH_BAT1" "$STOP_CHARGE_THRESH_BAT1" 1 "BAT1"; rc=$?
-    fi
+    local bat start_thresh stop_thresh
+
+    for bat in BAT0 BAT1; do
+        if batdrv_select_battery "$bat"; then
+            eval start_thresh="\$START_CHARGE_THRESH_${_bt_cfg_bat}"
+            eval stop_thresh="\$STOP_CHARGE_THRESH_${_bt_cfg_bat}"
+            batdrv_write_thresholds "$start_thresh" "$stop_thresh" 1 1
+        fi
+    done
 
     return 0
 }
 
 batdrv_read_force_discharge () {
-    # function not implemented
+    # function not implemented for MSI laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.read_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_write_force_discharge () {
-    # function not implemented
+    # function not implemented  for MSI laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.write_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_cancel_force_discharge () {
-    # function not implemented
+    # function not implemented for MSI laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.cancel_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_force_discharge_active () {
-    # function not implemented
+    # function not implemented  for MSI laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.force_discharge_active.not_implemented"
     return 255
 }
 
 batdrv_discharge () {
-    # function not implemented
+    # function not implemented for MSI laptops
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
 
     # Important: release lock from caller
     unlock_tlp tlp_discharge
@@ -427,8 +455,9 @@ batdrv_discharge () {
 batdrv_show_battery_data () {
     # output battery status
     # $1: 1=verbose
-    # global param: $_batteries
+    # global params: $_batdrv_plugin, $_batteries, $_batdrv_kmod, $_bm_thresh, $_bd_read, $_bf_start, $_bf_stop, $_bf_dischg
     # prerequisite: batdrv_init()
+
     local verbose=${1:-0}
 
     printf "+++ Battery Care\n"
@@ -548,5 +577,6 @@ batdrv_show_battery_data () {
 
 batdrv_recommendations () {
      # no recommendations
+
     return 0
 }
diff --git a/bat.d/TEMPLATE b/bat.d/TEMPLATE
--- a/bat.d/TEMPLATE
+++ b/bat.d/TEMPLATE
@@ -28,7 +28,7 @@ batdrv_init () {
     # rc: 0=matching hardware detected/1=not detected/2=no batteries detected
     # retval: $_batdrv_plugin, $_batdrv_kmod
     #
-    # 1. check for native kernel acpi (Linux 5.4 or higher required)
+    # 1. check for native kernel acpi (TEMPLATE: Linux m.n or higher required)
     #    --> retval $_natacpi:
     #       0=thresholds/
     #       32=disabled/
@@ -44,6 +44,7 @@ batdrv_init () {
     # 3. define sysfile basenames for natacpi
     #    start threshold                        --> retval $_bn_start,
     #    stop threshold                         --> retval $_bn_stop,
+    #    discharge                              --> retval $_bn_discharge
     #
     # 4. determine present batteries
     #    list of batteries (space separated)    --> retval $_batteries;
@@ -76,13 +77,12 @@ batdrv_init () {
 
     # presume no features at all
     _natacpi=128
-    # shellcheck disable=SC2034
     _bm_read="natacpi"
     _bm_thresh="none"
-    # shellcheck disable=SC2034
     _bm_dischg="none"
     _bn_start=""
     _bn_stop=""
+    _bn_dischg=""
     _batteries=""
     # TEMPLATE: customize to vendor defaults
     _bt_def_start=96
@@ -140,36 +140,44 @@ batdrv_init () {
 
     # shellcheck disable=SC2034
     _batdrv_selected=$_batdrv_plugin
-    echo_debug "bat" "batdrv_init.${_batdrv_plugin}: batteries=$_batteries; natacpi=$_natacpi; thresh=$_bm_thresh; bn_start=$_bn_start; bn_stop=$_bn_stop;"
+    echo_debug "bat" "batdrv_init.${_batdrv_plugin}: batteries=$_batteries; natacpi=$_natacpi; thresh=$_bm_thresh; bn_start=$_bn_start; bn_stop=$_bn_stop; dischg=$_bm_dischg; bn_dischg=$_bn_dischg"
     return 0
 }
 
 batdrv_select_battery () {
     # determine battery acpidir and sysfiles
     # $1: BAT0/BAT1/DEF
-    # # rc: 0=bat exists/1=bat non-existent
-    # retval: $_bat_str:   BAT0/BAT1/BATT;
-    #         $_bd_read:   directory with battery data sysfiles;
-    #         $_bf_start:  sysfile for stop threshold;
-    #         $_bf_stop:   sysfile for stop threshold;
+    # global params: $_batdrv_plugin, $_batteries, $_bn_start, $_bn_stop, $_bn_dischg
+    # rc: 0=bat exists/1=bat non-existent
+    # retval: $_bat_str:    BAT0/BAT1/<other>;
+    #         $_bt_cfg_bat: config suffix (BAT0/BAT1);
+    #         $_bd_read:    directory with battery data sysfiles;
+    #         $_bf_start:   sysfile for start threshold;
+    #         $_bf_stop:    sysfile for stop threshold;
     # prerequisite: batdrv_init()
 
     # defaults
-    _bat_str=""   # no bat
-    _bd_read=""   # no directory
+    _bat_str=""    # no bat
+    _bt_cfg_bat=""
+    _bd_read=""    # no directory
     _bf_start=""
     _bf_stop=""
 
+    local bat="$1"
+
+    # convert battery param to uppercase
+    # TEMPLATE: omit the following line for lower case battery device names
+    bat="$(printf '%s' "$bat" | tr "[:lower:]" "[:upper:]")"
+
     # validate battery param
-    local bs
-    case $1 in
+    case "$bat" in
         DEF) # 1st battery is default
             _bat_str="${_batteries%% *}"
             ;;
 
         *)
-            if wordinlist "$1" "$_batteries"; then
-                _bat_str=$1
+            if wordinlist "$bat" "$_batteries"; then
+                _bat_str="$bat"
             else
                 # battery not present --> quit
                 echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1).not_present"
@@ -178,6 +186,9 @@ batdrv_select_battery () {
             ;;
     esac
 
+    # TEMPLATE: assume config suffix matches battery name, i.e. works for BAT0/BAT1 only
+    _bt_cfg_bat="$_bat_str"
+
     # determine natacpi sysfiles
     _bd_read="$ACPIBATDIR/$_bat_str"
     if [ "$_bm_thresh" = "natacpi" ]; then
@@ -185,7 +196,7 @@ batdrv_select_battery () {
         _bf_stop="$ACPIBATDIR/$_bat_str/$_bn_stop"
     fi
 
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; bd_read=$_bd_read; bf_start=$_bf_start; bf_stop=$_bf_stop"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.select_battery($1): bat_str=$_bat_str; cfg=$_bt_cfg_bat; bd_read=$_bd_read; bf_start=$_bf_start; bf_stop=$_bf_stop"
     return 0
 }
 
@@ -193,7 +204,7 @@ batdrv_read_threshold () {
     # read and print charge threshold
     # $1: start/stop
     # $2: 0=api/1=tlp-stat output
-    # global param: $_bm_thresh, $_bf_start, $_bf_stop
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bf_start, $_bf_stop
     # out:
     # - api: 0..100/"" on error
     # - tlp-stat: 0..100/"(not available)" on error
@@ -255,8 +266,8 @@ batdrv_write_thresholds () {
     # $1: new start threshold 0(disabled)..100/DEF(default)
     # $2: new stop threshold 0..100/DEF(default)
     # $3: 0=quiet/1=output parameter errors/2=output progress and errors
-    # $4: config battery - non-empty string indicates thresholds stem from configuration
-    # global param: $_bm_thresh, $_bat_str, $_bf_start, $_bf_stop
+    # $4: non-empty string indicates thresholds stem from configuration
+    # global params: $_batdrv_plugin, $_bm_thresh, $_bat_str, $_bt_cfg_bat, $_bf_start, $_bf_stop
     # rc: 0=ok/
     #     1=not configured/
     #     2=threshold(s) out of range or non-numeric/
@@ -267,7 +278,6 @@ batdrv_write_thresholds () {
     local new_start=${1:-}
     local new_stop=${2:-}
     local verb=${3:-0}
-    local cfg_bat="$4"
     local old_start old_stop
 
     # insert defaults
@@ -277,9 +287,9 @@ batdrv_write_thresholds () {
     # --- validate thresholds
     local rc
 
-    if [ -n "$cfg_bat" ] && [ -z "$new_start" ] && [ -z "$new_stop" ]; then
+    if [ -n "$4" ] && [ -z "$new_start" ] && [ -z "$new_stop" ]; then
         # do nothing if unconfigured
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).not_configured: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).not_configured: bat=$_bat_str; cfg=$_bt_cfg_bat"
         return 1
     fi
 
@@ -288,17 +298,17 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_start" 3 || \
        ! is_within_bounds "$new_start" 0 100; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_start: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_start: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration at START_CHARGE_THRESH_${cfg_bat}=\"${new_start}\": not specified, invalid or out of range (0..100). Battery skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration at START_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_start}\": not specified, invalid or out of range (0..100). Battery skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..100). Aborted.\n" "$cfg_bat" "$new_start" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..100). Aborted.\n" "$_bt_cfg_bat}" "$new_start" 1>&2
                 else
                     printf "Error: start charge threshold (%s) for %s is not specified, invalid or out of range (0..100). Aborted.\n" "$new_start" "$_bat_str" 1>&2
                 fi
@@ -312,17 +322,17 @@ batdrv_write_thresholds () {
     if ! is_uint "$new_stop" 3 || \
        ! is_within_bounds "$new_stop" 0 100; then
         # threshold out of range
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_stop: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (0..100). Battery skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (0..100). Battery skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..100). Aborted.\n" "$cfg_bat" "$new_stop" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
                     printf "Error: stop charge threshold (%s) for %s is not specified, invalid or out of range (0..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
                 fi
@@ -334,17 +344,17 @@ batdrv_write_thresholds () {
     # TEMPLATE: customize assertion to vendor specs
     # check start < stop
     if [ "$new_start" -ge "$new_stop" ]; then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_diff: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).invalid_diff: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1)
-                if [ -n "$cfg_bat" ]; then
-                    echo_message "Error in configuration: START_CHARGE_THRESH_${cfg_bat} >= STOP_CHARGE_THRESH_${cfg_bat}. Battery skipped."
+                if [ -n "$4" ]; then
+                    echo_message "Error in configuration: START_CHARGE_THRESH_${_bt_cfg_bat} >= STOP_CHARGE_THRESH_$_bt_cfg_bat. Battery skipped."
                 fi
                 ;;
 
             2)
-                if [ -n "$cfg_bat" ]; then
-                    printf "Error in configuration: START_CHARGE_THRESH_%s >= STOP_CHARGE_THRESH_%s. Aborted.\n" "$cfg_bat" "$cfg_bat" 1>&2
+                if [ -n "$4" ]; then
+                    printf "Error in configuration: START_CHARGE_THRESH_%s >= STOP_CHARGE_THRESH_%s. Aborted.\n" "$_bt_cfg_bat" "$_bt_cfg_bat" 1>&2
                 else
                     printf "Error: start threshold >= stop threshold for %s. Aborted.\n" "$_bat_str" 1>&2
                 fi
@@ -356,7 +366,7 @@ batdrv_write_thresholds () {
     # read active threshold values
     if ! old_start=$(batdrv_read_threshold start 0) || \
        ! old_stop=$(batdrv_read_threshold stop 0); then
-        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str"
+        echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1) echo_message "Error: could not read current charge threshold(s) for $_bat_str. Battery skipped." ;;
             2) printf "Error: could not read current charge threshold(s) for %s. Aborted.\n" "$_bat_str" 1>&2 ;;
@@ -403,7 +413,7 @@ batdrv_write_thresholds () {
                 stop)  write_sysf "$new_thresh" "$_bf_stop"  ;;
             esac
             steprc=$?; [ $steprc -ne 0 ] && rc=5
-            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.write: bat=$_bat_str; old=$old_thresh; new=$new_thresh; steprc=$steprc"
+            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.write: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_thresh; new=$new_thresh; steprc=$steprc"
 
             case $verb in
                 2)
@@ -420,7 +430,7 @@ batdrv_write_thresholds () {
                     ;;
             esac
         else
-            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.no_change: bat=$_bat_str; old=$old_thresh; new=$new_thresh"
+            echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.no_change: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_thresh; new=$new_thresh"
 
             if [ "$verb" = "2" ]; then
                 printf "  %-5s = %3d (no change)\n" "$step" "$new_thresh"
@@ -428,56 +438,78 @@ batdrv_write_thresholds () {
         fi
     done # for step
 
-    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).complete: bat=$_bat_str; rc=$rc"
+    echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).complete: bat=$_bat_str; cfg=$_bt_cfg_bat; rc=$rc"
     return $rc
 }
 
 batdrv_chargeonce () {
     # function not implemented
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.charge_once.not_implemented"
     return 255
 }
 
 batdrv_apply_configured_thresholds () {
     # apply configured stop thresholds from configuration to all batteries
+    # - called for bg tasks tlp init [re]start/auto and tlp start
     # output parameter errors only
+    # prerequisite: batdrv_init()
 
-    if batdrv_select_battery BAT0; then
-        batdrv_write_thresholds "$START_CHARGE_THRESH_BAT0" "$STOP_CHARGE_THRESH_BAT0" 1 "BAT0"; rc=$?
-    fi
-    if batdrv_select_battery BAT1; then
-        batdrv_write_thresholds "$START_CHARGE_THRESH_BAT1" "$STOP_CHARGE_THRESH_BAT1" 1 "BAT1"; rc=$?
-    fi
+    local bat start_thresh stop_thresh
+
+    for bat in BAT0 BAT1; do
+        if batdrv_select_battery "$bat"; then
+            eval start_thresh="\$STOP_CHARGE_THRESH_${_bt_cfg_bat}"
+            eval stop_thresh="\$STOP_CHARGE_THRESH_${_bt_cfg_bat}"
+            batdrv_write_thresholds "$start_thresh" "$stop_thresh" 1 1
+        fi
+    done
 
     return 0
 }
 
 batdrv_read_force_discharge () {
     # function not implemented
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.read_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_write_force_discharge () {
     # function not implemented
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.write_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_cancel_force_discharge () {
     # function not implemented
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.cancel_force_discharge.not_implemented"
     return 255
 }
 
 batdrv_force_discharge_active () {
     # function not implemented
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
+
     echo_debug "bat" "batdrv.${_batdrv_plugin}.force_discharge_active.not_implemented"
     return 255
 }
 
 batdrv_discharge () {
     # function not implemented
+    # global param: $_batdrv_plugin
+    # prerequisite: batdrv_init()
 
     # Important: release lock from caller
     unlock_tlp tlp_discharge
@@ -489,8 +521,9 @@ batdrv_discharge () {
 batdrv_show_battery_data () {
     # output battery status
     # $1: 1=verbose
-    # global param: $_batteries
+    # global params: $_batdrv_plugin, $_batteries, $_batdrv_kmod, $_bd_read, $_bf_start, $_bf_stop, $_bf_dischg
     # prerequisite: batdrv_init()
+
     local verbose=${1:-0}
 
     printf "+++ Battery Care\n"
@@ -611,5 +644,6 @@ batdrv_show_battery_data () {
 
 batdrv_recommendations () {
      # no recommendations
+
     return 0
 }
