bat.d/!thinkpad: colorize messages and tlp-stat -b output

diff --git a/bat.d/20-huawei b/bat.d/20-huawei
--- a/bat.d/20-huawei
+++ b/bat.d/20-huawei
@@ -239,9 +239,9 @@ batdrv_write_thresholds () {
 
             2)
                 if [ -n "$4" ]; then
-                    printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..99). Aborted.\n" "$_bt_cfg_bat" "$new_start" 1>&2
+                    cprintf "" "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..99). Aborted.\n" "$_bt_cfg_bat" "$new_start" 1>&2
                 else
-                    printf "Error: start charge threshold (%s) is not specified, invalid or out of range (0..99). Aborted.\n" "$new_start" 1>&2
+                    cprintf "" "Error: start charge threshold (%s) is not specified, invalid or out of range (0..99). Aborted.\n" "$new_start" 1>&2
                 fi
                 ;;
         esac
@@ -262,9 +262,9 @@ batdrv_write_thresholds () {
 
             2)
                 if [ -n "$4" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
+                    cprintf "" "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
-                    printf "Error: stop charge threshold (%s) is not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" 1>&2
+                    cprintf "" "Error: stop charge threshold (%s) is not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" 1>&2
                 fi
                 ;;
         esac
@@ -283,9 +283,9 @@ batdrv_write_thresholds () {
 
             2)
                 if [ -n "$4" ]; then
-                    printf "Error in configuration: START_CHARGE_THRESH_%s > STOP_CHARGE_THRESH_%s. Aborted.\n" "$_bt_cfg_bat" "$_bt_cfg_bat" 1>&2
+                    cprintf "" "Error in configuration: START_CHARGE_THRESH_%s > STOP_CHARGE_THRESH_%s. Aborted.\n" "$_bt_cfg_bat" "$_bt_cfg_bat" 1>&2
                 else
-                    printf "Error: start threshold > stop threshold. Aborted.\n" 1>&2
+                    cprintf "" "Error: start threshold > stop threshold. Aborted.\n" 1>&2
                 fi
                 ;;
         esac
@@ -294,7 +294,7 @@ batdrv_write_thresholds () {
 
     # write new thresholds
     if [ "$verb" = "2" ]; then
-        printf "Setting temporary charge thresholds:\n"
+        printf "Setting temporary charge thresholds:\n" 1>&2
     fi
 
     local rc=0
@@ -304,9 +304,9 @@ batdrv_write_thresholds () {
     case $verb in
         2)
             if [ $rc -eq 0 ]; then
-                printf "  %s = %d, %s = %d\n" start "$new_start" stop "$new_stop"
+                printf "  %s = %d, %s = %d\n" start "$new_start" stop "$new_stop" 1>&2
             else
-                printf "  %s = %d, %s = %d (Error: write failed)\n" start "$new_start" stop "$new_stop" 1>&2
+                cprintf "err" "  %s = %d, %s = %d (Error: write failed)\n" start "$new_start" stop "$new_stop" 1>&2
             fi
             ;;
         1)
@@ -405,19 +405,19 @@ batdrv_show_battery_data () {
     printf "Plugin: %s\n" "$_batdrv_plugin"
 
     if [ "$_bm_thresh" = "natacpi" ]; then
-        printf "Supported features: charge thresholds\n"
+        cprintf "success" "Supported features: charge thresholds\n"
     else
-        printf "Supported features: none available\n"
+        cprintf "warning" "Supported features: none available\n"
     fi
 
     printf "Driver usage:\n"
     # native kernel ACPI battery API
     case $_natacpi in
-        0)   printf "* vendor (%s) = active (charge thresholds)\n" "$_batdrv_kmod" ;;
-        32)  printf "* vendor (%s) = inactive (disabled by configuration)\n" "$_batdrv_kmod" ;;
-        128) printf "* vendor (%s) = inactive (no kernel support)\n" "$_batdrv_kmod" ;;
-        254) printf "* vendor (%s) = inactive (laptop not supported)\n" "$_batdrv_kmod" ;;
-        *)   printf "* vendor (%s) = unknown status\n" "$_batdrv_kmod" ;;
+        0)   cprintf "success" "* vendor (%s) = active (charge thresholds)\n" "$_batdrv_kmod" ;;
+        32)  cprintf "notice"  "* vendor (%s) = inactive (disabled by configuration)\n" "$_batdrv_kmod" ;;
+        128) cprintf "err"     "* vendor (%s) = inactive (no kernel support)\n" "$_batdrv_kmod" ;;
+        254) cprintf "warning" "* vendor (%s) = inactive (laptop not supported)\n" "$_batdrv_kmod" ;;
+        *)   cprintf "err"     "* vendor (%s) = unknown status\n" "$_batdrv_kmod" ;;
     esac
 
     if [ "$_bm_thresh" = "natacpi" ]; then
diff --git a/bat.d/35-lg b/bat.d/35-lg
--- a/bat.d/35-lg
+++ b/bat.d/35-lg
@@ -267,9 +267,9 @@ batdrv_write_thresholds () {
 
             2)
                 if [ -n "$4" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified or invalid (must be 80 or 100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
+                    cprintf "" "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified or invalid (must be 80 or 100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
-                    printf "Error: stop charge threshold (%s) not specified or invalid (must be 80 or 100). Aborted.\n" "$new_stop" 1>&2
+                    cprintf "" "Error: stop charge threshold (%s) not specified or invalid (must be 80 or 100). Aborted.\n" "$new_stop" 1>&2
                 fi
                 ;;
         esac
@@ -281,14 +281,14 @@ batdrv_write_thresholds () {
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1) echo_message "Error: could not read current stop charge threshold. Skipped." ;;
-            2) printf "Error: could not read current stop charge threshold. Aborted.\n" 1>&2 ;;
+            2) cprintf "" "Error: could not read current stop charge threshold. Aborted.\n" 1>&2 ;;
         esac
         return 4
     fi
 
     # write new threshold
     if [ "$verb" = "2" ]; then
-        printf "Setting temporary charge threshold for %s:\n" "$_bat_str"
+        printf "Setting temporary charge threshold for %s:\n" "$_bat_str" 1>&2
     fi
 
     local rc=0
@@ -307,9 +307,9 @@ batdrv_write_thresholds () {
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
-                    printf "  stop = %d\n" "$new_stop"
+                    printf "  stop = %d\n" "$new_stop" 1>&2
                 else
-                    printf "  stop = %d (Error: write failed)\n" "$new_stop" 1>&2
+                    cprintf "err" "  stop = %d (Error: write failed)\n" "$new_stop" 1>&2
                 fi
                 ;;
             1)
@@ -321,7 +321,7 @@ batdrv_write_thresholds () {
     else
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).no_change: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_stop; new=$new_stop"
         if [ "$verb" = "2" ]; then
-                printf "  stop = %d (no change)\n" "$new_stop"
+                printf "  stop = %d (no change)\n" "$new_stop" 1>&2
         fi
     fi
 
@@ -415,19 +415,19 @@ batdrv_show_battery_data () {
     printf "Plugin: %s\n" "$_batdrv_plugin"
 
     if [ "$_bm_thresh" = "natacpi" ]; then
-        printf "Supported features: charge threshold\n"
+        cprintf "success" "Supported features: charge threshold\n"
     else
-        printf "Supported features: none available\n"
+        cprintf "warning" "Supported features: none available\n"
     fi
 
     printf "Driver usage:\n"
     # vendor specific kernel api
     case $_natacpi in
-        0)   printf "* natacpi (%s) = active (charge threshold)\n" "$_batdrv_kmod" ;;
-        32)  printf "* natacpi (%s) = inactive (disabled by configuration)\n" "$_batdrv_kmod" ;;
-        128) printf "* natacpi (%s) = inactive (no kernel support)\n" "$_batdrv_kmod" ;;
-        254) printf "* natacpi (%s) = inactive (laptop not supported)\n" "$_batdrv_kmod" ;;
-        *)   printf "* natacpi (%s) = unknown status\n" "$_batdrv_kmod" ;;
+        0)   cprintf "success" "* natacpi (%s) = active (charge threshold)\n" "$_batdrv_kmod" ;;
+        32)  cprintf "notice"  "* natacpi (%s) = inactive (disabled by configuration)\n" "$_batdrv_kmod" ;;
+        128) cprintf "err"     "* natacpi (%s) = inactive (no kernel support)\n" "$_batdrv_kmod" ;;
+        254) cprintf "warning" "* natacpi (%s) = inactive (laptop not supported)\n" "$_batdrv_kmod" ;;
+        *)   cprintf "err"     "* natacpi (%s) = unknown status\n" "$_batdrv_kmod" ;;
     esac
 
     if [ "$_bm_thresh" = "natacpi" ]; then
diff --git a/bat.d/40-sony b/bat.d/40-sony
--- a/bat.d/40-sony
+++ b/bat.d/40-sony
@@ -238,9 +238,9 @@ batdrv_write_thresholds () {
 
             2)
                 if [ -n "$4" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": care limiter not specified or invalid (must be 50, 80 or 100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
+                    cprintf "" "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": care limiter not specified or invalid (must be 50, 80 or 100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
-                    printf "Error: care limiter (%s) not specified or invalid (must be 50, 80 or 100). Aborted.\n" "$new_stop" 1>&2
+                    pcrintf "" "Error: care limiter (%s) not specified or invalid (must be 50, 80 or 100). Aborted.\n" "$new_stop" 1>&2
                 fi
                 ;;
         esac
@@ -258,14 +258,14 @@ batdrv_write_thresholds () {
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1) echo_message "Error: could not read current care limiter. Skipped." ;;
-            2) printf "Error: could not read current care limiter. Aborted.\n" 1>&2 ;;
+            2) cprintf "" "Error: could not read current care limiter. Aborted.\n" 1>&2 ;;
         esac
         return 4
     fi
 
     # write new threshold
     if [ "$verb" = "2" ]; then
-        printf "Setting temporary charge threshold for all batteries:\n"
+        printf "Setting temporary charge threshold for all batteries:\n" 1>&2
     fi
 
     local rc=0
@@ -276,9 +276,9 @@ batdrv_write_thresholds () {
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
-                    printf "  care limiter = %d\n" "$new_stop"
+                    printf "  care limiter = %d\n" "$new_stop" 1>&2
                 else
-                    printf "  care limiter = %d (Error: write failed)\n" "$new_stop" 1>&2
+                    cprintf "err" "  care limiter = %d (Error: write failed)\n" "$new_stop" 1>&2
                 fi
                 ;;
             1)
@@ -290,7 +290,7 @@ batdrv_write_thresholds () {
     else
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).no_change: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_stop; new=$sony_stop"
         if [ "$verb" = "2" ]; then
-                printf "  care limiter = %d (no change)\n" "$new_stop"
+                printf "  care limiter = %d (no change)\n" "$new_stop" 1>&2
         fi
     fi
 
@@ -378,19 +378,19 @@ batdrv_show_battery_data () {
     printf "Plugin: %s\n" "$_batdrv_plugin"
 
     if [ "$_bm_thresh" = "natacpi" ]; then
-        printf "Supported features: charge threshold\n"
+        cprintf "success" "Supported features: charge threshold\n"
     else
-        printf "Supported features: none available\n"
+        cprintf "warning" "Supported features: none available\n"
     fi
 
     printf "Driver usage:\n"
     # vendor specific kernel api
     case $_natacpi in
-        0)   printf "* vendor (%s) = active (charge threshold)\n" "$_batdrv_kmod" ;;
-        32)  printf "* vendor (%s) = inactive (disabled by configuration)\n" "$_batdrv_kmod" ;;
-        128) printf "* vendor (%s) = inactive (no kernel support)\n" "$_batdrv_kmod" ;;
-        254) printf "* vendor (%s) = inactive (laptop not supported)\n" "$_batdrv_kmod" ;;
-        *)   printf "* vendor (%s) = unknown status\n" "$_batdrv_kmod" ;;
+        0)   cprintf "success" "* vendor (%s) = active (charge threshold)\n" "$_batdrv_kmod" ;;
+        32)  cprintf "notice"  "* vendor (%s) = inactive (disabled by configuration)\n" "$_batdrv_kmod" ;;
+        128) cprintf "err"     "* vendor (%s) = inactive (no kernel support)\n" "$_batdrv_kmod" ;;
+        254) cprintf "warning" "* vendor (%s) = inactive (laptop not supported)\n" "$_batdrv_kmod" ;;
+        *)   cprintf "err"     "* vendor (%s) = unknown status\n" "$_batdrv_kmod" ;;
     esac
 
     if [ "$_bm_thresh" = "natacpi" ]; then
diff --git a/bat.d/45-system76 b/bat.d/45-system76
--- a/bat.d/45-system76
+++ b/bat.d/45-system76
@@ -299,9 +299,9 @@ batdrv_write_thresholds () {
 
             2)
                 if [ -n "$4" ]; then
-                    printf "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..99). Aborted.\n" "$_bt_cfg_bat" "$new_start" 1>&2
+                    cprintf "" "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (0..99). Aborted.\n" "$_bt_cfg_bat" "$new_start" 1>&2
                 else
-                    printf "Error: start charge threshold (%s) for %s is not specified, invalid or out of range (0..99). Aborted.\n" "$new_start" "$_bat_str" 1>&2
+                    cprintf "" "Error: start charge threshold (%s) for %s is not specified, invalid or out of range (0..99). Aborted.\n" "$new_start" "$_bat_str" 1>&2
                 fi
                 ;;
         esac
@@ -322,9 +322,9 @@ batdrv_write_thresholds () {
 
             2)
                 if [ -n "$4" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
+                    cprintf "" "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (1..100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
-                    printf "Error: stop charge threshold (%s) for %s is not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
+                    cprintf "" "Error: stop charge threshold (%s) for %s is not specified, invalid or out of range (1..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
                 fi
                 ;;
         esac
@@ -343,9 +343,9 @@ batdrv_write_thresholds () {
 
             2)
                 if [ -n "$4" ]; then
-                    printf "Error in configuration: START_CHARGE_THRESH_%s >= STOP_CHARGE_THRESH_%s. Aborted.\n" "$_bt_cfg_bat" "$_bt_cfg_bat" 1>&2
+                    cprintf "" "Error in configuration: START_CHARGE_THRESH_%s >= STOP_CHARGE_THRESH_%s. Aborted.\n" "$_bt_cfg_bat" "$_bt_cfg_bat" 1>&2
                 else
-                    printf "Error: start threshold >= stop threshold for %s. Aborted.\n" "$_bat_str" 1>&2
+                    cprintf "" "Error: start threshold >= stop threshold for %s. Aborted.\n" "$_bat_str" 1>&2
                 fi
                 ;;
         esac
@@ -358,7 +358,7 @@ batdrv_write_thresholds () {
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1) echo_message "Error: could not read current charge threshold(s) for $_bat_str. Battery skipped." ;;
-            2) printf "Error: could not read current charge threshold(s) for %s. Aborted.\n" "$_bat_str" 1>&2 ;;
+            2) cprintf "" "Error: could not read current charge threshold(s) for %s. Aborted.\n" "$_bat_str" 1>&2 ;;
         esac
         return 4
     fi
@@ -376,7 +376,7 @@ batdrv_write_thresholds () {
 
     # write new thresholds in determined sequence
     if [ "$verb" = "2" ]; then
-        printf "Setting temporary charge thresholds for %s:\n" "$_bat_str"
+        printf "Setting temporary charge thresholds for %s:\n" "$_bat_str" 1>&2
     fi
 
     for step in $tseq; do
@@ -406,9 +406,9 @@ batdrv_write_thresholds () {
             case $verb in
                 2)
                     if [ $steprc -eq 0 ]; then
-                        printf "  %-5s = %3d\n" "$step" "$new_thresh"
+                        printf "  %-5s = %3d\n" "$step" "$new_thresh" 1>&2
                     else
-                        printf "  %-5s = %3d (Error: write failed)\n" "$step" "$new_thresh" 1>&2
+                        cprintf "err" "  %-5s = %3d (Error: write failed)\n" "$step" "$new_thresh" 1>&2
                     fi
                     ;;
                 1)
@@ -421,7 +421,7 @@ batdrv_write_thresholds () {
             echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).$step.no_change: bat=$_bat_str; old=$old_thresh; new=$new_thresh"
 
             if [ "$verb" = "2" ]; then
-                printf "  %-5s = %3d (no change)\n" "$step" "$new_thresh"
+                printf "  %-5s = %3d (no change)\n" "$step" "$new_thresh" 1>&2
             fi
         fi
     done # for step
@@ -513,21 +513,21 @@ batdrv_show_battery_data () {
     printf "Plugin: %s\n" "$_batdrv_plugin"
 
     if [ "$_bm_thresh" != "none" ]; then
-        printf "Supported features: charge thresholds\n"
+        cprintf "success" "Supported features: charge thresholds\n"
     else
-        printf "Supported features: none available\n"
+        cprintf "warning" "Supported features: none available\n"
     fi
 
     printf "Driver usage:\n"
     # native kernel ACPI battery API
     case $_natacpi in
-        0)   printf "* natacpi (%s) = active (charge thresholds)\n" "$_batdrv_kmod" ;;
-        32)  printf "* natacpi (%s) = inactive (disabled by configuration)\n" "$_batdrv_kmod" ;;
-        128) printf "* natacpi (%s) = inactive (no kernel support)\n" "$_batdrv_kmod" ;;
-        254) printf "* natacpi (%s) = inactive (laptop not supported)\n" "$_batdrv_kmod" ;;
-        *)   printf "* natacpi (%s) = unknown status\n" "$_batdrv_kmod" ;;
+        0)   cprintf "success" "* natacpi (%s) = active (charge thresholds)\n" "$_batdrv_kmod" ;;
+        32)  cprintf "notice"  "* natacpi (%s) = inactive (disabled by configuration)\n" "$_batdrv_kmod" ;;
+        128) cprintf "err"     "* natacpi (%s) = inactive (no kernel support)\n" "$_batdrv_kmod" ;;
+        254) cprintf "warning" "* natacpi (%s) = inactive (laptop not supported)\n" "$_batdrv_kmod" ;;
+        *)   cprintf "err"     "* natacpi (%s) = unknown status\n" "$_batdrv_kmod" ;;
     esac
-    if [ "$_bm_thresh" != "none" ]; then
+    if [ "$_bm_thresh" = "natacpi" ]; then
         printf "Parameter value ranges:\n"
         printf "* START_CHARGE_THRESH_BAT0:  0(off)..90(default)..99\n"
         printf "* STOP_CHARGE_THRESH_BAT0:   1..100(default)\n"
diff --git a/bat.d/50-toshiba b/bat.d/50-toshiba
--- a/bat.d/50-toshiba
+++ b/bat.d/50-toshiba
@@ -269,9 +269,9 @@ batdrv_write_thresholds () {
 
             2)
                 if [ -n "$4" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified or invalid (must be 80 or 100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
+                    cprintf "" "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified or invalid (must be 80 or 100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
-                    printf "Error: stop charge threshold (%s) for %s is not specified or invalid (must be 80 or 100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
+                    cprintf "" "Error: stop charge threshold (%s) for %s is not specified or invalid (must be 80 or 100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
                 fi
                 ;;
         esac
@@ -283,14 +283,14 @@ batdrv_write_thresholds () {
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1) echo_message "Error: could not read current stop charge threshold for $_bat_str. Battery skipped." ;;
-            2) printf "Error: could not read current stop charge threshold for %s. Aborted.\n" "$_bat_str" 1>&2 ;;
+            2) cprintf "" "Error: could not read current stop charge threshold for %s. Aborted.\n" "$_bat_str" 1>&2 ;;
         esac
         return 4
     fi
 
     # write new threshold
     if [ "$verb" = "2" ]; then
-        printf "Setting temporary charge threshold for %s:\n" "$_bat_str"
+        printf "Setting temporary charge threshold for %s:\n" "$_bat_str" 1>&2
     fi
 
     local rc=0
@@ -301,9 +301,9 @@ batdrv_write_thresholds () {
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
-                    printf "  stop = %3d\n" "$new_stop"
+                    printf "  stop = %3d\n" "$new_stop" 1>&2
                 else
-                    printf "  stop = %3d (Error: write failed)\n" "$new_stop" 1>&2
+                    cprintf "err" "  stop = %3d (Error: write failed)\n" "$new_stop" 1>&2
                 fi
                 ;;
             1)
@@ -408,19 +408,19 @@ batdrv_show_battery_data () {
     printf "Plugin: %s\n" "$_batdrv_plugin"
 
     if [ "$_bm_thresh" = "natacpi" ]; then
-        printf "Supported features: charge threshold\n"
+        cprintf "success" "Supported features: charge threshold\n"
     else
-        printf "Supported features: none available\n"
+        cprintf "warning" "Supported features: none available\n"
     fi
 
     printf "Driver usage:\n"
     # native kernel ACPI battery API
     case $_natacpi in
-        0)   printf "* natacpi (%s) = active (charge threshold)\n" "$_batdrv_kmod" ;;
-        32)  printf "* natacpi (%s) = inactive (disabled by configuration)\n" "$_batdrv_kmod" ;;
-        128) printf "* natacpi (%s) = inactive (no kernel support)\n" "$_batdrv_kmod" ;;
-        254) printf "* natacpi (%s) = inactive (laptop not supported)\n" "$_batdrv_kmod" ;;
-        *)   printf "* natacpi (%s) = unknown status\n" "$_batdrv_kmod" ;;
+        0)   cprintf "success" "* natacpi (%s) = active (charge threshold)\n" "$_batdrv_kmod" ;;
+        32)  cprintf "notice"  "* natacpi (%s) = inactive (disabled by configuration)\n" "$_batdrv_kmod" ;;
+        128) cprintf "err"     "* natacpi (%s) = inactive (no kernel support)\n" "$_batdrv_kmod" ;;
+        254) cprintf "warning" "* natacpi (%s) = inactive (laptop not supported)\n" "$_batdrv_kmod" ;;
+        *)   cprintf "err"     "* natacpi (%s) = unknown status\n" "$_batdrv_kmod" ;;
     esac
 
     if [ "$_bm_thresh" = "natacpi" ]; then
diff --git a/bat.d/60-macbook b/bat.d/60-macbook
--- a/bat.d/60-macbook
+++ b/bat.d/60-macbook
@@ -323,9 +323,9 @@ batdrv_write_thresholds () {
 
             2)
                 if [ -n "$4" ]; then
-                    printf "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified or invalid (must be 80 or 100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
+                    cprintf "" "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified or invalid (must be 80 or 100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
-                    printf "Error: stop charge threshold (%s) for %s is not specified or invalid (must be 80 or 100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
+                    cprintf "" "Error: stop charge threshold (%s) for %s is not specified or invalid (must be 80 or 100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
                 fi
                 ;;
          esac
@@ -343,14 +343,14 @@ batdrv_write_thresholds () {
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
             1) echo_message "Error: could not read current stop charge threshold for $_bat_str. Battery skipped." ;;
-            2) printf "Error: could not read current stop charge threshold for %s. Aborted.\n" "$_bat_str" 1>&2 ;;
+            2) cprintf "" "Error: could not read current stop charge threshold for %s. Aborted.\n" "$_bat_str" 1>&2 ;;
         esac
         return 4
     fi
 
     # write new stop threshold
     if [ "$verb" = "2" ]; then
-        printf "Setting temporary charge thresholds for %s:\n" "$_bat_str"
+        printf "Setting temporary charge thresholds for %s:\n" "$_bat_str" 1>&2
     fi
 
     local rc=0
@@ -362,10 +362,10 @@ batdrv_write_thresholds () {
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
-                    printf "  stop  = %3d\n" "$new_stop"
-                    printf "  start = %3d (due to hardware constraint)\n" "$new_start"
+                    printf "  stop  = %3d\n" "$new_stop" 1>&2
+                    printf "  start = %3d (due to hardware constraint)\n" "$new_start" 1>&2
                 else
-                    printf "  stop  = %3d (Error: write failed)\n" "$new_stop" 1>&2
+                    cprintf "err" "  stop  = %3d (Error: write failed)\n" "$new_stop" 1>&2
                 fi
                 ;;
             1)
@@ -378,8 +378,8 @@ batdrv_write_thresholds () {
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).stop.no_change: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_stop; new=$new_stop"
 
         if [ "$verb" = "2" ]; then
-            printf "  stop  = %3d (no change)\n" "$new_stop"
-            printf "  start = %3d (no change)\n" "$new_start"
+            printf "  stop  = %3d (no change)\n" "$new_stop" 1>&2
+            printf "  start = %3d (no change)\n" "$new_start" 1>&2
         fi
     fi
 
@@ -514,9 +514,9 @@ batdrv_show_battery_data () {
     printf "Plugin: %s\n" "$_batdrv_plugin"
 
     if [ "$_bm_thresh" != "none" ]; then
-        printf "Supported features: charge thresholds\n"
+        cprintf "success" "Supported features: charge thresholds\n"
     else
-        printf "Supported features: none available\n"
+        cprintf "warning" "Supported features: none available\n"
     fi
 
     printf "Driver usage:\n"
