TLP_WARN_LEVEL: warn about invalid user settings
Configurable for:
* Background tasks --> syslog
* Command line --> stderr

diff --git a/bat.d/20-huawei b/bat.d/20-huawei
--- a/bat.d/20-huawei
+++ b/bat.d/20-huawei
@@ -251,7 +251,7 @@ batdrv_write_thresholds () {
         # threshold out of range
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3).invalid_start: bat=$_bat_str"
         case $verb in
-            1) printf "Warning: charge start threshold (%s) for %s not specified, invalid or out of range (0..100). Battery skipped.\n" "$new_start" $_bat_str 1>&2 ;;
+            1) echo_message "Warning: charge start threshold ($new_start) for $_bat_str not specified, invalid or out of range (0..100). Battery skipped." ;;
             2) printf "Error: charge start threshold (%s) for %s not specified, invalid or out of range (0..100). Aborted.\n" "$new_start" $_bat_str 1>&2 ;;
         esac
         return 2
@@ -263,7 +263,7 @@ batdrv_write_thresholds () {
         # threshold out of range
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3).invalid_stop: bat=$_bat_str"
         case $verb in
-            1) printf "Warning: charge stop threshold (%s) for %s not specified, invalid or out of range (0..100). Battery skipped.\n" "$new_stop" $_bat_str 1>&2 ;;
+            1) echo_message "Warning: charge stop threshold ($new_stop) for $_bat_str not specified, invalid or out of range (0..100). Battery skipped." ;;
             2) printf "Error: charge stop threshold (%s) for %s not specified, invalid or out of range (0..100). Aborted.\n" "$new_stop" $_bat_str 1>&2 ;;
         esac
         return 2
@@ -273,7 +273,7 @@ batdrv_write_thresholds () {
     if [ $new_start -ge $new_stop ]; then
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3).invalid_diff: bat=$_bat_str"
         case $verb in
-            1) printf "Warning: charge start threshold > stop threshold for %s. Battery skipped.\n" $_bat_str 1>&2 ;;
+            1) echo_message "Warning: charge start threshold > stop threshold for $_bat_str. Battery skipped." ;;
             2) printf "Error: start threshold > stop threshold for %s. Aborted.\n" $_bat_str 1>&2 ;;
         esac
         return 3
@@ -284,8 +284,8 @@ batdrv_write_thresholds () {
        ! old_stop=$(batdrv_read_threshold stop); then
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3).read_error: bat=$_bat_str"
         case $verb in
-            1) printf "Warning: could not read current charge thresholds for %s. Battery skipped.\n" $_bat_str 1>&2 ;;
-            2) printf "Error: could not read current charge thresholds for %s. Aborted.\n" $_bat_str 1>&2 ;;
+            1) echo_message "Warning: could not read current charge threshold(s) for $_bat_str. Battery skipped." ;;
+            2) printf "Error: could not read current charge threshold(s) for %s. Aborted.\n" $_bat_str 1>&2 ;;
         esac
         return 4
     fi
@@ -349,7 +349,7 @@ batdrv_write_thresholds () {
                     ;;
                 1)
                     if [ $steprc -gt 0 ]; then
-                        printf "Warning: writing charge %s threshold for %s failed. Battery skipped.\n" $step $_bat_str 1>&2
+                        echo_message "Warning: writing charge $step threshold for $_bat_str failed."
                     fi
                     ;;
             esac
