bat.d/!thinkpad: recommend discharging if SOC above stop threshold

diff --git a/bat.d/35-lg b/bat.d/35-lg
--- a/bat.d/35-lg
+++ b/bat.d/35-lg
@@ -307,9 +307,9 @@ batdrv_write_thresholds () {
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
-                    printf "  stop = %d\n" "$new_stop" 1>&2
+                    printf        "  %-5s = %3d\n" "stop" "$new_stop" 1>&2
                 else
-                    cprintf "err" "  stop = %d (Error: write failed)\n" "$new_stop" 1>&2
+                    cprintf "err" "  %-5s = %3d (Error: write failed)\n" "stop" "$new_stop" 1>&2
                 fi
                 ;;
             1)
@@ -321,8 +321,12 @@ batdrv_write_thresholds () {
     else
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).no_change: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_stop; new=$new_stop"
         if [ "$verb" = "2" ]; then
-                printf "  stop = %d (no change)\n" "$new_stop" 1>&2
+            printf "  %-5s = %3d (no change)\n" "stop" "$new_stop" 1>&2
         fi
+    fi
+
+    if [ "$rc" -eq 0 ] && [ "$verb" = "2" ]; then
+        soc_gt_stop_notice
     fi
 
     return $rc
@@ -524,8 +528,29 @@ batdrv_show_battery_data () {
     return 0
 }
 
-batdrv_recommendations () {
-     # no recommendations for LG laptops
+batdrv_check_soc_gt_stop () {
+    # check if battery charge level (SOC) is greater than the stop threshold
+    # rc: 0=greater/1=less or equal (or thresholds not supported)
+    # global params: $_bm_thresh, $_bat_str
+    # prerequisite: batdrv_init(), batdrv_select_battery()
 
-    return 0
-}
+    local soc stop
+
+    if [ "$_bm_thresh" = "natacpi" ] && soc=$(read_sysval "$ACPIBATDIR/$_bat_str/capacity"); then
+        stop="$(batdrv_read_threshold)"
+        if [ -n "$stop" ] && [ "$soc" -gt "$stop" ]; then
+            return 0
+        fi
+    fi
+
+    return 1
+ }
+
+ batdrv_recommendations () {
+     # output LG laptop specific recommendations
+     # prerequisite: batdrv_init()
+
+     soc_gt_stop_recommendation
+
+     return 0
+ }
diff --git a/bat.d/40-sony b/bat.d/40-sony
--- a/bat.d/40-sony
+++ b/bat.d/40-sony
@@ -240,7 +240,7 @@ batdrv_write_thresholds () {
                 if [ -n "$4" ]; then
                     cprintf "" "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": care limiter not specified or invalid (must be 50, 80 or 100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
-                    pcrintf "" "Error: care limiter (%s) not specified or invalid (must be 50, 80 or 100). Aborted.\n" "$new_stop" 1>&2
+                    cprintf "" "Error: care limiter (%s) not specified or invalid (must be 50, 80 or 100). Aborted.\n" "$new_stop" 1>&2
                 fi
                 ;;
         esac
@@ -276,9 +276,9 @@ batdrv_write_thresholds () {
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
-                    printf "  care limiter = %d\n" "$new_stop" 1>&2
+                    printf        "  care limiter = %3d\n" "$new_stop" 1>&2
                 else
-                    cprintf "err" "  care limiter = %d (Error: write failed)\n" "$new_stop" 1>&2
+                    cprintf "err" "  care limiter = %3d (Error: write failed)\n" "$new_stop" 1>&2
                 fi
                 ;;
             1)
@@ -287,11 +287,16 @@ batdrv_write_thresholds () {
                 fi
                 ;;
         esac
+
     else
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).no_change: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_stop; new=$sony_stop"
         if [ "$verb" = "2" ]; then
-                printf "  care limiter = %d (no change)\n" "$new_stop" 1>&2
+            printf "  care limiter = %3d (no change)\n" "$new_stop" 1>&2
         fi
+    fi
+
+    if [ "$rc" -eq 0 ] && [ "$verb" = "2" ]; then
+        soc_gt_stop_notice
     fi
 
     return $rc
@@ -493,8 +498,29 @@ batdrv_show_battery_data () {
     return 0
 }
 
+batdrv_check_soc_gt_stop () {
+    # check if battery charge level (SOC) is greater than the stop threshold
+    # rc: 0=greater/¹=less or equal (or thresholds not supported)
+    # global params: $_bm_thresh, $_bat_str
+    # prerequisite: batdrv_init(), batdrv_select_battery()
+
+    local soc stop
+
+    if [ "$_bm_thresh" = "natacpi" ] && soc=$(read_sysval "$ACPIBATDIR/$_bat_str/capacity"); then
+        stop="$(batdrv_read_threshold 0)"
+        if [ -n "$stop" ] && [ "$soc" -gt "$stop" ]; then
+            return 0
+        fi
+    fi
+
+    return 1
+ }
+
 batdrv_recommendations () {
-     # no recommendations for Sony laptops
+    # output Sony laptop specific recommendations
+    # prerequisite: batdrv_init()
+
+    soc_gt_stop_recommendation
 
     return 0
-}
+ }
diff --git a/bat.d/60-macbook b/bat.d/60-macbook
--- a/bat.d/60-macbook
+++ b/bat.d/60-macbook
@@ -362,10 +362,10 @@ batdrv_write_thresholds () {
         case $verb in
             2)
                 if [ $rc -eq 0 ]; then
-                    printf "  stop  = %3d\n" "$new_stop" 1>&2
-                    printf "  start = %3d (due to hardware constraint)\n" "$new_start" 1>&2
+                    printf        "  %-5s = %3d\n" "stop" "$new_stop" 1>&2
+                    printf        "  %-5s = %3d (due to hardware constraint)\n" "start" "$new_start" 1>&2
                 else
-                    cprintf "err" "  stop  = %3d (Error: write failed)\n" "$new_stop" 1>&2
+                    cprintf "err" "  %-5s = %3d (Error: write failed)\n" "stop" "$new_stop" 1>&2
                 fi
                 ;;
             1)
@@ -378,9 +378,13 @@ batdrv_write_thresholds () {
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).stop.no_change: bat=$_bat_str; cfg=$_bt_cfg_bat; old=$old_stop; new=$new_stop"
 
         if [ "$verb" = "2" ]; then
-            printf "  stop  = %3d (no change)\n" "$new_stop" 1>&2
-            printf "  start = %3d (no change)\n" "$new_start" 1>&2
+            printf "  %-5s = %3d (no change)\n" "stop" "$new_stop" 1>&2
+            printf "  %-5s = %3d (no change)\n" "start" "$new_start" 1>&2
         fi
+    fi
+
+    if [ "$rc" -eq 0 ] && [ "$verb" = "2" ]; then
+        soc_gt_stop_notice
     fi
 
     echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).complete: bat=$_bat_str; cfg=$_bt_cfg_bat; rc=$rc"
@@ -464,7 +468,7 @@ batdrv_read_force_discharge () {
 }
 
 batdrv_write_force_discharge () {
-    # function not implemented
+    # function not implemented for Macbooks
     # global param: $_batdrv_plugin
     # prerequisite: batdrv_init()
 
@@ -473,7 +477,7 @@ batdrv_write_force_discharge () {
 }
 
 batdrv_cancel_force_discharge () {
-    # function not implemented
+    # function not implemented for Macbooks
     # global param: $_batdrv_plugin
     # prerequisite: batdrv_init()
 
@@ -482,7 +486,7 @@ batdrv_cancel_force_discharge () {
 }
 
 batdrv_force_discharge_active () {
-    # function not implemented
+    # function not implemented for Macbooks
     # global param: $_batdrv_plugin
     # prerequisite: batdrv_init()
 
@@ -491,7 +495,7 @@ batdrv_force_discharge_active () {
 }
 
 batdrv_discharge () {
-    # function not implemented
+    # function not implemented for Macbooks
     # global param: $_batdrv_plugin
     # prerequisite: batdrv_init()
 
@@ -631,8 +635,29 @@ batdrv_show_battery_data () {
     return 0
 }
 
+batdrv_check_soc_gt_stop () {
+    # check if battery charge level (SOC) is greater than the stop threshold
+    # rc: 0=greater/¹=less or equal (or thresholds not supported)
+    # global params: $_bm_thresh, $_bat_str
+    # prerequisite: batdrv_init(), batdrv_select_battery()
+
+    local soc stop
+
+    if [ "$_bm_thresh" = "natacpi" ] && soc=$(read_sysval "$ACPIBATDIR/$_bat_str/capacity"); then
+        stop="$(batdrv_read_threshold stop 0)"
+        if [ -n "$stop" ] && [ "$soc" -gt "$stop" ]; then
+            return 0
+        fi
+    fi
+
+    return 1
+}
+
 batdrv_recommendations () {
-     # no recommendations
+    # output Macbook specific recommendations
+    # prerequisite: batdrv_init()
+
+    soc_gt_stop_recommendation
 
     return 0
 }
