bat.d/wilco-ec: thresholds apply to all batteries; adapt messages

diff --git a/bat.d/66-wilco-ec b/bat.d/66-wilco-ec
--- a/bat.d/66-wilco-ec
+++ b/bat.d/66-wilco-ec
@@ -280,7 +280,7 @@ batdrv_write_thresholds () {
         case $verb in
             1)
                 if [ -n "$4" ]; then
-                    echo_message "Error in configuration at START_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_start}\": not specified, invalid or out of range (50..95). Battery skipped."
+                    echo_message "Error in configuration at START_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_start}\": not specified, invalid or out of range (50..95). Skipped."
                 fi
                 ;;
 
@@ -288,7 +288,7 @@ batdrv_write_thresholds () {
                 if [ -n "$4" ]; then
                     cprintf "" "Error in configuration at START_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (50..95). Aborted.\n" "$_bt_cfg_bat" "$new_start" 1>&2
                 else
-                    cprintf "" "Error: start charge threshold (%s) for battery %s is not specified, invalid or out of range (50..95). Aborted.\n" "$new_start" "$_bat_str" 1>&2
+                    cprintf "" "Error: start charge threshold (%s) is not specified, invalid or out of range (50..95). Aborted.\n" "$new_start" 1>&2
                 fi
                 ;;
         esac
@@ -303,7 +303,7 @@ batdrv_write_thresholds () {
         case $verb in
             1)
                 if [ -n "$4" ]; then
-                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (55..100). Battery skipped."
+                    echo_message "Error in configuration at STOP_CHARGE_THRESH_${_bt_cfg_bat}=\"${new_stop}\": not specified, invalid or out of range (55..100). Skipped."
                 fi
                 ;;
 
@@ -311,7 +311,7 @@ batdrv_write_thresholds () {
                 if [ -n "$4" ]; then
                     cprintf "" "Error in configuration at STOP_CHARGE_THRESH_%s=\"%s\": not specified, invalid or out of range (55..100). Aborted.\n" "$_bt_cfg_bat" "$new_stop" 1>&2
                 else
-                    cprintf "" "Error: stop charge threshold (%s) for battery %s is not specified, invalid or out of range (55..100). Aborted.\n" "$new_stop" "$_bat_str" 1>&2
+                    cprintf "" "Error: stop charge threshold (%s) is not specified, invalid or out of range (55..100). Aborted.\n" "$new_stop" 1>&2
                 fi
                 ;;
         esac
@@ -324,7 +324,7 @@ batdrv_write_thresholds () {
         case $verb in
             1)
                 if [ -n "$4" ]; then
-                    echo_message "Error in configuration: START_CHARGE_THRESH_${_bt_cfg_bat} > STOP_CHARGE_THRESH_$_bt_cfg_bat - 5. Battery skipped."
+                    echo_message "Error in configuration: START_CHARGE_THRESH_${_bt_cfg_bat} > STOP_CHARGE_THRESH_$_bt_cfg_bat - 5. Skipped."
                 fi
                 ;;
 
@@ -332,7 +332,7 @@ batdrv_write_thresholds () {
                 if [ -n "$4" ]; then
                     cprintf "" "Error in configuration: START_CHARGE_THRESH_%s > STOP_CHARGE_THRESH_%s - 5. Aborted.\n" "$_bt_cfg_bat" "$_bt_cfg_bat" 1>&2
                 else
-                    cprintf "" "Error: start threshold > stop threshold - 5 for battery %s. Aborted.\n" "$_bat_str" 1>&2
+                    cprintf "" "Error: start threshold > stop threshold - 5. Aborted.\n" 1>&2
                 fi
                 ;;
         esac
@@ -344,8 +344,8 @@ batdrv_write_thresholds () {
        ! old_stop=$(batdrv_read_threshold stop 0); then
         echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).read_error: bat=$_bat_str; cfg=$_bt_cfg_bat"
         case $verb in
-            1) echo_message "Error: could not read current charge threshold(s) for battery $_bat_str. Battery skipped." ;;
-            2) cprintf "" "Error: could not read current charge threshold(s) for battery %s. Aborted.\n" "$_bat_str" 1>&2 ;;
+            1) echo_message "Error: could not read current charge threshold(s). Skipped." ;;
+            2) cprintf "" "Error: could not read current charge threshold(s). Aborted.\n" 1>&2 ;;
         esac
         return 4
     fi
@@ -362,7 +362,7 @@ batdrv_write_thresholds () {
 
     # write new thresholds in determined sequence
     if [ "$verb" = "2" ]; then
-        printf "Setting temporary charge thresholds for battery %s:\n" "$_bat_str" 1>&2
+        printf "Setting temporary charge thresholds:\n" 1>&2
     fi
 
     # prerequisite: check charge type and change to 'Custom' if necessary
@@ -372,11 +372,11 @@ batdrv_write_thresholds () {
             # changing to 'Custom' failed
             case $verb in
                 1)
-                    echo_message "Error: failed to set 'Custom' charge type for battery $_bat_str. Skipped."
+                    echo_message "Error: failed to set 'Custom' charge type. Skipped."
                     ;;
 
                 2)
-                    cprintf "" "Error: failed to set 'Custom' charge type for battery %s. Aborted.\n" "$_bat_str" 1>&2
+                    cprintf "" "Error: failed to set 'Custom' charge type. Aborted.\n" 1>&2
                     ;;
             esac
             echo_debug "bat" "batdrv.${_batdrv_plugin}.write_thresholds($1, $2, $3, $4).chtype_error: bat=$_bat_str; cfg=$_bt_cfg_bat; old_chtype=$old_chtype; rc=6"
@@ -418,7 +418,7 @@ batdrv_write_thresholds () {
                     ;;
                 1)
                     if [ $steprc -gt 0 ]; then
-                        echo_message "Error: writing $step charge threshold for battery $_bat_str failed."
+                        echo_message "Error: writing $step charge threshold failed."
                     fi
                     ;;
             esac
@@ -478,20 +478,18 @@ batdrv_chargeonce () {
 }
 
 batdrv_apply_configured_thresholds () {
-    # apply configured stop thresholds from configuration to all batteries
+    # apply configured thresholds from configuration to all batteries
     # - called for bg tasks tlp init [re]start/auto and tlp start
     # output parameter errors only
     # prerequisite: batdrv_init()
 
-    local bat start_thresh stop_thresh
+    local start_thresh stop_thresh
 
-    for bat in BAT0 BAT1; do
-        if batdrv_select_battery "$bat"; then
-            eval start_thresh="\$START_CHARGE_THRESH_${_bt_cfg_bat}"
-            eval stop_thresh="\$STOP_CHARGE_THRESH_${_bt_cfg_bat}"
-            batdrv_write_thresholds "$start_thresh" "$stop_thresh" 1 1
-        fi
-    done
+    if batdrv_select_battery "DEF"; then
+        eval start_thresh="\$START_CHARGE_THRESH_${_bt_cfg_bat}"
+        eval stop_thresh="\$STOP_CHARGE_THRESH_${_bt_cfg_bat}"
+        batdrv_write_thresholds "$start_thresh" "$stop_thresh" 1 1
+    fi
 
     return 0
 }
