Cleanup indent: replace tabs with 4 spaces

diff --git a/tlp b/tlp
--- a/tlp
+++ b/tlp
@@ -10,8 +10,8 @@ RFLIB=/usr/lib/tlp-pm/tlp-rf-func
 
 # --- Source libraries
 if [ ! -f $LIB ]; then
-	echo "Error: missing function library \'$LIB\'."
-	exit 1
+    echo "Error: missing function library \'$LIB\'."
+    exit 1
 fi
 . $LIB
 
@@ -27,111 +27,111 @@ echo_debug "run" "+++ mode=$mode"
 echo_debug "path" "PATH=$PATH"
 
 case "$mode" in
-	start) # Set start power mode depending on state
-		check_root
-		get_power_state
-		pwr=$?
-		load_tp_modules
-		set_laptopmode $pwr
-		set_dirty_parms $pwr
+    start) # Set start power mode depending on state
+        check_root
+        get_power_state
+        pwr=$?
+        load_tp_modules
+        set_laptopmode $pwr
+        set_dirty_parms $pwr
         set_sched_powersave $pwr
-		set_phc_controls $pwr
-		set_disk_apm_level $pwr
-		set_disk_io_sched
-		set_sata_link_power $pwr
+        set_phc_controls $pwr
+        set_disk_apm_level $pwr
+        set_disk_io_sched
+        set_sata_link_power $pwr
         set_pcie_aspm $pwr
         set_radeon_profile $pwr
-		set_wifi_power_mode $pwr
-		disable_wake_on_lan $pwr
-		set_sound_power_mode $pwr
+        set_wifi_power_mode $pwr
+        disable_wake_on_lan $pwr
+        set_sound_power_mode $pwr
         enable_runtime_pm
         enable_usb_suspend 0
-		set_charge_thresholds
-		[ "$pwr" = "1" ] && poweroff_drivebay 0
+        set_charge_thresholds
+        [ "$pwr" = "1" ] && poweroff_drivebay 0
         
         echo_started_mode $pwr
-		;;
+        ;;
 
-	true|bat*) # Set battery power mode
-		check_root
-		load_tp_modules
-		set_laptopmode 1
-		set_dirty_parms 1
+    true|bat*) # Set battery power mode
+        check_root
+        load_tp_modules
+        set_laptopmode 1
+        set_dirty_parms 1
         set_sched_powersave 1
-		set_phc_controls 1
-		set_disk_apm_level 1
-		set_disk_io_sched
-		set_sata_link_power 1
+        set_phc_controls 1
+        set_disk_apm_level 1
+        set_disk_io_sched
+        set_sata_link_power 1
         set_pcie_aspm 1
         set_radeon_profile 1
-		set_wifi_power_mode 1
-		disable_wake_on_lan 1
-		set_sound_power_mode 1
+        set_wifi_power_mode 1
+        disable_wake_on_lan 1
+        set_sound_power_mode 1
         enable_runtime_pm
         enable_usb_suspend 0
-		poweroff_drivebay 0
+        poweroff_drivebay 0
         
         echo_started_mode 1
-		;;
-		
-	false|ac) # Set ac power mode
-		check_root
-		load_tp_modules
-		set_laptopmode 0
-		set_dirty_parms 0
+        ;;
+        
+    false|ac) # Set ac power mode
+        check_root
+        load_tp_modules
+        set_laptopmode 0
+        set_dirty_parms 0
         set_sched_powersave 0
-		set_phc_controls 0
-		set_disk_apm_level 0
-		set_disk_io_sched
-		set_sata_link_power 0
+        set_phc_controls 0
+        set_disk_apm_level 0
+        set_disk_io_sched
+        set_sata_link_power 0
         set_pcie_aspm 0
         set_radeon_profile 0
-		set_wifi_power_mode 0
-		disable_wake_on_lan 0
-		set_sound_power_mode 0
+        set_wifi_power_mode 0
+        disable_wake_on_lan 0
+        set_sound_power_mode 0
         enable_runtime_pm
         enable_usb_suspend 0
         
         echo_started_mode 0
-		;;
-		
-	wifi) # Set wifi power mode depending on state
-		check_root
-		get_power_state
-		pwr=$?
-		set_wifi_power_mode $pwr $2
-		;;
+        ;;
+        
+    wifi) # Set wifi power mode depending on state
+        check_root
+        get_power_state
+        pwr=$?
+        set_wifi_power_mode $pwr $2
+        ;;
 
-	usb) # Enable usb autosuspend
-		check_root
-		enable_usb_suspend 1
-		;;
-		
-	bayoff) # Power off drive bay
-		check_root
-		poweroff_drivebay 1
-		;;
-		
-	xlogin) # Called on desktop login
-		;;
+    usb) # Enable usb autosuspend
+        check_root
+        enable_usb_suspend 1
+        ;;
+        
+    bayoff) # Power off drive bay
+        check_root
+        poweroff_drivebay 1
+        ;;
+        
+    xlogin) # Called on desktop login
+        ;;
 
-	discharge) # Discharge battery completely (to recalibrate)
-		check_root
-		load_tp_modules
-		discharge_battery $2
-		;;
-		
-	setcharge) # Set charge thresholds (temporarily)
-		check_root
-		load_tp_modules
-		setcharge_battery $2 $3 $4
-		;;
+    discharge) # Discharge battery completely (to recalibrate)
+        check_root
+        load_tp_modules
+        discharge_battery $2
+        ;;
+        
+    setcharge) # Set charge thresholds (temporarily)
+        check_root
+        load_tp_modules
+        setcharge_battery $2 $3 $4
+        ;;
 
-	fullcharge) # Charge battery up to 100% (temporarily)
-		check_root
-		load_tp_modules
-		setcharge_battery 96 100 $2
-		;;
+    fullcharge) # Charge battery up to 100% (temporarily)
+        check_root
+        load_tp_modules
+        setcharge_battery 96 100 $2
+        ;;
         
     stat) # Show status
         tlp-stat
@@ -142,11 +142,11 @@ case "$mode" in
             get_disk_dev $dev
             echo "$disk_dev: $disk_id"
         done } | sort
-		;;
+        ;;
         
-	*) 
-		echo "Usage: tlp start|true|bat|false|ac|wifi|usb|bayoff|discharge|setcharge|fullcharge|stat|diskid"
-		;;
+    *) 
+        echo "Usage: tlp start|true|bat|false|ac|wifi|usb|bayoff|discharge|setcharge|fullcharge|stat|diskid"
+        ;;
 esac
 
 exit 0
diff --git a/tlp-rf b/tlp-rf
--- a/tlp-rf
+++ b/tlp-rf
@@ -21,33 +21,33 @@ self=${0##*/}
 
 case $self in
     bluetooth|wifi|wwan)
-		case $1 in
-			on)
-				device_on $self
-				echo_device_state $self $devs
-				;;
+        case $1 in
+            on)
+                device_on $self
+                echo_device_state $self $devs
+                ;;
 
-			off)
-				device_off $self
-				echo_device_state $self $devs
-				;;
-				
-			toggle)
-				device_toggle $self
-				echo_device_state $self $devs
-				;;
-				
-			*)
+            off)
+                device_off $self
+                echo_device_state $self $devs
+                ;;
+                
+            toggle)
+                device_toggle $self
+                echo_device_state $self $devs
+                ;;
+                
+            *)
                 device_state $self
-				echo_device_state $self $devs
-				;;
-		esac
+                echo_device_state $self $devs
+                ;;
+        esac
         ;;
 
     *)
-		echo "Error: unknown device type \"$self\"."
-		exit 1
-		;;
+        echo "Error: unknown device type \"$self\"."
+        exit 1
+        ;;
 esac
 
 exit 0
diff --git a/tlp-rf-func b/tlp-rf-func
--- a/tlp-rf-func
+++ b/tlp-rf-func
@@ -11,26 +11,26 @@ RFKILL="$(which rfkill 2> /dev/null)"
 # ----------------------------------------------------------------------------
 # Functions
 get_devc () { # $1: rftype; retval $devc
-	local i
+    local i
     
     check_sysfs "get_devc" "/sys/class/rfkill"
 
     devc=""
     devs=254
     is2200="0"
-	
-	case $1 in
-		wwan|bluetooth)
-			for i in /sys/class/rfkill/rfkill* ; do
-				if [ -f $i/type  ] && [ "$(cat $i/type)" = "$1" ]; then 
-					devc="$i/state"
-					echo_debug "rf" "get_devc($1) = $devc"
-					return 0
-				fi
-			done
-			;;
+    
+    case $1 in
+        wwan|bluetooth)
+            for i in /sys/class/rfkill/rfkill* ; do
+                if [ -f $i/type  ] && [ "$(cat $i/type)" = "$1" ]; then 
+                    devc="$i/state"
+                    echo_debug "rf" "get_devc($1) = $devc"
+                    return 0
+                fi
+            done
+            ;;
 
-		wifi)
+        wifi)
             if [ -d /sys/bus/pci/drivers/ipw2200 ]; then
                 for i in /sys/bus/pci/drivers/ipw2200/*/rf_kill ; do
                     if [ -f $i ]; then
@@ -48,193 +48,193 @@ get_devc () { # $1: rftype; retval $devc
                         return 0
                     fi
                 done
-			fi
-			;;
+            fi
+            ;;
         
         *)
-			echo "Error: unknown device type \"$1\"" 1>&2
-			echo_debug "rf" "get_devc($1).unknown_type"
+            echo "Error: unknown device type \"$1\"" 1>&2
+            echo_debug "rf" "get_devc($1).unknown_type"
             return 0
-			;;
-	esac
+            ;;
+    esac
     
     echo_debug "rf" "get_devc($1).not_present"
-	
-	return 0
+    
+    return 0
 }
 
 err_no_root_priv () { 
-	echo "Error: root privilege needed. Please call me with sudo." 1>&2
-	
-	return 0
+    echo "Error: root privilege needed. Please call me with sudo." 1>&2
+    
+    return 0
 }
 
 get_devs () { # $1: rftype; retval $devs: 0=off/1=on
-	if [ -n "$devc" ]; then
+    if [ -n "$devc" ]; then
         devs=$(cat $devc)
         if [ "$is2200" = "1" ]; then
-			devs=$((! $devs))
-		fi
+            devs=$((! $devs))
+        fi
     fi
 
-	echo_debug "rf" "get_devs($1) = $devs"
-	
-	return 0
+    echo_debug "rf" "get_devs($1) = $devs"
+    
+    return 0
 }
 
 device_state () { # $1: rftype 
-	echo_debug "rf" "device_state($1)"
+    echo_debug "rf" "device_state($1)"
     
     get_devc $1
-    get_devs $1	
+    get_devs $1 
 }
 
 
 device_on () { # $1: rftype 
-	echo_debug "rf" "device_on($1)"
+    echo_debug "rf" "device_on($1)"
     
     get_devc $1
     [ -z "$devc" ] && return 0
-    get_devs $1	
-	
-	if [ "$is2200" = "1" ]; then
-		if [ "$(id -u)" = "0" ]; then
-			echo_debug "rf" "device_on($1).ipw2200"
-			echo -n 0 > $devc
-		else
-			err_no_root_priv
-		fi
-	elif [ -x "$RFKILL" ]; then
-		echo_debug "rf" "device_on($1).rfkill"
-		$RFKILL unblock $1
-	else
-		if [ "$(id -u)" = "0" ]; then
-			echo_debug "rf" "device_on($1).devc"
-			echo -n 1 > $devc
-		else
-			err_no_root_priv
-		fi
-	fi
+    get_devs $1 
+    
+    if [ "$is2200" = "1" ]; then
+        if [ "$(id -u)" = "0" ]; then
+            echo_debug "rf" "device_on($1).ipw2200"
+            echo -n 0 > $devc
+        else
+            err_no_root_priv
+        fi
+    elif [ -x "$RFKILL" ]; then
+        echo_debug "rf" "device_on($1).rfkill"
+        $RFKILL unblock $1
+    else
+        if [ "$(id -u)" = "0" ]; then
+            echo_debug "rf" "device_on($1).devc"
+            echo -n 1 > $devc
+        else
+            err_no_root_priv
+        fi
+    fi
     
     get_devs $1
-	
-	return 0
+    
+    return 0
 }
 
 device_off () { # $1: rftype
-	echo_debug "rf" "device_off($1)"
+    echo_debug "rf" "device_off($1)"
     
     get_devc $1
     [ -z "$devc" ] && return 0
-    get_devs $1	
-	
-	if [ "$is2200" = "1" ]; then
-		if [ "$(id -u)" = "0" ]; then
-			echo_debug "rf" "device_off($1).ipw2200"
-			echo -n 1 > $devc
-		else
-			err_no_root_priv
-		fi
-	elif [ -x "$RFKILL" ]; then
-		echo_debug "rf" "device_off($1).rfkill"
-		$RFKILL block $1
-	else
-		if [ "$(id -u)" = "0" ]; then
-			echo_debug "rf" "device_off($1).devc"
-			echo -n 0 > $devc
-		else
-			err_no_root_priv
-		fi
-	fi
+    get_devs $1 
+    
+    if [ "$is2200" = "1" ]; then
+        if [ "$(id -u)" = "0" ]; then
+            echo_debug "rf" "device_off($1).ipw2200"
+            echo -n 1 > $devc
+        else
+            err_no_root_priv
+        fi
+    elif [ -x "$RFKILL" ]; then
+        echo_debug "rf" "device_off($1).rfkill"
+        $RFKILL block $1
+    else
+        if [ "$(id -u)" = "0" ]; then
+            echo_debug "rf" "device_off($1).devc"
+            echo -n 0 > $devc
+        else
+            err_no_root_priv
+        fi
+    fi
 
     get_devs $1
-		
-	return 0
+        
+    return 0
 }
 
 device_toggle () { # $1: rftype
-	echo_debug "rf" "device_toggle($1)"
+    echo_debug "rf" "device_toggle($1)"
 
     get_devc $1
     [ -z "$devc" ] && return 0
-    get_devs $1	
-			
-	if [ "$is2200" = "1" ]; then
-		if [ "$(id -u)" = "0" ]; then
-			echo_debug "rf" "device_toggle($1).ipw2200"
-			case $devs in
-				0) echo -n 0 > $devc ;;
-				1) echo -n 1 > $devc ;;
-				*) ;;
-			esac
-		else
-			err_no_root_priv
-		fi
-	elif [ -x "$RFKILL" ]; then
-		echo_debug "rf" "device_toggle($1).rfkill"
-		case $devs in
-			0) $RFKILL unblock $1 ;;
-			1) $RFKILL block $1   ;;				
-			*) ;;
-		esac
-	else
-		if [ "$(id -u)" = "0" ]; then
-			echo_debug "rf" "device_toggle($1).devc"
-			case $devs in
-				0) echo -n 1 > $devc ;;
-				1) echo -n 0 > $devc ;;
-				*) ;;
-			esac
-		else
-			err_no_root_priv
-		fi
-	fi
+    get_devs $1 
+            
+    if [ "$is2200" = "1" ]; then
+        if [ "$(id -u)" = "0" ]; then
+            echo_debug "rf" "device_toggle($1).ipw2200"
+            case $devs in
+                0) echo -n 0 > $devc ;;
+                1) echo -n 1 > $devc ;;
+                *) ;;
+            esac
+        else
+            err_no_root_priv
+        fi
+    elif [ -x "$RFKILL" ]; then
+        echo_debug "rf" "device_toggle($1).rfkill"
+        case $devs in
+            0) $RFKILL unblock $1 ;;
+            1) $RFKILL block $1   ;;                
+            *) ;;
+        esac
+    else
+        if [ "$(id -u)" = "0" ]; then
+            echo_debug "rf" "device_toggle($1).devc"
+            case $devs in
+                0) echo -n 1 > $devc ;;
+                1) echo -n 0 > $devc ;;
+                *) ;;
+            esac
+        else
+            err_no_root_priv
+        fi
+    fi
     
     get_devs $1
-	
-	return 0
+    
+    return 0
 }
 
 echo_device_state () { # $1: rftype, $2: state
-	case $1 in
-		bluetooth)
-			devstr="bluetooth"
-			;;
-			
-		wifi)
-			devstr="wifi     "
-			;;
-		
-		wwan)
-			devstr="wwan     "
-			;;
-			
-		*)
-			devstr=$1
-			;;
-	esac
-	
-	case $2 in
-		0) 
-			echo "$devstr = off (software)"
-			;;
-
-		1) 
-			echo "$devstr = on"
-			;;
+    case $1 in
+        bluetooth)
+            devstr="bluetooth"
+            ;;
             
-		2) 
-			echo "$devstr = off (hardware)"
-			;;
-			
-		254) 
-			echo "$devstr = none (no device)"
-			;;
+        wifi)
+            devstr="wifi     "
+            ;;
+        
+        wwan)
+            devstr="wwan     "
+            ;;
+            
+        *)
+            devstr=$1
+            ;;
+    esac
+    
+    case $2 in
+        0) 
+            echo "$devstr = off (software)"
+            ;;
 
-		*)
+        1) 
+            echo "$devstr = on"
+            ;;
+            
+        2) 
+            echo "$devstr = off (hardware)"
+            ;;
+            
+        254) 
+            echo "$devstr = none (no device)"
+            ;;
+
+        *)
             echo "$devstr = unknown state \"$state\""
-	esac
-	
-	return 0
+    esac
+    
+    return 0
 }
 
diff --git a/tlp-run-on b/tlp-run-on
--- a/tlp-run-on
+++ b/tlp-run-on
@@ -4,27 +4,27 @@ self=${0##*/}
 
 cmd=$1
 if [ -z "$1" ]; then
-	echo "Usage: $self command [arg(s)]"
-	exit 1
+    echo "Usage: $self command [arg(s)]"
+    exit 1
 fi
 
 shift
 
 case $self in
     run-on-ac)
-		if on_ac_power; then		
-			$cmd $@
-		fi
-		;;
-		
-	run-on-bat)
-		if ! on_ac_power; then		
-			$cmd $@
-		fi
-		;;
+        if on_ac_power; then        
+            $cmd $@
+        fi
+        ;;
+        
+    run-on-bat)
+        if ! on_ac_power; then      
+            $cmd $@
+        fi
+        ;;
 
     *)
-		echo "Error: unknown mode $self."
-		exit 1
-		;;
+        echo "Error: unknown mode $self."
+        exit 1
+        ;;
 esac
diff --git a/tlp-stat b/tlp-stat
--- a/tlp-stat
+++ b/tlp-stat
@@ -18,40 +18,40 @@ USBD=/sys/bus/usb/devices
 
 # --- Functions
 echoparm () { # $1: file, $2: n/a message, $3: unit, $4: cutoff
-	local val
-	
-	if [ -f $1 ]; then
-		val=`cat $1`
-		if [ -n "$4" ]; then
-			val=${val%$4}
-		fi
-		if [ -n "$3" ]; then	
-			echo "$1 = $val [$3]"
-		else
-			echo "$1 = $val"
-		fi
-	else
-		if [ -n "$2" ]; then
-			echo "$1 = ($2)"
-		else
-			echo "$1 = (not available)"
-		fi
-	fi
+    local val
+    
+    if [ -f $1 ]; then
+        val=`cat $1`
+        if [ -n "$4" ]; then
+            val=${val%$4}
+        fi
+        if [ -n "$3" ]; then    
+            echo "$1 = $val [$3]"
+        else
+            echo "$1 = $val"
+        fi
+    else
+        if [ -n "$2" ]; then
+            echo "$1 = ($2)"
+        else
+            echo "$1 = (not available)"
+        fi
+    fi
 }
 
 # --- Read libraries
 if [ -f $LIB ]; then
-	. $LIB
+    . $LIB
 else
-	echo "Fatal error: library $LIB not installed."
-	exit 1
+    echo "Fatal error: library $LIB not installed."
+    exit 1
 fi
 
 if [ -f $RFLIB ]; then
-	. $RFLIB
+    . $RFLIB
 else
-	echo "Fatal error: library $RFLIB not installed."
-	exit 1
+    echo "Fatal error: library $RFLIB not installed."
+    exit 1
 fi
 
 # --- MAIN
@@ -63,15 +63,15 @@ load_tp_modules
 echo "--- tlp $TLPVER --------------------------------------------"
 
 if [ -f $TLPCFG ]; then
-	. $TLPCFG
+    . $TLPCFG
 else
-	echo "Warning: config file $TLPCFG not present."
-	echo
+    echo "Warning: config file $TLPCFG not present."
+    echo
 fi
 
 echo "System = $($DMI -s system-manufacturer)" \
-	   "$($DMI -s system-version)" \
-	   "$($DMI -s system-product-name)"
+       "$($DMI -s system-version)" \
+       "$($DMI -s system-product-name)"
 echo "BIOS = $($DMI -s bios-version)"
 
 [ -x "$LSB" ] && echo "Release = $(lsb_release -d -s)"
@@ -79,17 +79,17 @@ echo "Kernel = $(uname -r -m)"
 echo
 
 if check_laptop_mode_tools; then
-	if [ "$TLP_ENABLE" = "1" ]; then
-		echo "tlp power save = enabled"
-	else
-		echo "tlp power save = not enabled"
-	fi
+    if [ "$TLP_ENABLE" = "1" ]; then
+        echo "tlp power save = enabled"
+    else
+        echo "tlp power save = not enabled"
+    fi
 fi
 
 if get_power_state; then
-	echo "power source = ac"
+    echo "power source = ac"
 else
-	echo "power source = battery"
+    echo "power source = battery"
 fi
 echo
 
@@ -131,9 +131,9 @@ DISK_DEVICES=${DISK_DEVICES:=sda}
 for dev in $DISK_DEVICES; do
     get_disk_dev $dev
 
-	if [ -b /dev/$disk_dev ]; then
-		check_disk_hdparm_cap $disk_dev
-		if [ $? = 0 ]; then
+    if [ -b /dev/$disk_dev ]; then
+        check_disk_hdparm_cap $disk_dev
+        if [ $? = 0 ]; then
             echo "/dev/$disk_dev:"
                 
             if [ -n "$disk_id" ]; then
@@ -162,8 +162,8 @@ for dev in $DISK_DEVICES; do
                 $SMARTCTL -A /dev/$disk_dev | egrep '^(  4|  5|  9 |193)' | \
                   awk -F ' ' '{ printf "          %-25s = %6d \n", $2, $10 }'
             fi
-		fi
-	fi
+        fi
+    fi
 done
 echo
 
@@ -171,13 +171,13 @@ echo
 cnt=0
 for i in /sys/class/scsi_host/host* ; do
     if [ -f $i/link_power_management_policy ]; then
-		echoparm $i/link_power_management_policy
-		cnt=$((cnt+1))
-	fi
+        echoparm $i/link_power_management_policy
+        cnt=$((cnt+1))
+    fi
 done
 if [ $cnt = 0 ]; then
-	echo "sata link power management: no ahci-enabled host controller detected"
-fi	
+    echo "sata link power management: no ahci-enabled host controller detected"
+fi  
 echo 
 
 # pcie aspm
@@ -202,104 +202,104 @@ done
 for i in bluetooth wifi wwan; do
     get_devc $i
     get_devs $i
-	echo_device_state $i $devs
+    echo_device_state $i $devs
 done
 echo
 
 # wifi power mode
 get_wifi_ifaces
 for iface in $WIFACES; do
-	if [ -n "$iface" ]; then
-		wifipm=$($IWC $iface 2> /dev/null | grep "Power Management" | \
-		  sed -r 's/.*Power Management:(on|off).*/\1/')
-		get_wifi_driver $iface
-		echo -n "$iface($WIFIDRV): power management = "
-		case $wifipm in
-			on)
-				echo "on"
-				;;
-				
-			off)
-				if [ -z "$($IWC $iface power off 2>&1)" ]; then
-					echo "off"
-				else
-					echo "off (not supported)"
-				fi
-				;;
-				
-			*) 
-				echo "unknown"
-				;;
-		esac
-	fi
+    if [ -n "$iface" ]; then
+        wifipm=$($IWC $iface 2> /dev/null | grep "Power Management" | \
+          sed -r 's/.*Power Management:(on|off).*/\1/')
+        get_wifi_driver $iface
+        echo -n "$iface($WIFIDRV): power management = "
+        case $wifipm in
+            on)
+                echo "on"
+                ;;
+                
+            off)
+                if [ -z "$($IWC $iface power off 2>&1)" ]; then
+                    echo "off"
+                else
+                    echo "off (not supported)"
+                fi
+                ;;
+                
+            *) 
+                echo "unknown"
+                ;;
+        esac
+    fi
 done
 echo
-	
+    
 # sound power mode
 if [ -d /sys/module/snd_hda_intel ]; then
-	echoparm /sys/module/snd_hda_intel/parameters/power_save
-	echoparm /sys/module/snd_hda_intel/parameters/power_save_controller
+    echoparm /sys/module/snd_hda_intel/parameters/power_save
+    echoparm /sys/module/snd_hda_intel/parameters/power_save_controller
 fi
 if [ -d /sys/module/snd_ac97_codec ]; then
-	echoparm /sys/module/snd_ac97_codec/parameters/power_save
+    echoparm /sys/module/snd_ac97_codec/parameters/power_save
 fi
 echo 
 
 # battery info & charge thresholds 
 if [ -d /sys/devices/platform/smapi ]; then
-	# ThinkPad via tp_smapi
+    # ThinkPad via tp_smapi
     thresh_blacklist_check
     
-	for bat in /sys/devices/platform/smapi/BAT[01]; do
-		if [ -d $bat ] && [ "$(cat $bat/installed)" = "1" ]; then
-			echoparm $bat/manufacturer
-			echoparm $bat/manufacture_date
-			echoparm $bat/first_use_date
-			echoparm $bat/cycle_count
-			echoparm $bat/design_capacity - mWh
-			echoparm $bat/last_full_capacity - mWh
-			echoparm $bat/remaining_capacity - mWh
-			echoparm $bat/remaining_percent - "%"
-			echoparm $bat/remaining_running_time_now - min
-			echoparm $bat/remaining_charging_time - min
-			echo
-			if [ -z "$thresh_blacklisted" ]; then
+    for bat in /sys/devices/platform/smapi/BAT[01]; do
+        if [ -d $bat ] && [ "$(cat $bat/installed)" = "1" ]; then
+            echoparm $bat/manufacturer
+            echoparm $bat/manufacture_date
+            echoparm $bat/first_use_date
+            echoparm $bat/cycle_count
+            echoparm $bat/design_capacity - mWh
+            echoparm $bat/last_full_capacity - mWh
+            echoparm $bat/remaining_capacity - mWh
+            echoparm $bat/remaining_percent - "%"
+            echoparm $bat/remaining_running_time_now - min
+            echoparm $bat/remaining_charging_time - min
+            echo
+            if [ -z "$thresh_blacklisted" ]; then
                 echoparm $bat/start_charge_thresh - "%"
             else
                 echo "$bat/start_charge_thresh = (not available)"
             fi
-			echoparm $bat/stop_charge_thresh - "%"
-			echo
-		fi
-	done
+            echoparm $bat/stop_charge_thresh - "%"
+            echo
+        fi
+    done
 elif [ -d /sys/class/power_supply ]; then
-	if [ -d /sys/devices/platform/thinkpad_acpi ]; then
-		echo "ThinkPad extended battery info not available (missing tp_smapi kernel module)."
-	fi
-	# generic
-	for bat in /sys/class/power_supply/BAT?; do
-		if [ -d $bat ] && [ "$(cat $bat/present)" = "1" ]; then
-			echoparm $bat/manufacturer
-			echoparm $bat/energy_full_design - mWh 000
-			echoparm $bat/energy_full - mWh 000
-			echoparm $bat/energy_now - mWh 000
-			echo
-		fi
-	done
+    if [ -d /sys/devices/platform/thinkpad_acpi ]; then
+        echo "ThinkPad extended battery info not available (missing tp_smapi kernel module)."
+    fi
+    # generic
+    for bat in /sys/class/power_supply/BAT?; do
+        if [ -d $bat ] && [ "$(cat $bat/present)" = "1" ]; then
+            echoparm $bat/manufacturer
+            echoparm $bat/energy_full_design - mWh 000
+            echoparm $bat/energy_full - mWh 000
+            echoparm $bat/energy_now - mWh 000
+            echo
+        fi
+    done
 fi
 
 # usb autosuspend
 if [ "$USB_AUTOSUSPEND" = "1" ]; then
-	echo "tlp usb autosuspend = enabled"
+    echo "tlp usb autosuspend = enabled"
 else
-	echo "tlp usb autosuspend = not enabled"
+    echo "tlp usb autosuspend = not enabled"
 fi
 echo "tlp usb blacklist = ${USB_BLACKLIST:=(not configured)}"
 echo
 
 devices=$(ls $USBD | grep -v ':')
 for usbdev in $devices; do
-	if [ -f $USBD/$usbdev/power/autosuspend ]; then
+    if [ -f $USBD/$usbdev/power/autosuspend ]; then
         if [ -f $USBD/$usbdev/power/control ]; then
             control="control = $(cat $USBD/$usbdev/power/control)" 
         else
@@ -308,9 +308,9 @@ for usbdev in $devices; do
         fi
         
         # show dev path, state, usb id
-		echo -n "$USBD/$usbdev/power/autosuspend = `cat $USBD/$usbdev/power/autosuspend`," \
-		     "$control --" \
-		     "$(cat $USBD/$usbdev/idVendor):$(cat $USBD/$usbdev/idProduct) "
+        echo -n "$USBD/$usbdev/power/autosuspend = `cat $USBD/$usbdev/power/autosuspend`," \
+             "$control --" \
+             "$(cat $USBD/$usbdev/idVendor):$(cat $USBD/$usbdev/idProduct) "
         
         # show product string     
         product="$([ -f $USBD/$usbdev/product ] && cat $USBD/$usbdev/product)"
@@ -333,7 +333,7 @@ for usbdev in $devices; do
             fi
         done 
         echo "(${driverlist:-no driver})"
-	fi
+    fi
 done
 echo
 
