Threshold and discharge logic refactored. Messages more user friendly.

diff --git a/tlp-functions b/tlp-functions
--- a/tlp-functions
+++ b/tlp-functions
@@ -10,7 +10,7 @@
 
 # ----------------------------------------------------------------------------
 # Definitions
-TLPVER=0.3.4.901
+TLPVER=0.3.4.902
 DEFAULT_FILE=/etc/default/tlp
 
 ACPWR=on_ac_power
@@ -674,149 +674,89 @@ enable_usb_suspend () { # $1: 0=silent/1=report result
     return 0
 }
 
-do_threshold () { # $1: treshold file, $2: new value
-    local othr rc=0
-    
-    if [ -n "$2" ]; then
-        if [ -f $1 ]; then
-            othr=$(cat $1 2> /dev/null)
-            if [ -z "$othr" ]; then
-                rc=1
-            elif [ "$othr" != "$2" ]; then
-                echo $2 > $1 2> /dev/null
-                rc=$?
-            fi
-        else
-            rc=2
-        fi
-    fi
-    
-    return $rc
-}
-
-thresh_check () { # $1: threshold; ret: 0=invalid/1..100=valid
-    local thr
-    
-    thr=$(echo $1 | egrep '^[0-9]{1,3}$') # check for 1..3 digits
-    [ -z "$thr"  ] && thr=0 
-    [ $thr -gt 100 ] && thr=0 
-    
-    return $thr
-}
-
-do_force_discharge () { # $1: bat sysfile; $2: 0=off/1=on
-    local rc
+do_threshold () { # $1: threshold sysfile, $2: new value
+    local old_thresh rc=0
     
     if [ -f $1 ]; then
-        echo $2 > $1 2> /dev/null
-        rc=$?
-    else 
+        old_thresh=$(cat $1 2> /dev/null)
+        if [ -z "$old_thresh" ]; then
+            rc=1
+        elif [ "$old_thresh" != "$2" ]; then
+            echo $2 > $1 2> /dev/null; rc=$?
+        fi
+    else
         rc=2
     fi
     
     return $rc
 }
 
+check_thresh () { # $1: threshold; ret: 0=invalid/1..100=valid
+    local thresh
+    
+    thresh=$(echo $1 | egrep '^[0-9]{1,3}$') # check for 1..3 digits
+    [ -z "$thresh" ] && thresh=0 # replace empty value with 0
+    [ $thresh -gt 100 ] && thresh=0 # replace values > 100 with 0
+    
+    return $thresh
+}
+
 set_charge_thresholds () {
-    local rc
+    local thresh rc
     
     echo_debug "pm" "set_charge_thresholds.enter"
     [ -d $SMAPIDIR ] || return 0
     echo_debug "pm" "set_charge_thresholds.tp-smapi_present"
     
     if [ -d $SMAPIDIR/BAT0 ] && [ "$(cat $SMAPIDIR/BAT0/installed)" = "1" ]; then
-        if [ -n "$START_CHARGE_THRESH_BAT0" ]; then 
-            do_threshold $SMAPIDIR/BAT0/start_charge_thresh "$START_CHARGE_THRESH_BAT0"
-            rc=$?
-            echo_debug "pm" "set_charge_thresholds.start(BAT0): $START_CHARGE_THRESH_BAT0; rc=$rc"
+        check_thresh "$START_CHARGE_THRESH_BAT0"; thresh=$?
+        if [ $thresh -gt 0 ]; then
+            do_threshold $SMAPIDIR/BAT0/start_charge_thresh $thresh; rc=$?
+            echo_debug "pm" "set_charge_thresholds.start(BAT0): $thresh; rc=$rc"
+        else
+            echo_debug "pm" "set_charge_thresholds.start(BAT0).not_set"
         fi
         
-        if [ -n "$STOP_CHARGE_THRESH_BAT0" ]; then 
-            do_threshold $SMAPIDIR/BAT0/stop_charge_thresh "$STOP_CHARGE_THRESH_BAT0"
-            rc=$?
-            echo_debug "pm" "set_charge_thresholds.stop(BAT0): $STOP_CHARGE_THRESH_BAT0; rc=$rc"
+        check_thresh "$STOP_CHARGE_THRESH_BAT0"; thresh=$?
+        if [ $thresh -gt 0 ]; then
+            do_threshold $SMAPIDIR/BAT0/stop_charge_thresh $thresh; rc=$?
+            echo_debug "pm" "set_charge_thresholds.stop(BAT0): $thresh; rc=$rc"
+        else
+            echo_debug "pm" "set_charge_thresholds.stop(BAT0).not_set"
         fi
     fi
     
     if [ -d $SMAPIDIR/BAT1 ] &&  [ "$(cat $SMAPIDIR/BAT1/installed)" = "1" ]; then
-        if [ -n "$START_CHARGE_THRESH_BAT1" ]; then 
-            do_threshold $SMAPIDIR/BAT1/start_charge_thresh "$START_CHARGE_THRESH_BAT1"
-            rc=$?
-            echo_debug "pm" "set_charge_thresholds.start(BAT1): $START_CHARGE_THRESH_BAT1; rc=$rc"
-        fi
+        check_thresh "$START_CHARGE_THRESH_BAT1"; thresh=$?
+        if [ $thresh -gt 0 ]; then
+            do_threshold $SMAPIDIR/BAT1/start_charge_thresh $thresh; rc=$?
+            echo_debug "pm" "set_charge_thresholds.start(BAT1): $thresh; rc=$rc"
+         else
+            echo_debug "pm" "set_charge_thresholds.start(BAT1).not_set"
+       fi
         
-        if [ -n "$STOP_CHARGE_THRESH_BAT1" ]; then 
-            do_threshold $SMAPIDIR/BAT1/stop_charge_thresh "$STOP_CHARGE_THRESH_BAT1"
-            rc=$?
-            echo_debug "pm" "set_charge_thresholds.stop(BAT1): $STOP_CHARGE_THRESH_BAT1; rc=$rc"
+        check_thresh "$STOP_CHARGE_THRESH_BAT1"; thresh=$?
+        if [ $thresh -gt 0 ]; then
+            do_threshold $SMAPIDIR/BAT1/stop_charge_thresh $thresh; rc=$?
+            echo_debug "pm" "set_charge_thresholds.stop(BAT1): $thresh; rc=$rc"
+        else
+            echo_debug "pm" "set_charge_thresholds.stop(BAT1).not_set"
         fi
     fi
     
     return 0
 }
 
-cancel_discharge () { # called from trap
-    do_force_discharge $bdir/force_discharge 0
-    echo
-    echo "Discharging of battery $bat cancelled."
-    echo_debug "pm" "discharge_battery.cancelled($bat)"
-    exit 0
-}
-
-discharge_battery () { # $1: battery
-    local bat bdir rc
+do_force_discharge () { # $1: bat sysfile; $2: 0=off/1=on
+    local rc
     
-    if [ ! -d $SMAPIDIR ]; then
-        echo_debug "pm" "discharge_battery.no_tp-smapi($bat)"
-        echo "Error: ThinkPad battery functions not available (missing tp_smapi kernel module)."
-        return 1
+    if [ -f $1 ]; then
+        echo $2 > $1 2> /dev/null; rc=$?
+    else 
+        rc=2
     fi
-        
-    if ! get_power_state ; then
-        echo_debug "pm" "discharge_battery.no_ac_power"
-        echo "Error: discharge is possible on ac power only."
-        return 1
-    fi  
-
-    bat=$1
-    bat=${bat:=BAT0} # default is BAT0
-    bat=$(echo $bat | tr "[:lower:]" "[:upper:]")
-    bdir=$SMAPIDIR/$bat
     
-    if [ ! -f $bdir/installed ] || [ "$(cat $bdir/installed)" = "0" ]; then
-        echo_debug "pm" "discharge_battery.not_present($bat)"
-        echo "Error: battery $bat not present."
-        return 1
-    fi
-        
-    do_force_discharge $bdir/force_discharge 1
-    rc=$?
-    if [ $rc -ne 0 ]; then
-        echo_debug "pm" "discharge_battery.force_discharge_not_available($bat)"
-        echo "Error: discharge function not available for this ThinkPad model."
-        return 1
-    fi
-   
-    trap cancel_discharge INT
-    
-    while [ "$(cat $bdir/force_discharge)" = "0" ]; do :; done
-    echo_debug "pm" "discharge_battery.running($bat)"
-
-    while [ "$(cat $bdir/force_discharge)" = "1" ]; do
-        clear
-        echo "Currently discharging battery $bat:"
-        echo "voltage            = $(cat $bdir/voltage) [mV]"
-        echo "remaining percent  = $(cat $bdir/remaining_percent) [%]"
-        echo "remaining capacity = $(cat $bdir/remaining_capacity) [mWh]"
-        echo "remaining time     = $(cat $bdir/remaining_running_time_now) [min]"
-        echo "Press Ctrl+C to cancel."
-        sleep 2
-    done
-
-    echo
-    echo "Done: battery $bat was completely discharged."
-    echo_debug "pm" "discharge_battery.complete($bat)"
-    return 0
+    return $rc
 }
 
 setcharge_battery () { # $1: start charge threshold, $2: stop charge threshold, $3: battery, 
@@ -864,48 +804,128 @@ setcharge_battery () { # $1: start charge threshold, $2: stop charge threshold, 
     fi
  
     # check thresholds 
-    thresh_check $start_thresh; start_thresh=$?
-    thresh_check $stop_thresh; stop_thresh=$?
+    check_thresh $start_thresh; start_thresh=$?
+    check_thresh $stop_thresh; stop_thresh=$?
+  
+    # check if thresholds != 0    
+    if [ $start_thresh -eq 0 ] && [ $stop_thresh -eq 0 ]; then
+        echo "Error: no thresholds configured for $bat."        
+        echo_debug "pm" "setcharge_battery.no_thresholds_configured($bat)"
+        return 1
+    fi
     
-    # check if thresholds > 0 and stop > start + 3 
-    if [ $start_thresh -eq 0 ] || [ $stop_thresh -eq 0 ] || [ $(($start_thresh + 3)) -ge $stop_thresh ]; then
-        echo "Error: invalid thresholds (start=$start_thresh, stop=$stop_thresh)."        
+    # check if stop > start + 3 
+    if [ $(($start_thresh + 3)) -ge $stop_thresh ]; then
+        echo "Error: invalid threshold values for $bat (start=$start_thresh, stop=$stop_thresh)."        
         echo_debug "pm" "setcharge_battery.invalid_thresh($bat): $start_thresh $stop_thresh"
         return 1
     fi
 
     # write threshold values
-    do_threshold $bdir/stop_charge_thresh "$stop_thresh"
-    rc=$?
+    echo "Setting temporary charge thresholds for $bat:"
+    
+    do_threshold $bdir/stop_charge_thresh "$stop_thresh"; rc=$?
     echo_debug "pm" "setcharge_battery.stop($bat): $stop_thresh; rc=$rc"
-    if [ $rc -ne 0 ]; then
-        echo "Error: cannot set stop charge threshold of battery $bat."
+    if [ $rc -eq 0 ]; then
+        echo "  stop  = $stop_thresh"
+    else
+        echo "  stop  = Error:cannot set threshold. Aborting."
         return 1
     fi
 
-    do_threshold $bdir/start_charge_thresh "$start_thresh"
-    rc=$?
-    echo_debug "pm" "setcharge_battery.start($bat): $start_thresh; rc=$rc"
-    if [ $rc -ne 0 ]; then
-        echo "Warning: cannot set start charge threshold of battery $bat."
-        echo "Charging thresholds of battery $bat temporarily set to: stop=$stop_thresh."
+    if [ $start_thresh -gt 0 ]; then
+        do_threshold $bdir/start_charge_thresh "$start_thresh"; rc=$?
+        echo_debug "pm" "setcharge_battery.start($bat): $start_thresh; rc=$rc"
+        if [ $rc -eq 0 ]; then
+            echo "  start = $start_thresh"
+        else
+            echo "  start = Warning: cannot set start charge threshold."
+            return 1
+        fi
     else
-        echo "Charging thresholds of battery $bat temporarily set to: start=$start_thresh stop=$stop_thresh."
+        echo_debug "pm" "setcharge_battery.start($bat).not_configured"
+        echo "  start = not configured"
     fi
     
     # trigger charging via discharge
-    do_force_discharge $bdir/force_discharge 1
-    rc=$?
-    if [ $rc -eq 0 ]; then 
+    do_force_discharge $bdir/force_discharge 1; rc=$?
+    if [ $rc -eq 0 ]; then
+        echo -n "Activating..."
         sleep 2
         do_force_discharge $bdir/force_discharge 0
         echo_debug "pm" "setcharge_battery.initiated($bat)"
         sleep 2
+        echo "done."
     else
-        echo "Warning: cannot force thresholds on this ThinkPad model. Please power off to activate."
         echo_debug "pm" "setcharge_battery.force_discharge_not_available($bat): rc=$rc"
+        echo "Cannot activate immediately on this ThinkPad model. Please power off."
+        return 1
     fi
     
+    return 0
+}
+
+cancel_discharge () { # called from trap
+    do_force_discharge $bdir/force_discharge 0
+    echo_debug "pm" "discharge_battery.cancelled($bat)"
+    echo
+    echo "Discharging of battery $bat cancelled."
+    
+    exit 0
+}
+
+discharge_battery () { # $1: battery
+    local bat bdir rc
+    
+    if [ ! -d $SMAPIDIR ]; then
+        echo_debug "pm" "discharge_battery.no_tp-smapi($bat)"
+        echo "Error: ThinkPad battery functions not available (missing tp_smapi kernel module)."
+        return 1
+    fi
+        
+    if ! get_power_state ; then
+        echo_debug "pm" "discharge_battery.no_ac_power"
+        echo "Error: discharge is possible on ac power only."
+        return 1
+    fi  
+
+    bat=$1
+    bat=${bat:=BAT0} # default is BAT0
+    bat=$(echo $bat | tr "[:lower:]" "[:upper:]")
+    bdir=$SMAPIDIR/$bat
+    
+    if [ ! -f $bdir/installed ] || [ "$(cat $bdir/installed)" = "0" ]; then
+        echo_debug "pm" "discharge_battery.not_present($bat)"
+        echo "Error: battery $bat not present."
+        return 1
+    fi
+        
+    do_force_discharge $bdir/force_discharge 1; rc=$?
+    if [ $rc -ne 0 ]; then
+        echo_debug "pm" "discharge_battery.force_discharge_not_available($bat)"
+        echo "Error: discharge function not available for this ThinkPad model."
+        return 1
+    fi
+   
+    trap cancel_discharge INT
+    
+    while [ "$(cat $bdir/force_discharge)" = "0" ]; do :; done
+    echo_debug "pm" "discharge_battery.running($bat)"
+
+    while [ "$(cat $bdir/force_discharge)" = "1" ]; do
+        clear
+        echo "Currently discharging battery $bat:"
+        echo "voltage            = $(cat $bdir/voltage) [mV]"
+        echo "remaining percent  = $(cat $bdir/remaining_percent) [%]"
+        echo "remaining capacity = $(cat $bdir/remaining_capacity) [mWh]"
+        echo "remaining time     = $(cat $bdir/remaining_running_time_now) [min]"
+        echo "Press Ctrl+C to cancel."
+        sleep 2
+    done
+
+    echo
+    echo "Done: battery $bat was completely discharged."
+    echo_debug "pm" "discharge_battery.complete($bat)"
     return 0
 }
 
