conf.d: new config file parser
The new Perl script tlp-readconfs parses all files in the order given.

Upon each invocation of tlp (or the other top-level shell scripts)
tlp-readconfs is called, consolidated settings are written to a
temporary file (/tmp/tlp-run_XXXXXX.conf) which is subsequently
sourced by the calling shell script.

In addition tlp subcommands init, auto, start, bat, ac, suspend
and resume will copy the temporary file to /run/tlp/run.conf when
finishing.

Other changes:
* tlp.conf - reformatted for readability, explain file precedence,
  refer to tlp-stat -b for needed external kernel modules
* 00-template.conf - new template for drop-in customizations
* man/tlp.8 - cover all config files/directories

References:
* https://github.com/linrunner/TLP/issues/432
* https://github.com/linrunner/TLP/issues/398
* https://github.com/linrunner/TLP/pull/435
* https://github.com/linrunner/TLP/pull/440

diff --git a/tlp-func-base.in b/tlp-func-base.in
--- a/tlp-func-base.in
+++ b/tlp-func-base.in
@@ -14,23 +14,19 @@ readonly TLPVER="1.3.0-alpha.2"
 readonly RUNDIR=@TLP_RUN@
 readonly VARDIR=@TLP_VAR@
 
-readonly CONF_USR=@TLP_CONFUSR@  # /etc/tlp.conf
-readonly CONF_DIR=@TLP_CONFDIR@  # /etc/tlp.conf.d
 readonly CONF_DEF=@TLP_CONFDEF@  # /usr/share/tlp/defaults.conf
+readonly CONF_DIR=@TLP_CONFDIR@  # /etc/tlp.conf.d
+readonly CONF_USR=@TLP_CONFUSR@  # /etc/tlp.conf
 readonly CONF_OLD=@TLP_CONFOLD@  # /etc/default/tlp
-readonly CONF_RUN="run.conf"
-
-### TODO: remove after successful completion of conf.d
-#readonly CUSTOMIZECONFDIR=@TLP_CONFD@
-#readonly CONFFILE_DEF=@TLP_CONFDEF@
-#readonly CONFFILE_TEMP=@TLP_CONFTEMP@
-#readonly CONFFILE_OUTDATED=@TLP_CONFOUTDATED@
+readonly CONF_RUN="$RUNDIR/run.conf"
 
 readonly FLOCK=flock
 readonly HDPARM=hdparm
 readonly LAPMODE=laptop_mode
 readonly LOGGER=logger
+readonly MKTEMP=mktemp
 readonly MODPRO=modprobe
+readonly READCONFS=@TLP_TLIB@/tlp-readconfs
 readonly TPACPIBAT=@TLP_TLIB@/tpacpi-bat
 readonly UDEVADM=udevadm
 
@@ -52,7 +48,7 @@ readonly RE_TPSMAPI_ONLY='^(Edge( 13.*)?|G41|R[56][012][eip]?|R[45]00|SL[45]10|T
 readonly RE_TPSMAPI_AND_TPACPI='^(X1|X220[s]?( Tablet)?|T[45]20[s]?|W520)$'
 readonly RE_TP_NONE='^(L[45]20|SL[345]00|X121e)$'
 
-readonly RE_PARAM='^[A-Z_]+[0-9]*\=[0-9a-zA-Z _-]*$'
+readonly RE_PARAM='^[A-Z_]+[0-9]*=[0-9a-zA-Z _\-:]*$'
 
 # power supplies: ignore MacBook Pro 2017 sbs-charger and hid devices
 readonly RE_PS_IGNORE='sbs-charger|hidpp_battery|hid-'
@@ -69,6 +65,15 @@ _nodebug=0
 
 # ----------------------------------------------------------------------------
 # Functions
+
+# -- Exit
+
+do_exit () { # cleanup and exit  -- $1: rc
+    # remove temporary runconf
+    [ -f $_conf_tmp ] && rm -rf $_conf_tmp
+
+    exit $1
+}
 
 # --- Debug
 
@@ -153,10 +158,10 @@ test_root () { # test root privilege -- rc: 0=root, 1=not root
     [ "$(id -u)" = "0" ]
 }
 
-check_root () { # show error message and exit when root privilege missing
+check_root () { # show error message and quit when root privilege missing
     if ! test_root; then
         echo "Error: missing root privilege." 1>&2
-        exit 1
+        do_exit 1
     fi
 }
 
@@ -382,53 +387,34 @@ create_rundir () { # make sure $RUNDIR exists
 
 # --- Configuration
 
-read_confs () { # read all config files
-    # rc: 0=ok/1=tlp.conf missing/2=defaults.conf missing
-    local cf
-
-    # 1. intrinsic defaults
-    if [ -f $CONF_DEF ]; then
+read_config () { # read all config files and write temporary runconf file
+    # $1: 0=continue/1=quit on error
+    # $2: 1=no trace
+    # rc: 0=ok/5=tlp.conf missing/6=defaults.conf missing/7=file creation error
+    # retval: config parameters;
+    #         _conf_tmp: runconf
+    local rc=0
+    if _conf_tmp=$($MKTEMP --tmpdir "tlp-run_XXXXXX.conf"); then
+        # external perl script: merge all config files to $cf
+        $READCONFS $_conf_tmp $2; rc=$?
         # shellcheck disable=SC1090
-        . $CONF_DEF
+        [ $rc -eq 0 ] && . $_conf_tmp
     else
-        return 2
+        rc=7
     fi
 
-    # 2. customization
-    for cf in $CONF_DIR/*; do
-        # shellcheck disable=SC1090
-        [ ! -f "$cf" ] || . "$cf"
-    done
-
-    # 3. user settings
-    if [ -f $CONF_USR ]; then
-        # shellcheck disable=SC1090
-        . $CONF_USR
-    elif [ -f $CONF_OLD ]; then
-        # shellcheck disable=SC1090
-        . $CONF_OLD
-    else
-        return 1
+    if [ $rc -ne 0 ]; then
+        case $rc in
+            5) echo "Error: cannot read user configuration from $CONF_USR or $CONF_OLD." 1>&2 ;;
+            6) echo "Error: cannot read default configuration from $CONF_DEF." 1>&2 ;;
+            7) echo "Error: cannot write runtime configuration to $_conf_tmp." 1>&2 ;;
+        esac
+        if [ "$1" = "1" ]; then
+            do_exit $rc
+        fi
     fi
 
     return 0
-}
-
-print_conf () { # print runtime conf based on default and customized configuration
-### TODO: only defaults.conf parsed, no aggregation of multiple files, no conf args, shellcheck complains, mktemp?
-cat <<EOF >/tmp/tlp-runtime.conf.prepare
-echo "
-`for i in $(grep -E -v "^#|^\s*$" $CONF_DEF | awk -F'=' '{print $1}');do echo $i=\\'\\"\\$$i\\"\\';done`
-"
-EOF
-. /tmp/tlp-runtime.conf.prepare
-rm /tmp/tlp-runtime.conf.prepare
-}
-
-generate_runtime_conf () { # generate runtime conf file based on default and customized configuration
-    create_rundir
-    print_conf > $RUNDIR/$CONF_RUN
-    chmod -w $RUNDIR/$CONF_RUN
 }
 
 parse_args4config () { # parse command-line arguments: everything after the
@@ -441,14 +427,16 @@ parse_args4config () { # parse command-line arguments: everything after the
     while [ $# -gt 0 ]; do
         if [ $dflag -eq 1 ]; then
             # delimiter was passed --> sanitize and parse argument:
-            #   format is PARAMETER=value (quotes stripped by the shell calling tlp)
-            #   parameter name allows 'A'..'Z' and '_' only, may end in a number (_BAT0)
-            #   parameter value allows  'A'..'Z', 'a'..'z', '0'..'9', ' ', '_', '-'
+            #   quotes stripped by the shell calling tlp
+            #   format is PARAMETER=value
+            #   PARAMETER allows 'A'..'Z' and '_' only, may end in a number (_BAT0)
+            #   value allows  'A'..'Z', 'a'..'z', '0'..'9', ' ', '_', '-', ':'
+            #   value may be an empty string
             if printf "%s" "$1" | grep -E -q "$RE_PARAM"; then
                 param="${1%%=*}"
                 value="${1#*=}"
-                if [ -n "$param" ] && [ -n "$value" ]; then
-                    echo_debug "arg" "parse_args4config.param: $param=$value"
+                if [ -n "$param" ]; then
+                    echo_debug "cfg" "parse_args4config.param: $param=$value"
                     eval "$param='$value'" 2> /dev/null
                 fi
             fi
@@ -460,6 +448,18 @@ parse_args4config () { # parse command-line arguments: everything after the
     done # while arguments
 
     return 0
+}
+
+print_config () { # print runtime conf based on all config files
+    # external perl script: merge all config files to $cf
+    $READCONFS "STDOUT"
+}
+
+save_runconf () { # copy temporary to final runconf
+    create_rundir
+    [ -f $_conf_tmp ] && cp --preserve=timestamps $_conf_tmp $CONF_RUN > /dev/null 2>&1
+    chmod g+r,o+r $_conf_tmp $CONF_RUN > /dev/null 2>&1
+    echo_debug "cfg" "save_runconf: $_conf_tmp --> $CONF_RUN"
 }
 
 # --- Kernel
