tlp-rdw: - lock events during suspend/hibernate cycle - lock events for 5 seconds after ifup processing tlp-functions: - encapsulate locking code for usb mode and rdw - extensive logging for locking code misc cleanup

diff --git a/tlp-functions b/tlp-functions
--- a/tlp-functions
+++ b/tlp-functions
@@ -13,6 +13,7 @@
 readonly TLPVER=0.3.5.904
 
 readonly CONFFILE=/etc/default/tlp
+readonly RUNDIR=/var/run/tlp
 
 readonly ACPWR=on_ac_power
 readonly ETHTOOL=ethtool
@@ -33,9 +34,12 @@ readonly I915D=/sys/module/i915/parameters
 readonly USBD=/sys/bus/usb/devices
 readonly USB_TIMEOUT=2
 readonly USB_TIMEOUT_MS=2000
-readonly USB_DONE=/var/run/tlp.usb-done
+readonly USB_DONE=usb_done
+
+readonly SUSPEND_IN_PROGRESS=suspend_in_progress
 
 readonly TPMODULES="thinkpad_acpi tp_smapi"
+
 
 # ----------------------------------------------------------------------------
 # Functions
@@ -122,6 +126,74 @@ echo_started_mode () { # $1: 0=ac mode, 1=battery mode
     fi
     
     return 0
+}
+
+set_run_flag () { # $1: flag name
+    local rc
+    
+    [ -d $RUNDIR ] || mkdir $RUNDIR
+
+    if [ -d $RUNDIR ]; then
+        touch $RUNDIR/$1
+        rc=$?
+        echo_debug "lock" "set_run_flag.touch: $1; rc=$rc"
+        
+        return $?
+    else
+        # mkdir failed
+        echo_debug "lock" "set_run_flag.mkdir_failed"
+        return 2
+    fi
+}
+
+reset_run_flag () { # $1: flag name
+    if [ -f $RUNDIR/$1 ]; then
+        rm $RUNDIR/$1
+        echo_debug "lock" "reset_run_flag.remove: $1"
+    else
+        echo_debug "lock" "reset_run_flag.not_found: $1"
+    fi
+    
+    return 0
+}
+
+check_run_flag () { # $1: flag name
+    local rc
+    
+    [ -f $RUNDIR/$1 ]
+    rc=$?
+    echo_debug "lock" "check_run_flag: $1; rc=$rc"
+    
+    return $rc
+}
+
+set_timed_lock () { # $1: lock id, $2: lock duration [s]
+    # create time stamp file $2 seconds in the future
+    set_run_flag ${1}_timed_lock_$(date +%s -d "+${2} seconds")
+}
+
+check_timed_lock () { # $1: lock id
+    local lockid=$1
+    local locktime
+    local time=$(date +%s)
+    
+    for lockfile in $RUNDIR/${lockid}_timed_lock_*; do
+        if [ -f $lockfile ]; then
+            locktime=${lockfile#${RUNDIR}/${lockid}_timed_lock_}
+            if [ $time -lt $locktime ]; then
+                # timestamp in the future -> we're locked
+                echo_debug "lock" "check_timed_lock.locked: $time, $locktime"
+                return 0
+            else
+                # obsolete timestamp -> remove it
+                rm $lockfile
+                echo_debug "lock" "check_timed_lock.remove_obsolete: ${lockfile#${RUNDIR}/}"
+            fi
+        fi
+    done
+    
+    echo_debug "lock" "check_timed_lock.not_locked: $time"
+    return 1
 }
 
 set_laptopmode () { # $1: 0=ac mode, 1=battery mode
@@ -732,7 +804,7 @@ enable_usb_suspend () { # $1: 0=silent/1=report result
     fi
     
     # Set "startup completion" flag for tlp-usb-udev
-    [ -f $USB_DONE ] || touch $USB_DONE
+    set_run_flag $USB_DONE
     
     return 0
 }
