Fix minor bugs reported by André Erdmann (Gentoo port) Remove logic for X_BT_DISABLE_ON_LOGIN

diff --git a/tlp-functions b/tlp-functions
--- a/tlp-functions
+++ b/tlp-functions
@@ -57,7 +57,7 @@ check_sysfs ()  { # $1: routine; $2: sysfs path
 
 check_root () { 
 	if [ "$(id -u)" != "0" ]; then
-		echo "Error: root privilege needed. Please call me with 'sudo'." 1>&2
+		echo "Error: root privilege needed." 1>&2
 		exit 1
 	fi
 }
