Move libs to /usr/share/tlp-pm
FHS states architecture independent "data" (i.e. scripts) belongs in /usr/share.

Remove /usr/lib64 stuff: once used in Fedora packaging (pm-utils put scripts into
/usr/lib64/pm-utils despite being architecture independent), this is no longer
necessary.

diff --git a/tlp-rdw-nm.in b/tlp-rdw-nm.in
--- a/tlp-rdw-nm.in
+++ b/tlp-rdw-nm.in
@@ -6,19 +6,19 @@
 # This software is licensed under the GPL v2 or later.
 
 # --- Constants
-readonly LIBDIRS="/usr/lib/tlp-pm /usr/lib64/tlp-pm @TLP_TLIB@"
+readonly LIBDIR="@TLP_TLIB@"
 readonly LIBS="tlp-functions tlp-rf-func"
 
 readonly RDW_NM_LOCK="rdw_nm"
 readonly RDW_NM_LOCKTIME=2
 
-# --- Locate and source libraries
-for libdir in $LIBDIRS; do [ -d $libdir ] && break; done
-[ -d $libdir ] || exit 0
-
+# --- Source libraries
 for lib in $LIBS; do
-    [ -f $libdir/$lib ] || exit 0
-    . $libdir/$lib
+    if [ ! -f $LIBDIR/$lib ]; then
+        echo "Error: missing function library \'$LIBDIR/$lib\'." 1>&2
+        exit 1
+    fi
+    . $LIBDIR/$lib
 done
 
 # --- MAIN
diff --git a/tlp-run-on.in b/tlp-run-on.in
--- a/tlp-run-on.in
+++ b/tlp-run-on.in
@@ -5,22 +5,16 @@
 # This software is licensed under the GPL v2 or later.
 
 # --- Constants
-readonly LIBDIRS="/usr/lib/tlp-pm /usr/lib64/tlp-pm @TLP_TLIB@"
+readonly LIBDIR="@TLP_TLIB@"
 readonly LIBS="tlp-functions"
 
-# --- Locate and source libraries
-for libdir in $LIBDIRS; do [ -d $libdir ] && break; done
-if [ ! -d $libdir ]; then
-    echo "Error: missing library directory ($LIBDIRS)." 1>&2
-    exit 1
-fi
-
+# --- Source libraries
 for lib in $LIBS; do
-    if [ ! -f $libdir/$lib ]; then
-        echo "Error: missing function library \'$libdir/$lib\'." 1>&2
+    if [ ! -f $LIBDIR/$lib ]; then
+        echo "Error: missing function library \'$LIBDIR/$lib\'." 1>&2
         exit 1
     fi
-    . $libdir/$lib
+    . $LIBDIR/$lib
 done
 
 # --- MAIN
