* Bugfixes    - tlp-stat: error checking get_ctrl_device, tlp-stat batinfo (mikar) * Features   - tlp fullcharge   - set_charge_thresholds on startup only, not on shutdown   - ext3/ext4 fs commit depending on MAX_LOST_WORK_SECS

diff --git a/tlp-functions b/tlp-functions
--- a/tlp-functions
+++ b/tlp-functions
@@ -3,7 +3,7 @@
 
 # ----------------------------------------------------------------------------
 # Definitions
-TLPVER=0.2.5
+TLPVER=0.2.6
 DEFAULT_FILE=/etc/default/tlp
 ACPWR=/usr/bin/on_ac_power
 ETHTOOL=/usr/sbin/ethtool
@@ -101,51 +101,56 @@ set_laptopmode () { # $1: 0=ac mode, 1=battery mode
 	return 0
 }
 
+set_extfs_commit () { # $1: commit
+	# remount ext3/4 filesystems with commit=age (from laptop-mode-tools)
+	local dev mtpoint fstype mopts d1 d2
+	
+	mount | while read dev d1 mtpoint d2 fstype mopts; do 
+		case $fstype in
+			ext[34]) 
+				mopts=${mopts#(}; mopts=${mopts%)}
+				mopts=${mopts%%,commit=*}
+				if [ -b $dev -a -d $mtpoint ]; then
+					mount $dev $mtpoint -o remount,$mopts,commit=$commit
+				fi
+				;;
+			
+			*)
+				;;
+		esac		
+	done
+	
+	return 0
+}
+
 set_dirty_parms () { # $1: 0=ac mode, 1=battery mode
 	# Some code adapted from laptop-mode-tools
-	local age
+	local commit age
 	
 	check_sysfs "set_dirty_parms" "/proc/sys/vm"
 	
 	if [ "$1" = "1" ]; then
-		if [ "${MAX_LOST_WORK_SECS_ON_BAT:-undef}" != "undef" ]; then
-			age=$(($MAX_LOST_WORK_SECS_ON_BAT * 100))
-		else
-			age=1500
-		fi
-		echo_debug "pm" "set_dirty_parms($1): $age"
-		
-		echo $age > /proc/sys/vm/dirty_writeback_centisecs
-		echo $age > /proc/sys/vm/dirty_expire_centisecs
-
-		if [ -d /proc/sys/fs/xfs ]; then
-			echo $age > /proc/sys/fs/xfs/age_buffer_centisecs
-			echo $age > /proc/sys/fs/xfs/xfssyncd_centisecs
-			echo 3000 > /proc/sys/fs/xfs/xfsbufd_centisecs
-		fi
-
-		echo 60 > /proc/sys/vm/dirty_ratio
-		echo 1 > /proc/sys/vm/dirty_background_ratio
+		commit=${MAX_LOST_WORK_SECS_ON_BAT:-15}
 	else
-		if [ "${MAX_LOST_WORK_SECS_ON_AC:-undef}" != "undef" ]; then
-			age=$(($MAX_LOST_WORK_SECS_ON_AC * 100))
-		else
-			age=500
-		fi
-		echo_debug "pm" "set_dirty_parms($1): $age"
-		
-		echo $age > /proc/sys/vm/dirty_writeback_centisecs
-		echo $age > /proc/sys/vm/dirty_expire_centisecs
-		
-		if [ -d /proc/sys/fs/xfs ]; then
-			echo $age > /proc/sys/fs/xfs/age_buffer_centisecs
-			echo $age > /proc/sys/fs/xfs/xfssyncd_centisecs
-			echo 3000 > /proc/sys/fs/xfs/xfsbufd_centisecs
-		fi
-
-		echo 40 > /proc/sys/vm/dirty_ratio
-		echo 10 > /proc/sys/vm/dirty_background_ratio
+		commit=${MAX_LOST_WORK_SECS_ON_AC:-5}
 	fi
+	age=$(($commit * 100))
+			
+	echo_debug "pm" "set_dirty_parms($1): $commit $age"
+		
+	echo $age > /proc/sys/vm/dirty_writeback_centisecs
+	echo $age > /proc/sys/vm/dirty_expire_centisecs
+		
+	set_extfs_commit $commit
+		
+	if [ -d /proc/sys/fs/xfs ]; then
+		echo $age > /proc/sys/fs/xfs/age_buffer_centisecs
+		echo $age > /proc/sys/fs/xfs/xfssyncd_centisecs
+		echo 3000 > /proc/sys/fs/xfs/xfsbufd_centisecs
+	fi
+
+	echo 60 > /proc/sys/vm/dirty_ratio
+	echo 1 > /proc/sys/vm/dirty_background_ratio
 	
 	return 0
 }
@@ -217,9 +222,8 @@ set_disk_apm_level () { # $1: 0=ac mode, 1=battery mode
 } 
 
 set_sata_link_power () { # $1: 0=ac mode, 1=battery mode
-	local i
-	local pwr
-	
+	local i pwr
+		
 	if [ "$1" = "1" ]; then
 		[ "${SATA_LINKPWR_ON_BAT:-undef}" = "undef" ] && return 0
 		pwr=$SATA_LINKPWR_ON_BAT
@@ -245,8 +249,7 @@ get_wifi_ifaces () { # retval: $WIFACES
 }
 
 set_wifi_power_mode () { # $1: 0=ac mode, 1=battery mode; $2 iface
-	local pwr
-	local iface
+	local pwr iface
 	
 	if [ "$1" = "1" ]; then
 		pwr=${WIFI_PWR_ON_BAT:-0}
@@ -341,26 +344,122 @@ do_threshold () { # $1: treshold file, $2: new value
 }
 
 set_charge_thresholds () {
-	[ -d /sys/devices/platform/smapi ] || return 0
-	if [ "$(cat /sys/devices/platform/smapi/BAT0/installed)" = "1" ]; then
+	[ -d $SMAPIDIR ] || return 0
+	echo_debug "pm" "set_charge_thresholds"
+	
+	if [ -d $SMAPIDIR/BAT0 ] && [ "$(cat $SMAPIDIR/BAT0/installed)" = "1" ]; then
 		echo_debug "pm" "set_charge_thresholds: BAT0 $START_CHARGE_THRESH_BAT0 $STOP_CHARGE_THRESH_BAT0"
-		do_threshold /sys/devices/platform/smapi/BAT0/start_charge_thresh "$START_CHARGE_THRESH_BAT0"
-		do_threshold /sys/devices/platform/smapi/BAT0/stop_charge_thresh "$STOP_CHARGE_THRESH_BAT0"
+		do_threshold $SMAPIDIR/BAT0/start_charge_thresh "$START_CHARGE_THRESH_BAT0"
+		do_threshold $SMAPIDIR/BAT0/stop_charge_thresh "$STOP_CHARGE_THRESH_BAT0"
 	fi
-	if [ "$(cat /sys/devices/platform/smapi/BAT1/installed)" = "1" ]; then
+	if [ -d $SMAPIDIR/BAT1 ] &&  [ "$(cat $SMAPIDIR/BAT1/installed)" = "1" ]; then
 		echo_debug "pm" "set_charge_thresholds: BAT1 $START_CHARGE_THRESH_BAT1 $STOP_CHARGE_THRESH_BAT1"
-		do_threshold /sys/devices/platform/smapi/BAT1/start_charge_thresh "$START_CHARGE_THRESH_BAT1"
-		do_threshold /sys/devices/platform/smapi/BAT1/stop_charge_thresh "$STOP_CHARGE_THRESH_BAT1"
+		do_threshold $SMAPIDIR/BAT1/start_charge_thresh "$START_CHARGE_THRESH_BAT1"
+		do_threshold $SMAPIDIR/BAT1/stop_charge_thresh "$STOP_CHARGE_THRESH_BAT1"
 	fi
 	
 	return 0
 }
 
+cancel_discharge () { # called from trap
+	echo 0 > $bdir/force_discharge
+	echo "\nDischarging of battery $bat cancelled."
+	echo_debug "pm" "discharge_battery.cancelled: $bat"
+	exit 0
+}
+
+discharge_battery () { # $1: battery
+	local bat bdir
+	
+	if [ ! -d $SMAPIDIR ]; then
+		echo_debug "pm" "discharge_battery.nosmapi: $bat"
+		echo "Error: ThinkPad battery functions not available (missing tp_smapi kernel module)."
+		return 1
+	fi
+	
+	if ! get_power_state ; then
+		echo_debug "pm" "discharge_battery.noacpower: $bat"
+		echo "Error: discharge is possible on ac power only."
+		return 1
+	fi	
+
+	bat=$1
+	bat=${bat:=BAT0} # default is BAT0
+	bat=$(echo $bat | tr "[:lower:]" "[:upper:]")
+	bdir=$SMAPIDIR/$bat
+	
+	if [ ! -f $bdir/installed ] || [ "$(cat $bdir/installed)" = "0" ]; then
+		echo_debug "pm" "discharge_battery.notpresent: $bat"
+		echo "Error: battery $bat not present."
+		return 1
+	fi
+		
+	echo 1 > $bdir/force_discharge
+	trap cancel_discharge INT
+	
+	while [ "$(cat $bdir/force_discharge)" = "0" ]; do :; done
+	echo_debug "pm" "discharge_battery.running: $bat"
+
+	while [ "$(cat $bdir/force_discharge)" = "1" ]; do
+		clear
+		echo "Currently discharging battery $bat:"
+		echo "voltage            = $(cat $bdir/voltage) [mV]"
+		echo "remaining percent  = $(cat $bdir/remaining_percent) [%]"
+		echo "remaining capacity = $(cat $bdir/remaining_capacity) [mWh]"
+		echo "remaining time     = $(cat $bdir/remaining_running_time_now) [min]"
+		echo "Press Ctrl+C to cancel."
+		sleep 2
+	done
+
+	echo
+	echo "Done: battery $bat was completely discharged."
+	echo_debug "pm" "discharge_battery.complete: $bat"
+	return 0
+}
+
+fullcharge_battery () { # $1: battery
+	local bat bdir
+	
+	if [ ! -d $SMAPIDIR ]; then
+		echo_debug "pm" "fullcharge_battery.nosmapi: $bat"
+		echo "Error: ThinkPad battery functions not available (missing tp_smapi kernel module)."
+		return 1
+	fi
+
+	if ! get_power_state ; then
+		echo_debug "pm" "discharge_battery.noacpower: $bat"
+		echo "Error: fullcharge is possible on ac power only."
+		return 1
+	fi	
+
+	bat=$1
+	bat=${bat:=BAT0} # default is BAT0
+	bat=$(echo $bat | tr "[:lower:]" "[:upper:]")
+	bdir=$SMAPIDIR/$bat
+	
+	if [ ! -f $bdir/installed ] || [ "$(cat $bdir/installed)" = "0" ]; then
+		echo_debug "pm" "fullcharge_battery.notpresent: $bat"
+		echo "Error: battery $bat not present."
+		return 1
+	fi
+
+	# set thresholds to max charge
+	do_threshold $bdir/start_charge_thresh "96"
+	do_threshold $bdir/stop_charge_thresh "100"
+	
+	# trigger charging via discharge
+	echo 1 > $bdir/force_discharge
+	sleep 2
+	echo 0 > $bdir/force_discharge
+	
+	echo "Charging of battery $bat was initiated (thresholds temporarily set to 96/100)."
+	echo_debug "pm" "fullcharge_battery.initiated: $bat"
+	return 0
+}
+
 poweroff_drivebay () { # $1: 0=conditional+quiet mode, 1=force+verbose mode
 	# Some code adapted from http://www.thinkwiki.org/wiki/How_to_hotswap_UltraBay_devices
-	local dock
-	local optdrv
-	local syspath
+	local dock optdrv syspath
 	
 	# Run only if either explicitly enabled or forced 
 	[ "$BAY_POWEROFF_ON_BAT" = "1" ] || [ "$1" = "1" ] || return 0
@@ -410,54 +509,3 @@ poweroff_drivebay () { # $1: 0=conditional+quiet mode, 1=force+verbose mode
 	
 	return 0
 }
-
-cancel_discharge () { # called from trap
-	echo 0 > $bdir/force_discharge
-	echo "\nDischarging of battery $bat cancelled."
-	echo_debug "pm" "discharge_battery.cancelled: $bat"
-	exit 0
-}
-
-discharge_battery () { # $1: battery
-	local bat
-	local bdir
-	
-	if [ ! -d $SMAPIDIR ]; then
-		echo "Error: ThinkPad battery functions not available (missing tp_smapi kernel module)."
-		return 1
-	fi
-
-	bat=$1
-	bat=${bat:=BAT0} # default is BAT0
-	bat=$(echo $bat | tr "[:lower:]" "[:upper:]")
-	bdir=$SMAPIDIR/$bat
-	
-	if [ ! -f $bdir/installed ] || [ "$(cat $bdir/installed)" = "0" ]; then
-		echo_debug "pm" "discharge_battery.notpresent: $bat"
-		echo "Error: battery $bat not present."
-		return 1
-	fi
-		
-	echo 1 > $bdir/force_discharge
-	trap cancel_discharge INT
-	
-	while [ "$(cat $bdir/force_discharge)" = "0" ]; do :; done
-	echo_debug "pm" "discharge_battery.running: $bat"
-
-	while [ "$(cat $bdir/force_discharge)" = "1" ]; do
-		clear
-		echo "Currently discharging battery $bat:"
-		echo "voltage            = $(cat $bdir/voltage) [mV]"
-		echo "remaining percent  = $(cat $bdir/remaining_percent) [%]"
-		echo "remaining capacity = $(cat $bdir/remaining_capacity) [mWh]"
-		echo "remaining time     = $(cat $bdir/remaining_running_time_now) [min]"
-		echo "Press Ctrl+C to cancel."
-		sleep 2
-	done
-
-	echo
-	echo "Done: battery $bat was completely discharged."
-	echo_debug "pm" "discharge_battery.complete: $bat"
-	return 0
-}
-
