ipw2200: enable/disable via sysfs, set_power disabled check root priv

diff --git a/tlp-functions b/tlp-functions
--- a/tlp-functions
+++ b/tlp-functions
@@ -19,14 +19,14 @@ OPTDRV=/dev/sr0
 # Functions
 check_root () {
 	if [ "$(id -u)" != "0" ]; then
-		echo "Error: you are not root; please call me with 'sudo'." 2>&1
+		echo "Error: root privilege needed. Please call me with 'sudo'." 1>&2
 		exit 1
 	fi
 }
 
 check_tlp_enabled () {
 	if [ ! "$TLP_ENABLE" = "1" ]; then
-		echo "Error: tlp power save is disabled; set TLP_ENABLE=1 in /etc/default/tlp."
+		echo "Error: tlp power save is disabled; set TLP_ENABLE=1 in /etc/default/tlp." 1>&2
 		return 1
 	else
 		return 0
@@ -36,9 +36,9 @@ check_tlp_enabled () {
 check_laptop_mode_tools () {
 	[ -f /etc/default/acpi-support ] && . /etc/default/acpi-support
 	if [ "$ENABLE_LAPTOP_MODE" = "true" -o -f /var/run/laptop-mode-tools/enabled ]; then
-		echo "Error: tlp power save is disabled because laptop-mode-tools is active."
-		echo "       Set ENABLE_LAPTOP_MODE=false in /etc/default/acpi-support."
-		echo 
+		echo "Error: tlp power save is disabled because laptop-mode-tools is active." 1>&2
+		echo "       Set ENABLE_LAPTOP_MODE=false in /etc/default/acpi-support." 1>&2
+		echo 1>&2
 		return 1
 	else
 		return 0
@@ -173,11 +173,11 @@ set_wifi_power_mode () { # $1: 0=ac mode, 1=battery mode
 	fi
 
 	# Intel 2200bg
-	if [ -d /sys/bus/pci/drivers/ipw2200 ]; then
-		for i in /sys/bus/pci/drivers/ipw2200/*/net/* ; do
-			[ -a $i ] && $IWPRIV ${i##/*/} set_power $pwr
-		done
-	fi
+	#if [ -d /sys/bus/pci/drivers/ipw2200 ]; then
+	#	for i in /sys/bus/pci/drivers/ipw2200/*/net/* ; do
+	#		[ -e $i ] && $IWPRIV ${i##/*/} set_power $pwr > /dev/null 2>&1
+	#	done
+	#fi
 }
 
 disable_wake_on_lan () {  
diff --git a/tlp-rf-func b/tlp-rf-func
--- a/tlp-rf-func
+++ b/tlp-rf-func
@@ -4,6 +4,7 @@
 # ----------------------------------------------------------------------------
 # Definitions
 RFKILL="/sbin/rfkill"
+RMMOD="/sbin/rmmod"
 
 # ----------------------------------------------------------------------------
 # Functions
@@ -30,49 +31,89 @@ get_ctrl_device () {
 			;;
         
         *)
-			echo "Error: no such device \"$1\""
+			echo "Error: no such device \"$1\"" 1>&2
 			devc=""
 			;;
 	esac
 }
 
+check2200 () {
+	is2200="0"
+	if [ $1 = "wifi" ]; then
+		devc=""
+		if [ -d /sys/bus/pci/drivers/ipw2200 ]; then
+			for i in /sys/bus/pci/drivers/ipw2200/*/rf_kill ; do
+				devc=$i
+			done
+			[ -n "$devc" ] && is2200="1"
+		fi
+	fi
+}
+
+err_no_root_priv () {
+	echo "Error: root privilege needed. Please call me with sudo." 1>&2
+}
+
 device_on () { 
-	if [ -x $RFKILL ]; then
+	check2200 $1
+	if [ $is2200 = "1" ]; then
+		if [ "$(id -u)" = "0" ]; then
+			echo 0 > $devc
+		else
+			err_no_root_priv
+		fi
+	elif [ -x $RFKILL ]; then
 		$RFKILL unblock $1
 	else
-		get_ctrl_device $1
-		if [ -n $devc ]; then
-			echo -n 1 > $devc
+		if [ "$(id -u)" = "0" ]; then
+			get_ctrl_device $1
+			if [ -n $devc ]; then
+				echo -n 1 > $devc
+			fi
+		else
+			err_no_root_priv
 		fi
 	fi
 }
 
 device_off () {
-	if [ -x $RFKILL ]; then
-		case $1 in
-			bluetooth)
-				btidx=$($RFKILL list | grep "hci" | cut -f1 -d:)
-				[ -n "$btidx" ] && $RFKILL block $btidx
-				$RFKILL block $1
-				;;
-			*)
-				$RFKILL block $1
-				;;
-		esac
+	check2200 $1
+	if [ $is2200 = "1" ]; then
+		if [ "$(id -u)" = "0" ]; then
+			echo 1 > $devc
+		else
+			err_no_root_priv
+		fi
+	elif [ -x $RFKILL ]; then
+		$RFKILL block $1
 	else
-		get_ctrl_device $1
-		if [ -n $devc ]; then
-			echo -n 0 > $devc
+		if [ "$(id -u)" = "0" ]; then
+			get_ctrl_device $1
+			if [ -n $devc ]; then
+				echo -n 0 > $devc
+			fi
+		else
+			err_no_root_priv
 		fi
 	fi
 }
 
 device_state () {
-	get_ctrl_device $1
-	if [ -z $devc ]; then
-		state=254
-	else
-		state=$(cat $devc)
+	check2200 $1
+	if [ $is2200 = "1" ]; then
+		if [ -z $devc ]; then
+			state=254
+		else
+			state=$(cat $devc)
+			state=$((! $state))
+		fi
+	else 
+		get_ctrl_device $1
+		if [ -z $devc ]; then
+			state=254
+		else
+			state=$(cat $devc)
+		fi
 	fi
 	
 	case $1 in
