tlp-rf-func: code refactored

diff --git a/tlp-rf-func b/tlp-rf-func
--- a/tlp-rf-func
+++ b/tlp-rf-func
@@ -7,58 +7,55 @@ RFKILL="/sbin/rfkill"
 
 # ----------------------------------------------------------------------------
 # Functions
-get_ctrl_device () { # $1: rftype; retval $devc
+get_devc () { # $1: rftype; retval $devc
 	local i
-	
-	check_sysfs "get_ctrl_device" "/sys/class/rfkill"
+    
+    check_sysfs "get_devc" "/sys/class/rfkill"
+
+    devc=""
+    devs=254
+    is2200="0"
 	
 	case $1 in
 		wwan|bluetooth)
 			for i in /sys/class/rfkill/rfkill* ; do
 				if [ -f $i/type  ] && [ "$(cat $i/type)" = "$1" ]; then 
 					devc="$i/state"
-					echo_debug "rf" "get_ctrl_device($1) = $devc"
-					return
+					echo_debug "rf" "get_devc($1) = $devc"
+					return 0
 				fi
 			done
-			devc=""
 			;;
 
 		wifi)
-			for i in /sys/class/rfkill/rfkill* ; do
-				if [ -f $i/type  ] && [ "$(cat $i/type)" = "wlan" ]; then 
-					devc="$i/state"
-					echo_debug "rf" "get_ctrl_device($1) = $devc"
-					return
-				fi
-			done
-			devc=""
+            if [ -d /sys/bus/pci/drivers/ipw2200 ]; then
+                for i in /sys/bus/pci/drivers/ipw2200/*/rf_kill ; do
+                    if [ -f $i ]; then
+                        devc="$i"
+                        is2200="1"
+                        echo_debug "rf" "get_devc($1) = $devc [ipw2200]"
+                        return 0
+                    fi
+                done
+            else
+                for i in /sys/class/rfkill/rfkill* ; do
+                    if [ -f $i/type  ] && [ "$(cat $i/type)" = "wlan" ]; then 
+                        devc="$i/state"
+                        echo_debug "rf" "get_devc($1) = $devc"
+                        return 0
+                    fi
+                done
+			fi
 			;;
         
         *)
-			echo "Error: no such device \"$1\"" 1>&2
-			devc=""
-			echo_debug "rf" "get_ctrl_device($1) = none"
+			echo "Error: unknown device type \"$1\"" 1>&2
+			echo_debug "rf" "get_devc($1).unknown_type"
+            return 0
 			;;
 	esac
-	
-	return 0
-}
-
-check2200 () { # $1: rftype; retval $devc, $is2200
-	local i
-	
-	is2200="0"
-	if [ $1 = "wifi" ]; then
-		devc=""
-		if [ -d /sys/bus/pci/drivers/ipw2200 ]; then
-			for i in /sys/bus/pci/drivers/ipw2200/*/rf_kill ; do
-				[ -f $i ] && devc=$i
-			done
-			[ -n "$devc" ] && is2200="1"
-		fi
-	fi
-	echo_debug "rf" "check2200($1) = $is2200 $devc"
+    
+    echo_debug "rf" "get_devc($1).not_present"
 	
 	return 0
 }
@@ -69,36 +66,38 @@ err_no_root_priv () {
 	return 0
 }
 
-device_state () { # $1: rftype; retval $devs: 0=off/1=on
-	devs=254
-	check2200 $1
-	if [ "$is2200" = "1" ]; then
-		if [ -n "$devc" ]; then
-			devs=$(cat $devc)
+get_devs () { # $1: rftype; retval $devs: 0=off/1=on
+	if [ -n "$devc" ]; then
+        devs=$(cat $devc)
+        if [ "$is2200" = "1" ]; then
 			devs=$((! $devs))
 		fi
-	else 
-		get_ctrl_device $1	
-		if [ -n "$devc" ]; then
-			devs=$(cat $devc)
-		fi
-	fi
-	
-	echo_debug "rf" "device_state($1) = $devs"
+    fi
+
+	echo_debug "rf" "get_devs($1) = $devs"
 	
 	return 0
 }
 
+device_state () { # $1: rftype 
+	echo_debug "rf" "device_state($1)"
+    
+    get_devc $1
+    get_devs $1	
+}
+
+
 device_on () { # $1: rftype 
 	echo_debug "rf" "device_on($1)"
-	device_state $1
+    
+    get_devc $1
+    [ -z "$devc" ] && return 0
+    get_devs $1	
 	
 	if [ "$is2200" = "1" ]; then
 		if [ "$(id -u)" = "0" ]; then
-			if [ -n "$devc" ]; then
-				echo_debug "rf" "device_on($1).ipw2200"
-				echo -n 0 > $devc
-			fi
+			echo_debug "rf" "device_on($1).ipw2200"
+			echo -n 0 > $devc
 		else
 			err_no_root_priv
 		fi
@@ -107,28 +106,29 @@ device_on () { # $1: rftype
 		$RFKILL unblock $1
 	else
 		if [ "$(id -u)" = "0" ]; then
-			if [ -n "$devc" ]; then
-				echo_debug "rf" "device_on($1).devc"
-				echo -n 1 > $devc
-			fi
+			echo_debug "rf" "device_on($1).devc"
+			echo -n 1 > $devc
 		else
 			err_no_root_priv
 		fi
 	fi
+    
+    get_devs $1
 	
 	return 0
 }
 
 device_off () { # $1: rftype
 	echo_debug "rf" "device_off($1)"
-	device_state $1
+    
+    get_devc $1
+    [ -z "$devc" ] && return 0
+    get_devs $1	
 	
 	if [ "$is2200" = "1" ]; then
 		if [ "$(id -u)" = "0" ]; then
-			if [ -n "$devc" ]; then
-				echo_debug "rf" "device_off($1).ipw2200"
-				echo -n 1 > $devc
-			fi
+			echo_debug "rf" "device_off($1).ipw2200"
+			echo -n 1 > $devc
 		else
 			err_no_root_priv
 		fi
@@ -137,32 +137,33 @@ device_off () { # $1: rftype
 		$RFKILL block $1
 	else
 		if [ "$(id -u)" = "0" ]; then
-			if [ -n "$devc" ]; then
-				echo_debug "rf" "device_off($1).devc"
-				echo -n 0 > $devc
-			fi
+			echo_debug "rf" "device_off($1).devc"
+			echo -n 0 > $devc
 		else
 			err_no_root_priv
 		fi
 	fi
-	
+
+    get_devs $1
+		
 	return 0
 }
 
 device_toggle () { # $1: rftype
 	echo_debug "rf" "device_toggle($1)"
-	device_state $1
+
+    get_devc $1
+    [ -z "$devc" ] && return 0
+    get_devs $1	
 			
 	if [ "$is2200" = "1" ]; then
 		if [ "$(id -u)" = "0" ]; then
-			if [ -n "$devc" ]; then
-				echo_debug "rf" "device_toggle($1).ipw2200"
-				case $devs in
-					0) echo -n 0 > $devc ;;
-					1) echo -n 1 > $devc ;;
-					*) ;;
-				esac
-			fi
+			echo_debug "rf" "device_toggle($1).ipw2200"
+			case $devs in
+				0) echo -n 0 > $devc ;;
+				1) echo -n 1 > $devc ;;
+				*) ;;
+			esac
 		else
 			err_no_root_priv
 		fi
@@ -175,25 +176,23 @@ device_toggle () { # $1: rftype
 		esac
 	else
 		if [ "$(id -u)" = "0" ]; then
-			if [ -n "$devc" ]; then
-				echo_debug "rf" "device_toggle($1).devc"
-				case $devs in
-					0) echo -n 1 > $devc ;;
-					1) echo -n 0 > $devc ;;
-					*) ;;
-				esac
-			fi
+			echo_debug "rf" "device_toggle($1).devc"
+			case $devs in
+				0) echo -n 1 > $devc ;;
+				1) echo -n 0 > $devc ;;
+				*) ;;
+			esac
 		else
 			err_no_root_priv
 		fi
 	fi
+    
+    get_devs $1
 	
 	return 0
 }
 
-echo_device_state () { # $1: rftype
-	device_state $1
-		
+echo_device_state () { # $1: rftype, $2: state
 	case $1 in
 		bluetooth)
 			devstr="bluetooth"
@@ -212,7 +211,7 @@ echo_device_state () { # $1: rftype
 			;;
 	esac
 	
-	case $devs in
+	case $2 in
 		0) 
 			echo "$devstr = off (software)"
 			;;
