Fix readable_sysf() rc.

diff --git a/tlp-func-base.in b/tlp-func-base.in
--- a/tlp-func-base.in
+++ b/tlp-func-base.in
@@ -94,14 +94,19 @@ check_sysfs () { # debug: check if sysfile exists -- $1: routine; $2: sysfs path
 }
 
 read_sysf () { # read and echo contents of sysfile
-    # echo default if file is non-existent or read fails
+    # return 1 and echo default if read fails
     # $1: sysfile, $2: default; rc: 0=ok/1=error
-    cat "$1" 2> /dev/null || printf "%s" "$2"
+    if ! cat "$1" 2> /dev/null; then
+        printf "%s" "$2"
+        return 1
+    else
+        return 0
+    fi
 }
 
 readable_sysf () { # check if file is actually readable -- $1: file
-    # rc: 0=readable/1=error
-    read_sysf $1 > /dev/null
+    # rc: 0=readable/1=read error
+    cat "$1" > /dev/null 2>&1
 }
 
 read_sysval () { # read and echo contents of sysfile
