Feature: force batt discharge

diff --git a/tlp-functions b/tlp-functions
--- a/tlp-functions
+++ b/tlp-functions
@@ -14,6 +14,7 @@ UDEVADM=/sbin/udevadm
 PERL=/usr/bin/perl
 SMAPI=tp_smapi
 CDROM=/dev/cdrom
+SMAPIDIR=/sys/devices/platform/smapi
 
 # ----------------------------------------------------------------------------
 # Functions
@@ -299,4 +300,46 @@ poweroff_drivebay () { # $1: 0=conditional+quiet mode, 1=force+verbose mode
 	return 0
 }
 
+cancel_discharge () { # called from trap
+	echo 0 > $bdir/force_discharge
+	echo "\nDischarging of battery $bat cancelled."
+	exit 0
+}
+
+discharge_battery () { # $1: battery
+	if [ ! -d $SMAPIDIR ]; then
+		echo "Error: ThinkPad battery functions not available (missing tp_smapi kernel module)."
+		return 1
+	fi
+
+	bat=$1
+	bat=${bat:=BAT0} # default is BAT0
+	bat=$(echo $bat | tr "[:lower:]" "[:upper:]")
+	bdir=$SMAPIDIR/$bat
+	
+	if [ ! -f $bdir/installed ] || [ "$(cat $bdir/installed)" = "0" ]; then
+		echo "Error: battery $bat not present."
+		return 1
+	fi
+		
+	echo 1 > $bdir/force_discharge
+	trap cancel_discharge INT
+	
+	while [ "$(cat $bdir/force_discharge)" = "0" ]; do :; done
+
+	while [ "$(cat $bdir/force_discharge)" = "1" ]; do
+		clear
+		echo "Currently discharging battery $bat:"
+		echo "voltage            = $(cat $bdir/voltage) [mV]"
+		echo "remaining percent  = $(cat $bdir/remaining_percent) [%]"
+		echo "remaining capacity = $(cat $bdir/remaining_capacity) [mWh]"
+		echo "remaining time     = $(cat $bdir/remaining_running_time_now) [min]"
+		echo "Press Ctrl+C to cancel."
+		sleep 2
+	done
+
+	echo
+	echo "Done: battery $bat was completely discharged."
+	return 0
+}
 
