Make USB device udev event processing more robust * run in a detached subshell to avoid blocking udev * wait 2s for subdevices to populate for proper black/whitelist detection

diff --git a/tlp-usb-udev b/tlp-usb-udev
--- a/tlp-usb-udev
+++ b/tlp-usb-udev
@@ -4,6 +4,9 @@
 # Copyright (c) 2014 Thomas Koch <linrunner at gmx.net>
 # This software is licensed under the GPL v2 or later.
 
+# Remark: the calling udev rule is triggered for "base" devices only,
+#         not for the corresponding subdevices. 
+
 # --- Constants
 readonly LOGGER=logger
 
@@ -40,11 +43,11 @@ echo_debug () { # $1: tag; $2: msg; echo debug msg if tag matches
 
 # --- MAIN
 
-# Read config
+# read config
 [ -f $CONFFILE ] || exit 0
 . $CONFFILE
 
-# Exit if TLP or autosuspend disabled
+# exit if TLP or autosuspend disabled
 [ "$TLP_ENABLE" = "1" ] && [ "$USB_AUTOSUSPEND" = "1" ] || exit 0
 
 # USB autosuspend has two principal operation modes:
@@ -58,96 +61,96 @@ echo_debug () { # $1: tag; $2: msg; echo debug msg if tag matches
 # Mode 2 (default):
 # - Everything - including system startup, but not shutdown - is handled by this udev script
 
-# Do exit if mode 1 and no startup completion flag
+# do exit if mode 1 and no startup completion flag
 [ "$X_TLP_USB_MODE" = "1" ] && [ ! -f $RUNDIR/$USB_DONE ] && exit 0
 
-# Get args
+# get args
 usbdev=/sys$1
 exc=""
 
-# Handle device
+# handle device
 if [ -f $usbdev/power/autosuspend ] || [ -f $usbdev/power/autosuspend_delay_ms ]; then
     # device is autosuspendable
 
-    # wait for sysfs to settle
-    sleep 0.5
+    ( # run remainder in a detached subshell to avoid blocking udev
 
-    # initialize driver blacklist from settings
-    drv_bl=${USB_DRIVER_BLACKLIST:-$DEFAULT_USB_DRIVER_BLACKLIST}
+        # initialize driver blacklist from settings
+        drv_bl=${USB_DRIVER_BLACKLIST:-$DEFAULT_USB_DRIVER_BLACKLIST}
 
-    # add wwan driver blacklist if enabled
-    USB_BLACKLIST_WWAN=${USB_BLACKLIST_WWAN:-1} # default is exclude
+        # add wwan driver blacklist if enabled
+        USB_BLACKLIST_WWAN=${USB_BLACKLIST_WWAN:-1} # default is exclude
 
-    if [ $USB_BLACKLIST_WWAN = "1" ]; then
-        drv_bl="$drv_bl $USB_WWAN_DRIVERS"
-    fi
+        if [ $USB_BLACKLIST_WWAN = "1" ]; then
+            drv_bl="$drv_bl $USB_WWAN_DRIVERS"
+        fi
 
-    # check subdevices for blacklisted drivers
-    for subdev in $usbdev/*:*; do
-        if [ -h $subdev/driver ]; then
-            # Get driver name from device symlink
-            drv=$(readlink $subdev/driver)
-            drv=${drv##*/}
+        # wait for subdevices to populate via parallel udev events (not handled here)
+        sleep 2.0
 
-            # Check against driver blacklist
+        # check subdevices for blacklisted drivers
+        for subdev in $usbdev/*:*; do
+            # get driver name from subdev uevent file
+            drv=$(sed -rn 's/DRIVER=(.*)/\1/p' $subdev/uevent)
+
+            # check against driver blacklist
             if wordinlist "$drv" "$drv_bl"; then
-                # Driver is blacklisted
+                # driver is blacklisted
                 exc="_drv_black"
                 break
             fi
-        fi
-    done
+        done
 
-    # apply autosuspend
-    ctrlf="control"
-    autof="autosuspend_delay_ms"
-    usbid="$(cat $usbdev/idVendor):$(cat $usbdev/idProduct)"
-    busdev="Bus $(cat $usbdev/busnum) Dev $(cat $usbdev/devnum)"
+        # apply autosuspend
+        ctrlf="control"
+        autof="autosuspend_delay_ms"
+        usbid="$(cat $usbdev/idVendor):$(cat $usbdev/idProduct)"
+        busdev="Bus $(cat $usbdev/busnum) Dev $(cat $usbdev/devnum)"
 
-    control="auto"
-    if [ -n "$exc" ]; then
-        # driver or wwan blacklist device
-        if wordinlist "$usbid" "$USB_WHITELIST"; then
-            exc="_dev_white"
-        else
+        control="auto"
+        if [ -n "$exc" ]; then
+            # driver or wwan blacklisted device
+            if wordinlist "$usbid" "$USB_WHITELIST"; then
+                exc="_dev_white"
+            else
+                control="on"
+            fi
+        elif wordinlist "$usbid" "$USB_BLACKLIST"; then
+            # blacklisted device
             control="on"
+            exc="_dev_black"
         fi
-    elif wordinlist "$usbid" "$USB_BLACKLIST"; then
-        # blacklisted device
-        control="on"
-        exc="_dev_black"
-    fi
 
-    if [ -f $usbdev/power/control ]; then
-        echo "$control" > $usbdev/power/control
-    else
-        # level is deprecated
-        echo "$control" > $usbdev/power/level
-        ctrlf="level"
-    fi
+        if [ -f $usbdev/power/control ]; then
+            echo "$control" > $usbdev/power/control
+        else
+            # level is deprecated
+            echo "$control" > $usbdev/power/level
+            ctrlf="level"
+        fi
 
-    if [ "$X_TLP_USB_SET_AUTOSUSPEND_DELAY" = "1" ]; then
-        # Set autosuspend_delay
-        if [ -f $usbdev/power/autosuspend_delay_ms ]; then
-            echo $USB_TIMEOUT_MS > $usbdev/power/autosuspend_delay_ms 2> /dev/null
-            if [ $? != 0 ]; then
-                # openSUSE 11.4/2.6.37: writing to autosuspend_delay_ms fails -> fallback to autosuspend
-                echo_debug "usb" "udev_usb.autosuspend_delay_ms_not_writable: $busdev ID $usbid $usbdev"
+        if [ "$X_TLP_USB_SET_AUTOSUSPEND_DELAY" = "1" ]; then
+            # set autosuspend_delay
+            if [ -f $usbdev/power/autosuspend_delay_ms ]; then
+                echo $USB_TIMEOUT_MS > $usbdev/power/autosuspend_delay_ms 2> /dev/null
+                if [ $? != 0 ]; then
+                    # openSUSE 11.4/2.6.37: writing to autosuspend_delay_ms fails -> fallback to autosuspend
+                    echo_debug "usb" "udev_usb.autosuspend_delay_ms_not_writable: $busdev ID $usbid $usbdev"
+                    echo $USB_TIMEOUT > $usbdev/power/autosuspend
+                    autof="autosuspend"
+                fi
+            else
+                # autosuspend is deprecated
                 echo $USB_TIMEOUT > $usbdev/power/autosuspend
                 autof="autosuspend"
             fi
+            echo_debug "usb" "udev_usb.$control$exc: $busdev ID $usbid $usbdev [$ctrlf $autof]"
         else
-            # autosuspend is deprecated
-            echo $USB_TIMEOUT > $usbdev/power/autosuspend
-            autof="autosuspend"
+            # default: do not change autosuspend_delay, i.e. keep kernel default setting
+            echo_debug "usb" "udev_usb.$control$exc: $busdev ID $usbid $usbdev [$ctrlf]"
         fi
-        echo_debug "usb" "udev_usb.$control$exc: $busdev ID $usbid $usbdev [$ctrlf $autof]"
-    else
-        # Default: do not change autosuspend_delay, i.e. keep kernel default setting
-        echo_debug "usb" "udev_usb.$control$exc: $busdev ID $usbid $usbdev [$ctrlf]"
-    fi
+
+        exit 0
+    ) &
 fi
 
 exit 0
-
-
