Imported Upstream version 0.9

diff --git a/tlp-rdw-nm.in b/tlp-rdw-nm.in
--- a/tlp-rdw-nm.in
+++ b/tlp-rdw-nm.in
@@ -2,15 +2,35 @@
 # tlp-rdw - network manager dispatcher hook:
 #           enable/disable radios on ifup/ifdown
 #
-# Copyright (c) 2015 Thomas Koch <linrunner at gmx.net>
+# Copyright (c) 2016 Thomas Koch <linrunner at gmx.net>
 # This software is licensed under the GPL v2 or later.
 
 # --- Constants
 readonly LIBDIR="@TLP_TLIB@"
 readonly LIBS="tlp-functions tlp-rf-func"
 
-readonly RDW_NM_LOCK="rdw_nm"
-readonly RDW_NM_LOCKTIME=2
+# --- Functions
+
+check_switch_lock() { # switch listed radio devices
+    # and time-lock them afterwards if actually switched
+    # $1: device where the event originated -- do nothing if its time-locked
+    # $2: list of device types to switch
+    # $3: on/off
+    local dev
+
+    # quit if the originating *radio* device is time-locked (not LAN)
+    [ "$1" != "LAN" ] && check_timed_lock "${RDW_NM_LOCK}_$1" && return 1
+
+    for dev in $2; do
+        if [ -n "$dev" ] && [ "$dev" != "$1" ]; then
+            # device type is valid and not the originating one
+            # --> do switch with state change lock
+            device_switch $dev $3 "${RDW_NM_LOCK}_${dev}" $RDW_LOCKTIME
+        fi
+    done
+
+    return 0
+}
 
 # --- Source libraries
 for lib in $LIBS; do
@@ -34,20 +54,20 @@ itype="unknown"
 # Quit for invalid interfaces
 [ -n "$iface" ] && [ "$iface" != "none" ] || exit 0
 
-echo_debug "nm" "rdw_nm($iface).$action"
+# Quit for actions other than "up" and "down"
+[ "$action" = "up" ] || [ "$action" = "down" ] || exit 0
+
+echo_debug "nm" "+++ rdw_nm($iface).$action"
 if [ -n "$addpath" ]; then
     echo_debug "path" "PATH=$oldpath[$addpath]"
 else
     echo_debug "path" "PATH=$oldpath"
 fi
 
-# Quit if timed lock in progress
-check_timed_lock $RDW_NM_LOCK && exit 0
-
 # Determine interface type
 if cmd_exists $NMCLI ; then
     # nmcli is available --> check if nmcli dev output matches interface
-    itype="$($NMCLI dev | awk '$1 ~ /'$iface'/ { print $2; }')"
+    itype="$($NMCLI dev | awk '$1 ~ /^'$iface'$/ { print $2; }')"
 
     if [ -z "$itype" ]; then
         # iface is not found in nmcli dev output: many WWAN devices have
@@ -57,7 +77,27 @@ if cmd_exists $NMCLI ; then
         if wordinlist "$iface" "$wanifaces"; then
             itype="wwan"
         else
-            itype="unknown"
+            # fallback:
+            # if interface type detection with nmcli failed, then try to
+            # deduct it using interface name: it can happen if e.g.
+            # usb network card is unplugged
+            case "$iface" in
+                en* | eth*)
+                    itype="ethernet"
+                    ;;
+
+                wl*)
+                    itype="wifi"
+                    ;;
+
+                ww*)
+                    itype="wwan"
+                    ;;
+
+                *)
+                    itype="unknown"
+                    ;;
+            esac
         fi
     fi
     echo_debug "nm" "rdw_nm($iface).$action: type=$itype [nmcli]"
@@ -69,25 +109,17 @@ fi
 case $action in
     up) # interface up, disable configured interfaces
 
-        set_timed_lock $RDW_NM_LOCK $RDW_NM_LOCKTIME # lock rdw events
-
         case $itype in
             *ethernet)
-                for dev in $DEVICES_TO_DISABLE_ON_LAN_CONNECT; do
-                    [ -n "$dev" ] && device_switch $dev off
-                done
+                check_switch_lock LAN "$DEVICES_TO_DISABLE_ON_LAN_CONNECT" off
                 ;;
 
             *wireless|wifi)
-                for dev in $DEVICES_TO_DISABLE_ON_WIFI_CONNECT; do
-                    [ -n "$dev" ] && [ "$dev" != wifi ] && device_switch $dev off
-                done
+                check_switch_lock wifi "$DEVICES_TO_DISABLE_ON_WIFI_CONNECT" off
                 ;;
 
             gsm|wwan)
-                for dev in $DEVICES_TO_DISABLE_ON_WWAN_CONNECT; do
-                    [ -n "$dev" ] && [ "$dev" != wwan ] && device_switch $dev off
-                done
+                check_switch_lock wwan "$DEVICES_TO_DISABLE_ON_WWAN_CONNECT" off
                 ;;
         esac
         ;; # up
@@ -95,21 +127,15 @@ case $action in
     down) # interface down, enable configured interfaces
         case $itype in
             *ethernet)
-                for dev in $DEVICES_TO_ENABLE_ON_LAN_DISCONNECT; do
-                    [ -n "$dev" ] && device_switch $dev on
-                done
+                check_switch_lock LAN "$DEVICES_TO_ENABLE_ON_LAN_DISCONNECT" on
                 ;;
 
             *wireless|wifi)
-                for dev in $DEVICES_TO_ENABLE_ON_WIFI_DISCONNECT; do
-                    [ -n "$dev" ] && [ "$dev" != wifi ] && device_switch $dev on
-                done
+                check_switch_lock wifi "$DEVICES_TO_ENABLE_ON_WIFI_DISCONNECT" on
                 ;;
 
-            gsm)
-                for dev in $DEVICES_TO_ENABLE_ON_WWAN_DISCONNECT; do
-                    [ -n "$dev" ] && [ "$dev" != wwan ] && device_switch $dev on
-                done
+            gsm|wwan)
+                check_switch_lock wwan "$DEVICES_TO_ENABLE_ON_WWAN_DISCONNECT" on
                 ;;
         esac
         ;; # down
