bat.d driver: ThinkPads w/ natacpi/tpacpi-bat

diff --git a/tlp.in b/tlp.in
--- a/tlp.in
+++ b/tlp.in
@@ -242,15 +242,6 @@ case "$pwrmode" in
     *) echo_debug "run" "power_mode=unknown ($pwrmode)" ;;
 esac
 
-# source and initialize all battery feature drivers until a matching one is found
-for batdrv in @TLP_BATD@/[0-9][0-9]*; do
-    # shellcheck disable=SC1090
-    . $batdrv || exit 70
-
-    # end iteration when a matching driver is found
-    batdrv_init && break
-done
-
 # process command
 exitcode=0
 
@@ -455,7 +446,7 @@ case "$_cmd" in
     fullcharge) # charge battery to 100% (temporarily)
         if check_ac_power fullcharge; then
             check_root
-            setcharge_battery 0 0 $_carg1
+            setcharge_battery DEF DEF $_carg1
             exitcode=$?
             if [ $exitcode -eq 0 ]; then
                 echo "Charging starts now, keep AC connected."
@@ -496,15 +487,16 @@ case "$_cmd" in
         if check_ac_power recalibrate; then
             check_root
             if lock_tlp_nb tlp_discharge; then
-                setcharge_battery 96 100 $_carg1
-                sleep 1
-                discharge_battery $_carg1
-                exitcode=$?
-                if [ $exitcode -eq 0 ]; then
-                    echo "Charging starts now, for a complete recalibration"
-                    echo "keep AC connected until the battery is fully charged."
-                else
-                    echo "Battery recalibration aborted."
+                if setcharge_battery DEF DEF $_carg1; then
+                    sleep 1
+                    discharge_battery $_carg1
+                    exitcode=$?
+                    if [ $exitcode -eq 0 ]; then
+                        echo "Charging starts now, for a complete recalibration"
+                        echo "keep AC connected until the battery is fully charged."
+                    else
+                        echo "Battery recalibration aborted."
+                    fi
                 fi
             else
                 echo_discharge_locked
@@ -520,7 +512,8 @@ case "$_cmd" in
 
     noop) # Debug: no operation
         check_root
-        battery_present DEF
+        select_batdrv
+        batdrv_select_battery "DEF"
         save_runconf
         echo "Debug: no operation performed."
         ;;
