tlp init: "opportunistic" locking strategy
Rationale: 'tlp init' may concur with 'tlp auto' during system
startup/shutdown and thus skip execution because of the
non-blocking lock.

Solution: change lock to blocking-with-timeout and continue
after the timeout even when a lock could not be obtained.

Credits: André

diff --git a/tlp.in b/tlp.in
--- a/tlp.in
+++ b/tlp.in
@@ -83,59 +83,66 @@ exitcode=0
 case "$mode" in
     init) # system initialization/shutdown: sysv, upstart, systemd, ...
         check_root
-        if lock_tlp_nb; then
-            case $mode2 in
-                start|restart|force-reload)
-                    # apply radio states
-                    set_radio_device_states start
 
-                    # apply power save settings -- but only if not previously run
-                    # (by the udev rule) for the same power state
-                    if compare_and_save_power_state $pwrmode; then
-                        echo -n "Applying power save settings..."
-                        apply_common_settings $pwrmode
-                        [ "$pwrmode" = "1" ] && poweroff_drivebay 0
-                        [ "$X_TLP_USB_MODE" = "1" ] && set_usb_suspend 0 auto
-                        echo "done."
-                    fi
-
-                    # apply battery settings
-                    echo -n "Setting battery charge thresholds..."
-                    set_charge_thresholds
-                    echo "done."
-                    ;;
-
-                stop)
-                    set_radio_device_states stop
-
-                    if [ "$USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN" = "1" ]; then
-                        echo -n "Disabling usb autosuspend..."
-                        set_usb_suspend 0 on
-                        echo "done."
-                    fi
-
-                    # remove usb startup flag
-                    [ -f $USB_DONE ] && rm $USB_DONE
-
-                    # clear saved power state
-                    clear_saved_power_state
-
-                    # apply ac settings for faster shutdown
-                    echo -n "Applying power save settings..."
-                    apply_common_settings 0
-                    echo "done."
-                    ;;
-
-                *)
-                    echo "Usage: tlp init {start|stop|restart|force-reload}" >&2
-                    exit 3
-                    ;;
-            esac
-            unlock_tlp
+        # try to obtain lock (with timeout)
+        locked=0
+        if lock_tlp; then
+            locked=1
         else
-            echo_tlp_locked
-            exitcode=4
+            echo "Failed to get lock, continuing anyway." 1>&2
         fi
+
+        # do init business ...
+        case $mode2 in
+            start|restart|force-reload)
+                # apply radio states
+                set_radio_device_states start
+
+                # apply power save settings -- but only if not previously run
+                # (by the udev rule) for the same power state
+                if compare_and_save_power_state $pwrmode; then
+                    echo -n "Applying power save settings..."
+                    apply_common_settings $pwrmode
+                    [ "$pwrmode" = "1" ] && poweroff_drivebay 0
+                    [ "$X_TLP_USB_MODE" = "1" ] && set_usb_suspend 0 auto
+                    echo "done."
+                fi
+
+                # apply battery settings
+                echo -n "Setting battery charge thresholds..."
+                set_charge_thresholds
+                echo "done."
+                ;;
+
+            stop)
+                set_radio_device_states stop
+
+                if [ "$USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN" = "1" ]; then
+                    echo -n "Disabling usb autosuspend..."
+                    set_usb_suspend 0 on
+                    echo "done."
+                fi
+
+                # remove usb startup flag
+                [ -f $USB_DONE ] && rm $USB_DONE
+
+                # clear saved power state
+                clear_saved_power_state
+
+                # apply ac settings for faster shutdown
+                echo -n "Applying power save settings..."
+                apply_common_settings 0
+                echo "done."
+                ;;
+
+            *)
+                echo "Usage: tlp init {start|stop|restart|force-reload}" >&2
+                exit 3
+                ;;
+        esac
+
+        # unlock if necessary
+        [ $locked -eq 0 ] || unlock_tlp
         ;;
 
     auto) # set mode depending on state (called by udev rule)
