Ensure TLP's and NM's wifi|wwan states are in sync (fix)
Refactor and fix radio device detection and state r/w code.

Reference:
* https://thinkpad-forum.de/threads/tlp-1-9-alpha-testergebnisse.244864/page-4#post-2452741

diff --git a/func.d/30-tlp-func-rf-sw b/func.d/30-tlp-func-rf-sw
--- a/func.d/30-tlp-func-rf-sw
+++ b/func.d/30-tlp-func-rf-sw
@@ -22,124 +22,117 @@ readonly RDW_DOCK_LOCK="rdw_dock"
 readonly RDW_NM_LOCKTIME=2
 readonly RDW_KILL="rdw_kill"
 
-readonly RFSTATEFILE=$VARDIR/rfkill_saved
+readonly RFSTATEFILE="$VARDIR/rfkill_saved"
 
 # ----------------------------------------------------------------------------
 # Functions
 
-get_devc () { # get control device for radio type
-              # $1: rftype bluetooth/nfc/wifi/wwan
-              # retval $_devc: sysdev, $_devs: device state
-              #     $_rfkdev: 1/0=is/is not an rfkill device,
-              #     $_devon, $_devoff: value to write directly to the sysdev
-              #     to achieve the desired switch state
+get_rf_dev_state () {
+    # get radio device state
+    # $1: rftype
+    # rc: 0=ok/1=no device (or unknown type)
+    # retval $_devs: 0=off/1=on/254=no device (or unknown type)
+    #        $_devc: sysfs rkill state
 
-    local i
+    local rfki rfks
 
-    # preset retvals
-    _devc=""
+    # preset: no device
     _devs=254
-    _rfkdev="1"
-    _devon="1"
-    _devoff="0"
+    _devc=""
 
+    # step 1: get control device for radio type
     case "$1" in
         wwan|bluetooth|nfc)
-            for i in /sys/class/rfkill/rfkill* ; do
-                if [ "$(read_sysf "$i/type")" = "$1" ]; then
-                    _devc="$i/state"
-                    echo_debug "rf" "get_devc($1) = $_devc"
-                    return 0
+            for rfki in /sys/class/rfkill/rfkill* ; do
+                if [ "$(read_sysf "$rfki/type")" = "$1" ]; then
+                    _devc="$rfki/state"
                 fi
             done
             ;;
 
         wifi)
-            for i in /sys/bus/pci/drivers/ipw2?00/*/rf_kill; do
-                if [ -f "$i" ]; then
-                    _devc="$i"
-                    _rfkdev="0"
-                    _devon="0"
-                    _devoff="1"
-                    echo_debug "rf" "get_devc($1) = $_devc"
-                    return 0
-                fi
-            done
-
-            for i in /sys/class/rfkill/rfkill* ; do
-                if [ "$(read_sysf "$i/type")" = "wlan" ]; then
-                    _devc="$i/state"
-                    echo_debug "rf" "get_devc($1) = $_devc"
-                    return 0
+            for rfki in /sys/class/rfkill/rfkill* ; do
+                if [ "$(read_sysf "$rfki/type")" = "wlan" ]; then
+                    _devc="$rfki/state"
                 fi
             done
             ;;
 
         *)
+            # unknown radio type -> quit
             cecho "Error: unknown device type $1" 1>&2
-            echo_debug "rf" "get_devc($1).unknown_type"
-            return 0
+            echo_debug "rf" "get_rf_dev_state($1).unknown_type"
+            return 1
             ;;
     esac
 
-    echo_debug "rf" "get_devc($1).not_present"
-
-    return 0
-}
-
-get_devs () { # get radio device state -- $1: rftype; retval $_devs: 0=off/1=on
-              # prerequisite: get_devc()
-
-    local rfks
-
-    if [ -n "$_devc" ]; then
-        if check_nm && wordinlist "$1" "wifi wwan" && [ "$_rfkdev" = "1" ]; then
-            case "$($NMCLI radio "$1" 2> /dev/null)" in
-                enabled) _devs=1 ;;
-                disabled)
-                    rfks="$(read_sysf "$_devc")"
-                    case "$rfks" in
-                        0) _devs=0 ;; # soft blocked
-                        2) _devs=2 ;; # hard blocked device
-                    esac
-                    ;;
-                *) _devs=3 # unknown state
-            esac
-            echo_debug "rf" "get_devs.nmcli($1) = $_devs"
-        else
-            _devs="$(read_sysf "$_devc")"
-            case "$_devs" in
-                0|1) # invert state when not a rfkill device
-                    [ "$_rfkdev" = "0" ] && _devs=$((_devs ^ _devoff))
-                    ;;
-                2) ;; # hard blocked device
-                *) _devs=3 # unknown state
-            esac
-            echo_debug "rf" "get_devs.sysfs($1) = $_devs"
-        fi
+    if [ -z "$_devc" ]; then
+        # no device of this radio type -> quit
+        echo_debug "rf" "get_rf_dev_state($1).not_present"
+        return 1
     fi
 
+    # step 2: get state for radio type
+    if check_nm && wordinlist "$1" "wifi wwan";  then
+        # read state from rfkill sysfs first ...
+        rfks="$(read_sysf "$_devc")"
+        # ... then get state from NM
+        case "$($NMCLI radio "$1" 2> /dev/null)" in
+            enabled)
+                # assumption: the case NM(on), rfkill(off) does not occur
+                _devs=1
+                ;;
+
+            disabled)
+                case "$rfks" in
+                    0) _devs=0 ;; # rfkill soft blocked
+                    1) _devs=0 ;; # NM=off and rfkill=unblocked i.e. states are *not* in sync
+                                  # -> return off(soft blocked) to keep things going
+                    2) _devs=2 ;; # rfkill hard blocked
+                esac
+                ;;
+            *) _devs=3 # unknown state
+        esac
+        echo_debug "rf" "get_rf_dev_state.nmcli($1) = $_devs; devc=$_devc; rfkill=$rfks"
+    else
+        # get state from rfkill sysfs
+        _devs="$(read_sysf "$_devc")"
+        case "$_devs" in
+            0|1|2)     ;; # 0=soft blocked(off)/1=unblocked(on)/2=hard blocked(off)
+            *) _devs=3 ;; # unknown state
+        esac
+        echo_debug "rf" "get_rf_dev_state.sysfs($1) = $_devs; devc=$_devc"
+    fi
 
     return 0
 }
 
-err_no_root_priv () { # check root privilege
+err_no_root_priv () {
+    # check root privilege
+
     cecho "Error: missing root privilege." 1>&2
     echo_debug "rf" "$1.missing_root_privilege"
 
     return 0
 }
 
-test_rfkill_perms () { # test if either root priv or rfkill device writable
+test_rfkill_perms () {
+    # test if either root priv or rfkill device writable
+
     test_root || [ -w $RFKD ]
 }
 
-check_nm () { # test if NetworkManager is installed
+check_nm () {
+    # test if NetworkManager is installed
+
     [ "$X_USE_NMCLI" != "0" ] && cmd_exists $NMCLI
 }
 
-invoke_nmcli () { # call nmcli with radio option according to the program version
-                  # $1: rftype, $2: on/off, $3: caller; rc: last nmcli rc
+invoke_nmcli () {
+    # call nmcli to switch radio
+    # $1: rftype, $2: on/off, $3: caller
+    # rc: nmcli rc
+
     local rc
 
     check_nm || return 0 # return if NetworkManager not running
@@ -150,41 +143,31 @@ invoke_nmcli () { # call nmcli with radio option according to the program versio
     return $rc
 }
 
-device_state () { # get radio type state -- $1: rftype; retval $_devc, $_devs: 0=off/1=on
-    echo_debug "rf" "device_state($1)"
-
-    get_devc "$1"
-    get_devs "$1"
-}
-
-device_switch () { # switch radio type state
-                   # $1: rftype, $2: 1/on/0/off/toggle
-                   # $3: lock id, $4: lock duration
-                   # rc: 0=switched/1=invalid device or operation/
-                   #     2=hard blocked/3=invalid state/4=no change
-                   # retval $_devc, $_devs: 0=off/1=on
+device_switch () {
+    # switch radio state
+    # $1: rftype, $2: 1/on/0/off/toggle
+    # $3: lock id, $4: lock duration
+    # rc: 0=switched/1=invalid device or operation/
+    #     2=hard blocked/3=invalid state/4=no change
+    # retval $_devc, $_devs: 0=off/1=on
 
     local curst newst devn
 
     echo_debug "rf" "device_switch($1, $2, $3, $4)"
 
-    get_devc "$1"
-
-    # quit if no device
-    if [ -z "$_devc" ]; then
+    # get current device state
+    if ! get_rf_dev_state "$1"; then
+        #  no device -> quit
         echo_debug "rf" "device_switch($1, $2).no_device: rc=1"
         return 1
     fi
+    curst="$_devs"
 
     # quit if invalid operation
     if ! wordinlist "$2" "on 1 off 0 toggle"; then
         echo_debug "rf" "device_switch($1, $2).invalid_op: rc=1"
         return 1
     fi
-
-    # get current device state
-    get_devs "$1"
-    curst="$_devs"
 
     # quit if device state is hard blocked or invalid
     if [ "$_devs" -ge 2 ]; then
@@ -214,16 +197,16 @@ device_switch () { # switch radio type state
         [ -n "$3" ] && [ -n "$4" ] && [ "$1" != "bluetooth" ] && \
             set_timed_lock "$3" "$4"
 
-        if check_nm && wordinlist "$1" "wifi wwan" && [ "$_rfkdev" = "1" ]; then
+        if check_nm && wordinlist "$1" "wifi wwan"; then
             # switch device with NetworkManager
             case "$newst" in
                 1) invoke_nmcli "$1" on  ;;
                 0) invoke_nmcli "$1" off ;;
             esac
             # record device state after nmcli
-            get_devs "$1"
+            get_rf_dev_state "$1"
 
-        elif [ "$_rfkdev" = "1" ] && cmd_exists $RFKILL ; then
+        elif cmd_exists $RFKILL ; then
             # switch device with rfkill
             if test_rfkill_perms ; then
                 # use rfkill
@@ -234,22 +217,19 @@ device_switch () { # switch radio type state
                     *) ;;
                 esac
                 # record device state after rfkill
-                get_devs "$1"
+                get_rf_dev_state "$1"
             else
                 # missing permission to rfkill
                 err_no_root_priv "device_switch($1, $2).rfkill"
             fi
         else
             # switch device with direct write
-            case "$newst" in
-                1) devn="$_devon"  ;;
-                0) devn="$_devoff" ;;
-            esac
+            # TODO: can't we remove that?
             if test_root ; then
-                write_sysf "$devn" "$_devc"
+                write_sysf "$newst" "$_devc"
                 echo_debug "rf" "device_switch($1, $2).devc: rc=$?"
                 # record device state after direct write
-                get_devs "$1"
+                get_rf_dev_state "$1"
             else
                 err_no_root_priv "device_switch($1, $2).devc"
             fi
@@ -276,8 +256,10 @@ device_switch () { # switch radio type state
     fi
 }
 
-echo_device_state () { # print radio type state -- $1: rftype, $2: state
-                       # prerequisite: get_devc(), get_devs()
+echo_device_state () {
+    # print radio state -- $1: rftype, $2: state
+    # prerequisite: get_rf_dev_state()
+    #
     case "$1" in
         bluetooth)
             devstr="bluetooth"
@@ -325,8 +307,11 @@ echo_device_state () { # print radio type state -- $1: rftype, $2: state
 }
 
 # shellcheck disable=SC2120
-save_device_states () { # save radio states -- $1: list of rftypes
-                        # rc: 0=ok/1=create failed/2=write failed
+save_device_states () {
+    # save radio states
+    # $1: list of rftypes
+    # rc: 0=ok/1=create failed/2=write failed
+
     local dev
     local devlist="${1:-$ALLDEV}" # when arg empty -> use all
     local rc=0
@@ -335,7 +320,7 @@ save_device_states () { # save radio states -- $1: list of rftypes
     if [ -d "$VARDIR" ] && { : > "$RFSTATEFILE"; } 2> /dev/null; then
         # iterate over all possible devices -> save state in file
         for dev in $devlist; do
-            device_state "$dev"
+            get_rf_dev_state "$dev"
             { printf '%s\n' "$dev $_devs" >> "$RFSTATEFILE"; } 2> /dev/null || rc=2
         done
     else
@@ -347,8 +332,10 @@ save_device_states () { # save radio states -- $1: list of rftypes
     return $rc
 }
 
-restore_device_states () { # restore radio type states
-                           # rc: 0=ok/1=state file nonexistent
+restore_device_states () {
+    # restore radio states
+    # rc: 0=ok/1=state file nonexistent
+
     local sline
     local rc=0
 
@@ -369,9 +356,11 @@ restore_device_states () { # restore radio type states
     return $rc
 }
 
-set_radio_device_states () { # set/initialize all radio states
+set_radio_device_states () {
+    # set/initialize all radio states
     # $1: start/stop/PP_PRF=0/PP_BAL=1/PP_SAV=2/radiosw
     # called from init scripts or upon change of power source
+
     local dev devs2disable devs2enable restore
     local quiet=0
 
